import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import fastifyStatic from '@fastify/static';
import rawBody from 'fastify-raw-body';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { initDb, q, pool, dbReady } from './lib/db.mjs';
import { initCache, redis, cacheRemember } from './lib/cache.mjs';
import { AUTHORIZED_ORIGINS, CLERK_ENABLED, hashPassword, verifyPassword, createSession, destroySession, currentUser, requireUser, requireRole, validateOrigin, getClerkClient, beginAccountDeletion, cancelAccountDeletion, bootstrapConfiguredAdmins, invalidateUserIdentityCache } from './lib/auth.mjs';
import { processClerkWebhook } from './lib/clerk-webhook.mjs';
import { getCatalog, getReading, getSchedule, getAnime, getAnimeThemes, getMediaSummaries, getManga, getStudios, getDubbed, prewarm } from './lib/provider.mjs';
import { lists } from './lib/content.mjs';
import { getNativeNews, getNativeArticle, articleExpiry } from './lib/native-news.mjs';
import { enqueueAnalytics, flushAnalytics, analyticsStats } from './lib/analytics.mjs';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const trustProxy=['127.0.0.1','::1','10.0.0.0/8','172.16.0.0/12','192.168.0.0/16'];
const app=Fastify({logger:true,trustProxy,bodyLimit:1_000_000,requestTimeout:15_000,connectionTimeout:10_000,keepAliveTimeout:72_000});
await app.register(cookie);
await app.register(cors,{origin:(origin,callback)=>{if(!origin||AUTHORIZED_ORIGINS.includes(origin))return callback(null,true);return callback(null,false)},methods:['GET','HEAD','POST','PUT','PATCH','DELETE','OPTIONS'],allowedHeaders:['accept','authorization','content-type'],exposedHeaders:['retry-after'],credentials:false,maxAge:600,strictPreflight:true});
await app.register(rawBody,{field:'rawBody',global:false,encoding:false,runFirst:true,routes:['/api/webhooks/clerk']});
await app.register(helmet,{global:true,crossOriginEmbedderPolicy:false,contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'",'https://*.clerk.accounts.dev','https://*.clerk.com','https://challenges.cloudflare.com','https://*.protect.clerk.com'],styleSrc:["'self'","'unsafe-inline'",'https://fonts.googleapis.com'],fontSrc:["'self'",'https://fonts.gstatic.com'],imgSrc:["'self'",'data:','https:','https://img.clerk.com'],connectSrc:["'self'",'https://graphql.anilist.co','https://api.jikan.moe','https://api.mymemory.translated.net','https://translate.googleapis.com','https://api.animethemes.moe','https://listen.moe','wss://listen.moe','https://*.clerk.accounts.dev','https://api.clerk.com','https://*.protect.clerk.com:*'],mediaSrc:["'self'",'https://v.animethemes.moe','https://listen.moe'],frameSrc:["'self'",'https://www.youtube-nocookie.com','https://www.youtube.com','https://www.dailymotion.com','https://*.clerk.accounts.dev','https://challenges.cloudflare.com','https://*.protect.clerk.com'],workerSrc:["'self'",'blob:'],objectSrc:["'none'"],baseUri:["'self'"],frameAncestors:["'none'"],formAction:["'self'",'https://*.clerk.accounts.dev']}}});
await app.register(rateLimit,{global:false,max:120,timeWindow:'1 minute',ban:2,hook:'preHandler'});
app.decorateRequest('aninexusUser',null);
await app.register(fastifyStatic,{root:path.join(__dirname,'public'),prefix:'/',decorateReply:true,maxAge:'1h',immutable:false});
await app.register(fastifyStatic,{root:path.join(__dirname,'assets'),prefix:'/assets/',decorateReply:false,maxAge:'7d',immutable:true});

app.addHook('onRequest',async(req,reply)=>{if(!validateOrigin(req,reply))return reply;});
app.addHook('onSend',async(req,reply,payload)=>{
  reply.header('Permissions-Policy','camera=(), microphone=(), geolocation=(), payment=(), usb=(), serial=()');
  reply.header('Referrer-Policy','strict-origin-when-cross-origin');
  reply.header('X-Content-Type-Options','nosniff');
  reply.header('X-Permitted-Cross-Domain-Policies','none');
  const url=String(req.url||'').split('?')[0];
  if(url.startsWith('/api/auth/')||url.startsWith('/api/me'))reply.header('Cache-Control','no-store');
  else if(req.method==='GET'&&/^\/api\/(home|catalog|reading|schedule|anime\/\d+|manga\/\d+|media\/summaries|studios|dublados|lists|list\/|users\/|news(?:\/|$)|community\/(?:impressions|activity|threads))/.test(url))reply.header('Cache-Control','public, max-age=20, stale-while-revalidate=180, stale-if-error=600');
  else if(req.method==='GET'&&(url==='/'||reply.getHeader('content-type')?.toString().includes('text/html')))reply.header('Cache-Control','no-cache, max-age=0, must-revalidate');
  if(process.env.PUBLIC_ORIGIN?.startsWith('https://'))reply.header('Strict-Transport-Security','max-age=31536000; includeSubDomains; preload');
  return payload;
});
app.setErrorHandler((error,req,reply)=>{req.log.error({err:error},'request failed');if(reply.sent)return;const status=error.statusCode&&error.statusCode>=400&&error.statusCode<600?error.statusCode:500;reply.code(status).send({error:status>=500?'INTERNAL_ERROR':'REQUEST_FAILED'});});

const authenticateForRate=async(request,reply)=>{
  const user=await requireUser(request,reply);
  if(user)request.aninexusUser=user;
};
const authenticatedRateKey=request=>request.aninexusUser?.id?`user:${request.aninexusUser.id}`:`ip:${request.ip}`;
const rateForUser=(max,timeWindow,groupId)=>({preValidation:authenticateForRate,config:{rateLimit:{max,timeWindow,groupId,keyGenerator:authenticatedRateKey}}});
const authRate={config:{rateLimit:{max:8,timeWindow:'1 minute',groupId:'auth',keyGenerator:request=>request.ip}}};
const privateReadRate=rateForUser(120,'1 minute','private-read');
const privateHeavyRate=rateForUser(20,'1 minute','private-heavy');
const writeRate=rateForUser(30,'1 minute','private-write');
const publicRate={config:{rateLimit:{max:240,timeWindow:'1 minute'}}};
const currentSeason=()=>{const now=new Date(),month=Number(new Intl.DateTimeFormat('en',{timeZone:'America/Sao_Paulo',month:'numeric'}).format(now)),year=Number(new Intl.DateTimeFormat('en',{timeZone:'America/Sao_Paulo',year:'numeric'}).format(now));return{season:month<=3?'WINTER':month<=6?'SPRING':month<=9?'SUMMER':'FALL',year}};
const safeUser=u=>u&&({id:u.id,email:u.email,username:u.username,displayName:u.display_name||u.username,role:u.role,status:u.status||'active',avatarUrl:u.avatar_url,bannerUrl:u.profile_banner_url||null,bio:u.bio,location:u.location||null,websiteUrl:u.website_url||null,instagramHandle:u.instagram_handle||null,telegramHandle:u.telegram_handle||null,showLibrary:u.show_library!==false,showActivity:u.show_activity!==false,showStats:u.show_stats!==false,theme:u.theme,privacy:u.privacy||'public',emailVerified:u.email_verified,createdAt:u.created_at});
const safeInt=(v,min=1,max=Number.MAX_SAFE_INTEGER)=>{const n=Number(v);return Number.isSafeInteger(n)&&n>=min&&n<=max?n:null};
const safePath=v=>{const s=String(v||'').slice(0,500);return s.startsWith('/')&&!s.startsWith('//')?s:null};
const strongPassword=z.string().min(10).max(128).refine(v=>/[A-Za-zÀ-ÿ]/.test(v)&&/\d/.test(v),{message:'WEAK_PASSWORD'});
const usernameSchema=z.string().trim().min(3).max(30).regex(/^[\p{L}\p{N}_.-]+$/u).refine(value=>!/^(?:admin(?:istrator)?|moderador|moderator|suporte|support|aninexus|equipe|staff|sistema|system)$/i.test(value),{message:'RESERVED_USERNAME'});
const nullableText=(max,min=0)=>z.union([z.string().trim().min(min).max(max),z.literal(''),z.null()]).transform(value=>value||null);
const nullableHttpsUrl=z.union([z.string().trim().url().max(2000).refine(value=>value.startsWith('https://')),z.literal(''),z.null()]).transform(value=>value||null);
const nullableHandle=max=>z.preprocess(value=>typeof value==='string'?value.trim().replace(/^@+/, ''):value,z.union([z.string().regex(/^[A-Za-z0-9_.]+$/).max(max),z.literal(''),z.null()])).transform(value=>value||null);
const DUMMY_PASSWORD_HASH=CLERK_ENABLED?'':await hashPassword('aninexus-invalid-password-sentinel-do-not-use-8401');
const mediaProjection=`CASE WHEN mc.media_id IS NULL THEN NULL ELSE jsonb_build_object(
  'id',mc.media_id,'title',mc.payload->>'title','cover',mc.payload->>'cover','banner',mc.payload->>'banner',
  'score',mc.payload->'score','episodes',mc.payload->'episodes','status',mc.payload->>'status','format',mc.payload->>'format',
  'seasonYear',mc.payload->'seasonYear','genres',COALESCE(mc.payload->'genres','[]'::jsonb),'slug',mc.payload->>'slug'
) END`;
const hydrateCommunityMedia=async rows=>{
  const missing=[...new Set(rows.filter(row=>row.media_id&&!row.media).map(row=>Number(row.media_id)).filter(Number.isSafeInteger))];
  if(!missing.length)return rows;
  try{const resolved=await getMediaSummaries(missing),byId=new Map(resolved.map(media=>[Number(media.id),media]));return rows.map(row=>row.media?row:{...row,media:byId.get(Number(row.media_id))||null})}
  catch(error){app.log.warn({err:error,mediaIds:missing},'community media hydration failed');return rows}
};
const transaction=async fn=>{const client=await pool.connect();try{await client.query('BEGIN');const result=await fn(client);await client.query('COMMIT');return result}catch(error){await client.query('ROLLBACK').catch(()=>{});throw error}finally{client.release()}};

app.get('/health',async()=>({ok:true,uptime:Math.round(process.uptime()),time:new Date().toISOString()}));
app.get('/health/ready',async(req,reply)=>{const [db,cache]=await Promise.all([dbReady(),(async()=>{try{return redis.isReady&&(await redis.ping())==='PONG'}catch{return false}})()]);const ok=db&&cache;return reply.code(ok?200:503).send({ok,db,cache});});
app.get('/api/me',privateReadRate,async(req,reply)=>{const user=await requireUser(req,reply);if(!user)return;return{user:safeUser(user)}});
app.get('/api/users/:username',publicRate,async(req,reply)=>{
  const parsed=usernameSchema.safeParse(String(req.params.username||''));if(!parsed.success)return reply.code(404).send({error:'NOT_FOUND'});
  const requested=parsed.data;
  let result=await q('SELECT * FROM users WHERE username=$1 AND deleted_at IS NULL AND status=\'active\'',[requested]);
  let aliased=false;
  if(!result.rows[0]){result=await q(`SELECT u.* FROM user_profile_aliases a JOIN users u ON u.id=a.user_id WHERE a.alias=$1 AND u.deleted_at IS NULL AND u.status='active'`,[requested]);aliased=!!result.rows[0]}
  const user=result.rows[0];if(!user)return reply.code(404).send({error:'NOT_FOUND'});
  const isPrivate=user.privacy!=='public';
  const profile={username:user.username,displayName:user.display_name||user.username,avatarUrl:user.avatar_url,bannerUrl:user.profile_banner_url||null,bio:isPrivate?null:user.bio,location:isPrivate?null:user.location,websiteUrl:isPrivate?null:user.website_url,instagramHandle:isPrivate?null:user.instagram_handle,telegramHandle:isPrivate?null:user.telegram_handle,role:user.role,privacy:user.privacy,isPrivate,showLibrary:user.show_library!==false,showActivity:user.show_activity!==false,showStats:user.show_stats!==false,createdAt:user.created_at};
  if(isPrivate)return{profile,canonicalUsername:user.username,aliased,stats:null,library:[],activity:[],impressions:[]};
  const [statsResult,libraryResult,activityResult,impressionsResult]=await Promise.all([
    user.show_stats===false?Promise.resolve({rows:[]}):q(`SELECT count(*)::int list_total,count(*) FILTER(WHERE status='CURRENT')::int watching,count(*) FILTER(WHERE status='COMPLETED')::int completed,count(*) FILTER(WHERE status='PLANNING')::int planning,COALESCE(sum(progress),0)::int episodes_watched,round(avg(score)::numeric,1) average_score,(SELECT count(*)::int FROM user_favorites WHERE user_id=$1) favorites FROM user_anime WHERE user_id=$1`,[user.id]),
    user.show_library===false?Promise.resolve({rows:[]}):q(`SELECT ua.media_id,ua.status,ua.score,ua.reaction,ua.progress,ua.updated_at,${mediaProjection} AS media FROM user_anime ua LEFT JOIN media_cache mc ON mc.media_id=ua.media_id WHERE ua.user_id=$1 ORDER BY ua.updated_at DESC LIMIT 36`,[user.id]),
    user.show_activity===false?Promise.resolve({rows:[]}):q(`SELECT ua.media_id,ua.status,ua.score,ua.reaction,ua.progress,ua.updated_at AS created_at,${mediaProjection} AS media FROM user_anime ua LEFT JOIN media_cache mc ON mc.media_id=ua.media_id WHERE ua.user_id=$1 ORDER BY ua.updated_at DESC LIMIT 12`,[user.id]),
    user.show_activity===false?Promise.resolve({rows:[]}):q(`SELECT i.id,i.media_id,i.body,i.spoiler,i.created_at,${mediaProjection} AS media FROM impressions i LEFT JOIN media_cache mc ON mc.media_id=i.media_id WHERE i.user_id=$1 AND i.hidden=false ORDER BY i.created_at DESC LIMIT 12`,[user.id]),
  ]);
  const [library,activity,impressions]=await Promise.all([hydrateCommunityMedia(libraryResult.rows),hydrateCommunityMedia(activityResult.rows),hydrateCommunityMedia(impressionsResult.rows)]);
  return{profile,canonicalUsername:user.username,aliased,stats:statsResult.rows[0]||null,library,activity,impressions};
});
app.post('/api/auth/register',authRate,async(req,reply)=>{
  if(CLERK_ENABLED)return reply.code(410).send({error:'AUTH_MANAGED_BY_CLERK'});
  const parsed=z.object({email:z.string().trim().toLowerCase().email().max(254),username:usernameSchema,password:strongPassword}).safeParse(req.body);
  if(!parsed.success)return reply.code(400).send({error:'INVALID_INPUT'});
  const {email,username,password}=parsed.data,passwordHash=await hashPassword(password);
  try{
    const {rows}=await q('INSERT INTO users(email,username,password_hash) VALUES($1,$2,$3) RETURNING *',[email,username,passwordHash]);
    await createSession(reply,rows[0],req);return reply.code(201).send({user:safeUser(rows[0])});
  }catch(err){if(err?.code==='23505')return reply.code(409).send({error:'ACCOUNT_UNAVAILABLE'});throw err;}
});
app.post('/api/auth/login',authRate,async(req,reply)=>{
  if(CLERK_ENABLED)return reply.code(410).send({error:'AUTH_MANAGED_BY_CLERK'});
  const parsed=z.object({login:z.string().trim().min(3).max(254),password:z.string().min(1).max(128)}).safeParse(req.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_INPUT'});
  const {rows}=await q('SELECT * FROM users WHERE (email=$1 OR username=$1) AND deleted_at IS NULL',[parsed.data.login]);const u=rows[0];
  const valid=await verifyPassword(u?.password_hash||DUMMY_PASSWORD_HASH,parsed.data.password);if(!u||!valid)return reply.code(401).send({error:'INVALID_CREDENTIALS'});
  if(u.status&&u.status!=='active')return reply.code(403).send({error:u.status==='banned'?'ACCOUNT_BANNED':'ACCOUNT_SUSPENDED'});
  await createSession(reply,u,req);return {user:safeUser(u)};
});
app.post('/api/auth/logout',writeRate,async(req,reply)=>{if(CLERK_ENABLED)return reply.code(204).send();await destroySession(req,reply);return {ok:true};});
app.post('/api/webhooks/clerk',{config:{rawBody:true,rateLimit:{max:120,timeWindow:'1 minute'}}},async(req,reply)=>{
  if(!CLERK_ENABLED)return reply.code(404).send({error:'NOT_FOUND'});
  try{return await processClerkWebhook(req)}catch(error){req.log.warn({err:error},'clerk webhook rejected');return reply.code(400).send({error:'INVALID_WEBHOOK'})}
});

const getHomePayload=async(query={})=>{
  const fallback=currentSeason(),season=['WINTER','SPRING','SUMMER','FALL'].includes(String(query?.season||''))?String(query.season):fallback.season,year=safeInt(query?.year,1960,2100)||fallback.year;
  const now=Math.floor(Date.now()/1000),bucket=Math.floor(now/300),end=now+7*86400;
  return cacheRemember(`home:v4:${season}:${year}:${bucket}`,60,async()=>{
    const [seasonData,schedule,top,popular,reading,topReading,soon]=await Promise.all([
      getCatalog({page:1,perPage:22,season,year,sort:'POPULAR'}).catch(()=>({items:[]})),getSchedule(now,end).catch(()=>[]),getCatalog({page:1,perPage:10,sort:'SCORE'}).catch(()=>({items:[]})),getCatalog({page:1,perPage:22,sort:'POPULAR'}).catch(()=>({items:[]})),getReading({page:1,perPage:18,sort:'POPULAR'}).catch(()=>({items:[]})),getReading({page:1,perPage:10,format:'MANGA',sort:'SCORE'}).catch(()=>({items:[]})),getCatalog({page:1,perPage:22,status:'NOT_YET_RELEASED',sort:'POPULAR'}).catch(()=>({items:[]}))
    ]);
    return{season:seasonData.items||[],schedule:(schedule||[]).slice(0,8),top:top.items||[],popular:popular.items||[],reading:reading.items||[],topReading:topReading.items||[],soon:soon.items||[]};
  },{staleTtl:1800});
};
const miniappEnvelope=data=>({ok:true,apiVersion:'1',source:'aninexus',generatedAt:new Date().toISOString(),data});
const miniappPublicRate={config:{rateLimit:{max:180,timeWindow:'1 minute',groupId:'miniapp-public'}}};

app.get('/api/catalog',{...publicRate,config:{rateLimit:{max:100,timeWindow:'1 minute'}}},async req=>getCatalog(req.query||{}));
app.get('/api/home',publicRate,async req=>getHomePayload(req.query||{}));
app.get('/api/reading',{...publicRate,config:{rateLimit:{max:100,timeWindow:'1 minute'}}},async req=>getReading(req.query||{}));

app.get('/api/miniapp/v1/health',miniappPublicRate,async()=>miniappEnvelope({status:'ready',uptime:Math.round(process.uptime())}));
app.get('/api/miniapp/v1/home',miniappPublicRate,async req=>miniappEnvelope(await getHomePayload(req.query||{})));
app.get('/api/miniapp/v1/catalog',miniappPublicRate,async req=>miniappEnvelope(await getCatalog(req.query||{})));
app.get('/api/miniapp/v1/reading',miniappPublicRate,async req=>miniappEnvelope(await getReading(req.query||{})));
app.get('/api/miniapp/v1/anime/:id',miniappPublicRate,async(req,reply)=>{const id=safeInt(req.params.id);if(!id)return reply.code(400).send({ok:false,apiVersion:'1',error:'INVALID_ID'});return miniappEnvelope(await getAnime(id));});
app.get('/api/schedule',{config:{rateLimit:{max:100,timeWindow:'1 minute'}}},async(req,reply)=>{const now=Math.floor(Date.now()/1000),start=Number(req.query?.start||now-86400),end=Number(req.query?.end||now+7*86400);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end-start>10*86400)return reply.code(400).send({error:'INVALID_RANGE'});return getSchedule(start,end);});
app.get('/api/anime/:id',{config:{rateLimit:{max:120,timeWindow:'1 minute'}}},async(req,reply)=>{const id=safeInt(req.params.id);if(!id)return reply.code(400).send({error:'INVALID_ID'});return getAnime(id);});
app.get('/api/anime/:id/rating',publicRate,async(req,reply)=>{const id=safeInt(req.params.id);if(!id)return reply.code(400).send({error:'INVALID_ID'});const {rows}=await q(`SELECT round(avg(score)::numeric,1) score,count(score)::int votes FROM user_anime WHERE media_id=$1 AND score IS NOT NULL`,[id]);return{score:rows[0]?.score==null?null:Number(rows[0].score),votes:Number(rows[0]?.votes||0)};});
app.get('/api/anime/:id/themes',{config:{rateLimit:{max:120,timeWindow:'1 minute'}}},async(req,reply)=>{const id=safeInt(req.params.id);if(!id)return reply.code(400).send({error:'INVALID_ID'});return getAnimeThemes(id);});
app.get('/api/media/summaries',{config:{rateLimit:{max:120,timeWindow:'1 minute'}}},async(req,reply)=>{const raw=String(req.query?.ids||'').split(',').slice(0,60),ids=raw.map(value=>safeInt(value)).filter(Boolean);if(!ids.length)return reply.code(400).send({error:'INVALID_IDS'});return{items:await getMediaSummaries(ids)}});
app.get('/api/manga/:id',{config:{rateLimit:{max:120,timeWindow:'1 minute'}}},async(req,reply)=>{const id=safeInt(req.params.id);if(!id)return reply.code(400).send({error:'INVALID_ID'});return getManga(id);});
app.get('/api/studios',publicRate,async req=>getStudios(Number(req.query?.page||1)));
app.get('/api/dublados',publicRate,async req=>getDubbed(Number(req.query?.page||1)));
app.get('/api/lists',publicRate,async()=>lists);
app.get('/api/list/:slug',publicRate,async(req,reply)=>{const l=lists.find(x=>x.slug===req.params.slug);if(!l)return reply.code(404).send({error:'NOT_FOUND'});const data=await getCatalog({page:req.query?.page||1,perPage:24,sort:l.sort,genre:l.genre,format:l.format,status:l.status,season:l.season,year:l.year});return {...l,...data};});

app.get('/api/news',publicRate,async(req)=>{const limit=Math.max(1,Math.min(60,Number(req.query?.limit||20))),offset=Math.max(0,Math.min(5000,Number(req.query?.offset||0)));const type=req.query?.type?String(req.query.type).slice(0,40):null;return{items:await getNativeNews({limit,offset,type})};});
app.get('/api/news/:slug',publicRate,async(req,reply)=>{const slug=String(req.params.slug||'').slice(0,180);const item=await getNativeArticle(slug);if(!item)return reply.code(404).send({error:'NOT_FOUND'});return item;});
app.get('/api/news/:slug/comments',publicRate,async(req,reply)=>{const slug=String(req.params.slug||'').slice(0,180),limit=Math.max(1,Math.min(100,Number(req.query?.limit||40)));const {rows}=await q(`SELECT c.id,c.parent_id,c.body,c.spoiler,c.created_at,u.username,u.display_name,u.avatar_url FROM news_comments c JOIN users u ON u.id=c.user_id WHERE c.article_slug=$1 AND c.hidden=false AND u.deleted_at IS NULL AND u.status='active' AND u.privacy='public' ORDER BY c.created_at ASC LIMIT $2`,[slug,limit]);return{items:rows};});
app.post('/api/news/:slug/comments',rateForUser(5,'1 minute','news-comments-write'),async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const slug=String(req.params.slug||'').slice(0,180),parsed=z.object({body:z.string().trim().min(2).max(1800),spoiler:z.boolean().optional(),parentId:z.string().uuid().nullable().optional()}).safeParse(req.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_INPUT'});const article=await getNativeArticle(slug);if(!article)return reply.code(404).send({error:'NOT_FOUND'});const normalized=parsed.data.body.normalize('NFKC');if(/https?:\/\/\S+/gi.test(normalized)&&((normalized.match(/https?:\/\/\S+/gi)||[]).length>2))return reply.code(422).send({error:'TOO_MANY_LINKS'});const {rows}=await q(`INSERT INTO news_comments(article_slug,user_id,parent_id,body,spoiler) VALUES($1,$2,$3,$4,$5) RETURNING id,created_at`,[u.id,slug,parsed.data.parentId||null,normalized,parsed.data.spoiler||false]);return reply.code(201).send({ok:true,...rows[0]});});
app.post('/api/news/comments/:id/report',rateForUser(8,'10 minutes','news-comments-report'),async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const id=z.string().uuid().safeParse(req.params.id),parsed=z.object({reason:z.string().trim().min(3).max(1000)}).safeParse(req.body);if(!id.success||!parsed.success)return reply.code(422).send({error:'INVALID_INPUT'});await q(`INSERT INTO content_reports(reporter_id,target_type,target_id,reason) VALUES($1,'NEWS_COMMENT',$2,$3)`,[u.id,id.data,parsed.data.reason]);return reply.code(201).send({ok:true});});
const articleSchema=z.object({title:z.string().trim().min(3).max(220),summary:z.string().trim().min(10).max(1200),body:z.string().max(30000).nullable().optional(),eventType:z.enum(['SEASON','TRAILER','EPISODE','MANGA','TRENDING','OTHER']).nullable().optional(),spoiler:z.boolean().optional(),mediaIds:z.array(z.number().int().positive()).max(30).optional(),imageUrl:z.string().url().max(2000).nullable().optional(),imageAlt:z.string().max(240).nullable().optional(),facts:z.array(z.string().max(500)).max(32).optional(),status:z.enum(['draft','review','scheduled','published','archived']).optional(),scheduledAt:z.string().datetime().nullable().optional(),expiresAt:z.string().datetime().nullable().optional()});
app.post('/api/admin/news',writeRate,async(req,reply)=>{const u=await requireRole(req,reply,['moderator','admin']);if(!u)return;const p=articleSchema.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'INVALID_INPUT'});const d=p.data,slug=`${d.title.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,100)}-${Date.now().toString(36)}`;const published=d.status==='published'?new Date():null,expires=d.expiresAt?new Date(d.expiresAt):articleExpiry(published||new Date());const {rows}=await q(`INSERT INTO news_articles(slug,source_kind,event_type,title,summary,body,spoiler,status,media_ids,created_by,scheduled_at,published_at,image_url,image_alt,source_name,language,facts,expires_at) VALUES($1,'EDITORIAL',$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'AniNexus','pt-BR',$14,$15) RETURNING id,slug,status`,[slug,d.eventType||null,d.title,d.summary,d.body||null,d.spoiler||false,d.status||'draft',JSON.stringify(d.mediaIds||[]),u.id,d.scheduledAt||null,published,d.imageUrl||null,d.imageAlt||null,JSON.stringify(d.facts||[]),expires]);await q('INSERT INTO audit_log(actor_id,action,target_type,target_id) VALUES($1,$2,$3,$4)',[u.id,'NEWS_CREATE','NEWS',rows[0].id]);return reply.code(201).send(rows[0]);});
app.patch('/api/admin/news/:id',writeRate,async(req,reply)=>{const u=await requireRole(req,reply,['moderator','admin']);if(!u)return;const id=String(req.params.id);if(!/^[0-9a-f-]{36}$/i.test(id))return reply.code(400).send({error:'INVALID_ID'});const p=articleSchema.partial().safeParse(req.body);if(!p.success||!Object.keys(p.data).length)return reply.code(400).send({error:'INVALID_INPUT'});const d=p.data;const {rows}=await q(`UPDATE news_articles SET title=COALESCE($2,title),summary=COALESCE($3,summary),body=COALESCE($4,body),event_type=COALESCE($5,event_type),spoiler=COALESCE($6,spoiler),status=COALESCE($7,status),media_ids=COALESCE($8::jsonb,media_ids),scheduled_at=COALESCE($9::timestamptz,scheduled_at),image_url=COALESCE($10,image_url),image_alt=COALESCE($11,image_alt),facts=COALESCE($12::jsonb,facts),expires_at=COALESCE($13::timestamptz,expires_at),published_at=CASE WHEN $7='published' AND published_at IS NULL THEN now() ELSE published_at END,updated_at=now() WHERE id=$1 RETURNING id,slug,status`,[id,d.title??null,d.summary??null,d.body??null,d.eventType??null,d.spoiler??null,d.status??null,d.mediaIds?JSON.stringify(d.mediaIds):null,d.scheduledAt??null,d.imageUrl??null,d.imageAlt??null,d.facts?JSON.stringify(d.facts):null,d.expiresAt??null]);if(!rows[0])return reply.code(404).send({error:'NOT_FOUND'});await q('INSERT INTO audit_log(actor_id,action,target_type,target_id) VALUES($1,$2,$3,$4)',[u.id,'NEWS_UPDATE','NEWS',id]);return rows[0];});

app.get('/api/admin/overview',privateHeavyRate,async(req,reply)=>{const actor=await requireRole(req,reply,['moderator','admin']);if(!actor)return;const [users,reports,content]=await Promise.all([q(`SELECT count(*)::int total,count(*) FILTER(WHERE status='active')::int active,count(*) FILTER(WHERE status='suspended')::int suspended,count(*) FILTER(WHERE status='banned')::int banned,count(*) FILTER(WHERE created_at>=now()-interval '7 days')::int new_week FROM users WHERE deleted_at IS NULL`),q(`SELECT count(*) FILTER(WHERE status='open')::int open,count(*) FILTER(WHERE status='reviewing')::int reviewing FROM content_reports`),q(`SELECT (SELECT count(*) FROM impressions WHERE hidden=false)::int impressions,(SELECT count(*) FROM community_threads WHERE hidden=false)::int threads,(SELECT count(*) FROM community_posts WHERE hidden=false)::int posts`)]);return{users:users.rows[0],reports:reports.rows[0],content:content.rows[0]}});
app.get('/api/admin/users',privateHeavyRate,async(req,reply)=>{const actor=await requireRole(req,reply,['moderator','admin']);if(!actor)return;const search=String(req.query?.search||'').trim().slice(0,120),status=['active','suspended','banned'].includes(String(req.query?.status||''))?String(req.query.status):null,limit=Math.max(1,Math.min(100,Number(req.query?.limit||40))),offset=Math.max(0,Math.min(10000,Number(req.query?.offset||0)));const pattern=search?`%${search.replace(/[%_]/g,'\\$&')}%`:null;const {rows}=await q(`SELECT u.id,u.email,u.username,u.display_name,u.avatar_url,u.role,u.status,u.suspended_until,u.ban_reason,u.moderation_note,u.email_verified,u.created_at,u.last_seen_at,(SELECT count(*)::int FROM user_anime ua WHERE ua.user_id=u.id) list_count,(SELECT count(*)::int FROM impressions i WHERE i.user_id=u.id AND i.hidden=false) impression_count FROM users u WHERE u.deleted_at IS NULL AND ($1::text IS NULL OR u.email::text ILIKE $1 ESCAPE '\\' OR u.username::text ILIKE $1 ESCAPE '\\' OR COALESCE(u.display_name,'') ILIKE $1 ESCAPE '\\') AND ($2::text IS NULL OR u.status=$2) ORDER BY u.created_at DESC LIMIT $3 OFFSET $4`,[pattern,status,limit,offset]);return{items:rows,hasMore:rows.length===limit}});
app.patch('/api/admin/users/:id',writeRate,async(req,reply)=>{const actor=await requireRole(req,reply,['moderator','admin']);if(!actor)return;const id=z.string().uuid().safeParse(req.params.id);if(!id.success)return reply.code(400).send({error:'INVALID_ID'});const p=z.object({role:z.enum(['user','moderator','admin']).optional(),status:z.enum(['active','suspended','banned']).optional(),suspendedUntil:z.string().datetime().nullable().optional(),banReason:nullableText(1000),moderationNote:nullableText(4000)}).safeParse(req.body);if(!p.success||!Object.keys(p.data).length)return reply.code(400).send({error:'INVALID_INPUT'});if(id.data===actor.id&&((p.data.status&&p.data.status!=='active')||(p.data.role&&p.data.role!=='admin')))return reply.code(400).send({error:'CANNOT_RESTRICT_SELF'});const {rows}=await q(`UPDATE users SET role=COALESCE($2,role),status=COALESCE($3,status),suspended_until=CASE WHEN $3='suspended' THEN $4::timestamptz WHEN $3 IS NOT NULL THEN NULL ELSE suspended_until END,ban_reason=CASE WHEN $3='banned' THEN $5 WHEN $3 IS NOT NULL THEN NULL ELSE COALESCE($5,ban_reason) END,moderation_note=COALESCE($6,moderation_note),session_version=CASE WHEN $3 IS NOT NULL OR $2 IS NOT NULL THEN session_version+1 ELSE session_version END,updated_at=now() WHERE id=$1 AND deleted_at IS NULL RETURNING id,email,username,display_name,role,status,suspended_until,ban_reason,moderation_note,session_version`,[id.data,p.data.role??null,p.data.status??null,p.data.suspendedUntil??null,p.data.banReason??null,p.data.moderationNote??null]);if(!rows[0])return reply.code(404).send({error:'NOT_FOUND'});await invalidateUserIdentityCache(id.data).catch(()=>{});await q('INSERT INTO audit_log(actor_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5)',[actor.id,'USER_MODERATION','USER',id.data,JSON.stringify({role:p.data.role,status:p.data.status})]);return{ok:true,user:rows[0]}});
app.delete('/api/admin/users/:id',writeRate,async(req,reply)=>{const actor=await requireRole(req,reply,['admin']);if(!actor)return;const id=z.string().uuid().safeParse(req.params.id);if(!id.success)return reply.code(400).send({error:'INVALID_ID'});if(id.data===actor.id)return reply.code(400).send({error:'CANNOT_DELETE_SELF'});const {rows}=await q(`UPDATE users SET deleted_at=now(),status='banned',session_version=session_version+1,updated_at=now() WHERE id=$1 AND deleted_at IS NULL RETURNING id,clerk_user_id`,[id.data]);if(!rows[0])return reply.code(404).send({error:'NOT_FOUND'});await invalidateUserIdentityCache(id.data).catch(()=>{});if(CLERK_ENABLED&&rows[0].clerk_user_id){try{await getClerkClient().users.deleteUser(rows[0].clerk_user_id)}catch(error){req.log.warn({err:error,userId:id.data},'admin clerk delete failed')}}await q('INSERT INTO audit_log(actor_id,action,target_type,target_id) VALUES($1,$2,$3,$4)',[actor.id,'USER_DELETE','USER',id.data]);return reply.code(204).send();});
app.get('/api/admin/reports',privateHeavyRate,async(req,reply)=>{const actor=await requireRole(req,reply,['moderator','admin']);if(!actor)return;const status=['open','reviewing','resolved','dismissed'].includes(String(req.query?.status||''))?String(req.query.status):null,limit=Math.max(1,Math.min(100,Number(req.query?.limit||50))),offset=Math.max(0,Math.min(10000,Number(req.query?.offset||0)));const {rows}=await q(`SELECT r.*,u.username reporter_username,u.display_name reporter_display_name,a.username assignee_username FROM content_reports r JOIN users u ON u.id=r.reporter_id LEFT JOIN users a ON a.id=r.assigned_to WHERE ($1::text IS NULL OR r.status=$1) ORDER BY CASE r.status WHEN 'open' THEN 0 WHEN 'reviewing' THEN 1 ELSE 2 END,r.created_at DESC LIMIT $2 OFFSET $3`,[status,limit,offset]);return{items:rows,hasMore:rows.length===limit}});
app.patch('/api/admin/reports/:id',writeRate,async(req,reply)=>{const actor=await requireRole(req,reply,['moderator','admin']);if(!actor)return;const id=z.string().uuid().safeParse(req.params.id),p=z.object({status:z.enum(['open','reviewing','resolved','dismissed']).optional(),resolution:nullableText(4000),assignedTo:z.string().uuid().nullable().optional()}).safeParse(req.body);if(!id.success||!p.success)return reply.code(400).send({error:'INVALID_INPUT'});const {rows}=await q(`UPDATE content_reports SET status=COALESCE($2,status),resolution=COALESCE($3,resolution),assigned_to=COALESCE($4::uuid,assigned_to),resolved_at=CASE WHEN $2 IN ('resolved','dismissed') THEN now() ELSE resolved_at END,updated_at=now() WHERE id=$1 RETURNING *`,[id.data,p.data.status??null,p.data.resolution??null,p.data.assignedTo??null]);if(!rows[0])return reply.code(404).send({error:'NOT_FOUND'});await q('INSERT INTO audit_log(actor_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5)',[actor.id,'REPORT_UPDATE','REPORT',id.data,JSON.stringify(p.data)]);return{ok:true,report:rows[0]}});
app.patch('/api/admin/content/:type/:id',writeRate,async(req,reply)=>{const actor=await requireRole(req,reply,['moderator','admin']);if(!actor)return;const type=String(req.params.type||'').toUpperCase(),id=String(req.params.id);const p=z.object({hidden:z.boolean()}).safeParse(req.body);if(!p.success||!['IMPRESSION','THREAD','POST','NEWS_COMMENT'].includes(type))return reply.code(400).send({error:'INVALID_INPUT'});const map={IMPRESSION:['impressions','id'],THREAD:['community_threads','id'],POST:['community_posts','id'],NEWS_COMMENT:['news_comments','id']},[table,column]=map[type];if(!/^[0-9a-f-]{36}$/i.test(id))return reply.code(400).send({error:'INVALID_ID'});await q(`UPDATE ${table} SET hidden=$2 WHERE ${column}=$1`,[id,p.data.hidden]);await q('INSERT INTO audit_log(actor_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5)',[actor.id,p.data.hidden?'CONTENT_HIDE':'CONTENT_RESTORE',type,id,JSON.stringify({hidden:p.data.hidden})]);return{ok:true}});
app.get('/api/admin/audit-log',privateHeavyRate,async(req,reply)=>{const actor=await requireRole(req,reply,['admin']);if(!actor)return;const limit=Math.max(1,Math.min(100,Number(req.query?.limit||50))),offset=Math.max(0,Math.min(10000,Number(req.query?.offset||0)));const {rows}=await q(`SELECT a.id,a.action,a.target_type,a.target_id,a.metadata,a.created_at,u.username actor_username,u.display_name actor_display_name FROM audit_log a LEFT JOIN users u ON u.id=a.actor_id ORDER BY a.created_at DESC LIMIT $1 OFFSET $2`,[limit,offset]);return{items:rows,hasMore:rows.length===limit}});
app.get('/api/admin/analytics',privateHeavyRate,async(req,reply)=>{const actor=await requireRole(req,reply,['admin']);if(!actor)return;return analyticsStats()});

app.get('/api/me/list',privateReadRate,async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const {rows}=await q('SELECT media_id,status,score,reaction,progress,updated_at FROM user_anime WHERE user_id=$1 ORDER BY updated_at DESC',[u.id]);return{items:rows}});
app.put('/api/me/list/:mediaId',writeRate,async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const mediaId=safeInt(req.params.mediaId);if(!mediaId)return reply.code(400).send({error:'INVALID_ID'});const p=z.object({status:z.enum(['PLANNING','CURRENT','COMPLETED','DROPPED','PAUSED']),score:z.number().int().min(1).max(10).nullable().optional(),reaction:z.enum(['love','like','neutral','dislike']).nullable().optional(),progress:z.number().int().min(0).max(10000).optional()}).safeParse(req.body);if(!p.success)return reply.code(400).send({error:'INVALID_INPUT'});const d=p.data;await q(`INSERT INTO user_anime(user_id,media_id,status,score,reaction,progress) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(user_id,media_id) DO UPDATE SET status=EXCLUDED.status,score=EXCLUDED.score,reaction=EXCLUDED.reaction,progress=EXCLUDED.progress,updated_at=now()`,[u.id,mediaId,d.status,d.score??null,d.reaction??null,d.progress||0]);let media=null;try{media=await getAnime(mediaId)}catch{}if(media)await q(`INSERT INTO media_cache(media_id,slug,payload,updated_at) VALUES($1,$2,$3,now()) ON CONFLICT(media_id) DO UPDATE SET slug=EXCLUDED.slug,payload=EXCLUDED.payload,updated_at=now()`,[mediaId,media.slug,JSON.stringify(media)]).catch(()=>{});return{ok:true}});
app.delete('/api/me/list/:mediaId',writeRate,async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const mediaId=safeInt(req.params.mediaId);if(!mediaId)return reply.code(400).send({error:'INVALID_ID'});await q('DELETE FROM user_anime WHERE user_id=$1 AND media_id=$2',[u.id,mediaId]);return reply.code(204).send();});
app.get('/api/me/favorites',privateReadRate,async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const {rows}=await q('SELECT media_id,created_at FROM user_favorites WHERE user_id=$1 ORDER BY created_at DESC',[u.id]);return{items:rows}});
app.put('/api/me/favorites/:mediaId',writeRate,async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const mediaId=safeInt(req.params.mediaId);if(!mediaId)return reply.code(400).send({error:'INVALID_ID'});await q('INSERT INTO user_favorites(user_id,media_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[u.id,mediaId]);return reply.code(204).send();});
app.delete('/api/me/favorites/:mediaId',writeRate,async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const mediaId=safeInt(req.params.mediaId);if(!mediaId)return reply.code(400).send({error:'INVALID_ID'});await q('DELETE FROM user_favorites WHERE user_id=$1 AND media_id=$2',[u.id,mediaId]);return reply.code(204).send();});
app.get('/api/me/notifications',privateReadRate,async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const limit=safeInt(req.query?.limit,1,50)||20;const {rows}=await q('SELECT id,kind,title,body,url AS href,read_at,created_at FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2',[u.id,limit]);return{items:rows}});
app.patch('/api/me/notifications/:id',writeRate,async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const id=z.string().uuid().safeParse(req.params.id);if(!id.success)return reply.code(400).send({error:'INVALID_ID'});await q('UPDATE notifications SET read_at=COALESCE(read_at,now()) WHERE id=$1 AND user_id=$2',[id.data,u.id]);return reply.code(204).send();});
app.post('/api/me/account/deletion',writeRate,async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const p=z.object({password:z.string().max(128).optional()}).safeParse(req.body||{});if(!p.success)return reply.code(400).send({error:'INVALID_INPUT'});if(!CLERK_ENABLED){if(!p.data.password)return reply.code(400).send({error:'PASSWORD_REQUIRED'});const {rows}=await q('SELECT password_hash FROM users WHERE id=$1',[u.id]);if(!await verifyPassword(rows[0]?.password_hash||'',p.data.password))return reply.code(401).send({error:'INVALID_CREDENTIALS'})}const ticket=await beginAccountDeletion(u,req);try{if(CLERK_ENABLED&&u.clerk_user_id)await getClerkClient().users.deleteUser(u.clerk_user_id);await transaction(async client=>{await client.query('DELETE FROM users WHERE id=$1',[u.id])});return reply.code(204).send()}catch(error){await cancelAccountDeletion(ticket).catch(()=>{});throw error}});

app.get('/api/anime/:id/impressions',publicRate,async(req,reply)=>{const id=safeInt(req.params.id);if(!id)return reply.code(400).send({error:'INVALID_ID'});const limit=Math.max(1,Math.min(100,Number(req.query?.limit||50)));const {rows}=await q(`SELECT i.id,i.body,i.spoiler,i.created_at,u.username,u.display_name,u.avatar_url FROM impressions i JOIN users u ON u.id=i.user_id WHERE i.media_id=$1 AND i.hidden=false AND u.deleted_at IS NULL AND u.status='active' AND u.privacy='public' ORDER BY i.created_at DESC LIMIT $2`,[id,limit]);return{items:rows}});
app.post('/api/anime/:id/impressions',rateForUser(8,'1 minute','impressions-write'),async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const id=safeInt(req.params.id);if(!id)return reply.code(400).send({error:'INVALID_ID'});const p=z.object({body:z.string().trim().min(1).max(1200),spoiler:z.boolean().optional()}).safeParse(req.body);if(!p.success)return reply.code(400).send({error:'INVALID_INPUT'});const {rows}=await q('INSERT INTO impressions(user_id,media_id,body,spoiler) VALUES($1,$2,$3,$4) RETURNING id,created_at',[u.id,id,p.data.body,p.data.spoiler||false]);return reply.code(201).send({ok:true,...rows[0]});});

app.get('/api/community/activity',publicRate,async(req)=>{const limit=Math.max(1,Math.min(60,Number(req.query?.limit||30)));const {rows}=await q(`SELECT ua.media_id,ua.status,ua.score,ua.reaction,ua.progress,ua.updated_at AS created_at,u.username,u.display_name,u.avatar_url,${mediaProjection} AS media FROM user_anime ua JOIN users u ON u.id=ua.user_id LEFT JOIN media_cache mc ON mc.media_id=ua.media_id WHERE u.deleted_at IS NULL AND u.status='active' AND u.privacy='public' AND ua.status IN ('PLANNING','CURRENT','COMPLETED','PAUSED','DROPPED') ORDER BY ua.updated_at DESC LIMIT $1`,[limit]);return{items:await hydrateCommunityMedia(rows)}});
app.get('/api/community/impressions',publicRate,async(req)=>{const limit=Math.max(1,Math.min(30,Number(req.query?.limit||12)));const {rows}=await q(`SELECT i.id,i.media_id,i.body,i.spoiler,i.created_at,u.username,u.display_name,u.avatar_url,ua.status,ua.score,ua.progress,${mediaProjection} AS media FROM impressions i JOIN users u ON u.id=i.user_id LEFT JOIN user_anime ua ON ua.user_id=i.user_id AND ua.media_id=i.media_id LEFT JOIN media_cache mc ON mc.media_id=i.media_id WHERE i.hidden=false AND u.deleted_at IS NULL AND u.status='active' AND u.privacy='public' ORDER BY i.created_at DESC LIMIT $1`,[limit]);return{items:await hydrateCommunityMedia(rows)}});
app.get('/api/community/threads',publicRate,async(req)=>{const limit=Math.max(1,Math.min(50,Number(req.query?.limit||30))),mediaId=req.query?.mediaId?safeInt(req.query.mediaId):null;const {rows}=await q(`SELECT t.id,t.media_id,t.title,t.body,t.spoiler,t.locked,t.created_at,u.username,u.display_name,u.avatar_url,(SELECT count(*)::int FROM community_posts p LEFT JOIN users pu ON pu.id=p.user_id WHERE p.thread_id=t.id AND p.hidden=false AND (p.user_id IS NULL OR (pu.deleted_at IS NULL AND pu.status='active' AND pu.privacy='public'))) replies FROM community_threads t LEFT JOIN users u ON u.id=t.user_id WHERE t.hidden=false AND (u.id IS NULL OR (u.deleted_at IS NULL AND u.status='active' AND u.privacy='public')) AND ($1::bigint IS NULL OR t.media_id=$1) ORDER BY t.created_at DESC LIMIT $2`,[mediaId,limit]);return{items:await hydrateCommunityMedia(rows)}});
app.get('/api/community/threads/:id',publicRate,async(req,reply)=>{const id=z.string().uuid().safeParse(req.params.id);if(!id.success)return reply.code(400).send({error:'INVALID_ID'});const [threadResult,postResult]=await Promise.all([q(`SELECT t.id,t.media_id,t.title,t.body,t.spoiler,t.locked,t.created_at,u.username,u.display_name,u.avatar_url FROM community_threads t LEFT JOIN users u ON u.id=t.user_id WHERE t.id=$1 AND t.hidden=false AND (u.id IS NULL OR (u.deleted_at IS NULL AND u.status='active' AND u.privacy='public'))`,[id.data]),q(`SELECT p.id,p.parent_id,p.body,p.spoiler,p.created_at,u.username,u.display_name,u.avatar_url FROM community_posts p LEFT JOIN users u ON u.id=p.user_id WHERE p.thread_id=$1 AND p.hidden=false AND (u.id IS NULL OR (u.deleted_at IS NULL AND u.status='active' AND u.privacy='public')) ORDER BY p.created_at ASC LIMIT 500`,[id.data])]);if(!threadResult.rows[0])return reply.code(404).send({error:'NOT_FOUND'});const [thread]=await hydrateCommunityMedia([threadResult.rows[0]]);return{thread,posts:postResult.rows}});
app.post('/api/community/threads',rateForUser(4,'10 minutes','threads-write'),async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const p=z.object({mediaId:z.number().int().positive().nullable().optional(),title:z.string().trim().min(3).max(180),body:z.string().trim().min(3).max(5000),spoiler:z.boolean().optional()}).safeParse(req.body);if(!p.success)return reply.code(400).send({error:'INVALID_INPUT'});const {rows}=await q('INSERT INTO community_threads(user_id,media_id,title,body,spoiler) VALUES($1,$2,$3,$4,$5) RETURNING id,created_at',[u.id,p.data.mediaId||null,p.data.title,p.data.body,p.data.spoiler||false]);return reply.code(201).send({ok:true,...rows[0]})});
app.post('/api/community/threads/:id/posts',rateForUser(10,'5 minutes','posts-write'),async(req,reply)=>{const u=await requireUser(req,reply);if(!u)return;const id=z.string().uuid().safeParse(req.params.id),p=z.object({parentId:z.string().uuid().nullable().optional(),body:z.string().trim().min(1).max(3000),spoiler:z.boolean().optional()}).safeParse(req.body);if(!id.success||!p.success)return reply.code(400).send({error:'INVALID_INPUT'});const {rows:threadRows}=await q('SELECT locked FROM community_threads WHERE id=$1 AND hidden=false',[id.data]);if(!threadRows[0])return reply.code(404).send({error:'NOT_FOUND'});if(threadRows[0].locked)return reply.code(423).send({error:'THREAD_LOCKED'});const {rows}=await q('INSERT INTO community_posts(thread_id,user_id,parent_id,body,spoiler) VALUES($1,$2,$3,$4,$5) RETURNING id,created_at',[id.data,u.id,p.data.parentId||null,p.data.body,p.data.spoiler||false]);return reply.code(201).send({ok:true,...rows[0]})});

app.post('/api/events',{config:{rateLimit:{max:60,timeWindow:'1 minute'}}},async(req,reply)=>{const event=String(req.body?.event||'').slice(0,50),pagePath=String(req.body?.path||'').slice(0,200),mediaId=req.body?.mediaId?safeInt(req.body.mediaId):null;if(!/^(page_view|search|media_open|list_update|favorite|login|register)$/.test(event)||!safePath(pagePath))return reply.code(400).send({error:'INVALID_EVENT'});const user=await currentUser(req).catch(()=>null);enqueueAnalytics({event,userId:user?.id,sessionHash:crypto.createHash('sha256').update(`${req.cookies?.anx_session||''}:${process.env.SESSION_SECRET||''}`).digest('hex').slice(0,32),path:pagePath,mediaId,referrer:String(req.headers.referer||'').slice(0,500),userAgent:String(req.headers['user-agent']||'').slice(0,500),ipHash:crypto.createHash('sha256').update(`${req.ip}:${process.env.SESSION_SECRET||''}`).digest('hex').slice(0,32)});return reply.code(202).send({ok:true})});

app.get('/*',async(req,reply)=>{if(req.url.startsWith('/api/')||req.url.startsWith('/health'))return reply.code(404).send({error:'NOT_FOUND'});return reply.sendFile('index.html')});

let shuttingDown=false;
const shutdown=async signal=>{if(shuttingDown)return;shuttingDown=true;app.log.info({signal},'shutdown started');const force=setTimeout(()=>process.exit(1),15_000);force.unref();try{await app.close();await flushAnalytics();await Promise.allSettled([redis.quit(),pool.end()]);clearTimeout(force);process.exit(0)}catch(error){app.log.error({err:error},'shutdown failed');process.exit(1)}};
process.on('SIGTERM',()=>shutdown('SIGTERM'));process.on('SIGINT',()=>shutdown('SIGINT'));
process.on('unhandledRejection',reason=>{app.log.error({err:reason},'unhandled rejection')});
process.on('uncaughtException',error=>{app.log.fatal({err:error},'uncaught exception');shutdown('uncaughtException')});

await initDb();
await initCache();
await bootstrapConfiguredAdmins();
await app.listen({port:Number(process.env.PORT||3000),host:'0.0.0.0'});
app.log.info({port:Number(process.env.PORT||3000),clerk:CLERK_ENABLED},'AniNexus ready');
prewarm().catch(e=>app.log.warn({err:e},'prewarm failed'));
