import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8'),exists=p=>fs.existsSync(path.join(root,p));let passed=0;
function test(name,fn){try{fn();passed++;console.log(`✓ ${name}`)}catch(err){console.error(`✗ ${name}\n  ${err.message}`);process.exitCode=1}}
const inc=(t,n)=>assert.ok(t.includes(n),`missing: ${n}`),not=(t,n)=>assert.ok(!t.includes(n),`unexpected: ${n}`);
const index=read('index.html'),actions=read('preview-v39/media-actions-v39.js'),actionsCss=read('preview-v39/media-actions-v39.css'),state=read('preview-v19/media-state-v2.js'),sync=read('preview-v39/media-sync-v39.js');
const activity=read('preview-v40/activity-v40.js'),community=read('preview-v40/community-v40.js'),communityCss=read('preview-v40/community-v40.css'),homeBridge=read('preview-v40/home-community-v40.js');
const schedule=read('preview-v18/schedule.js'),season=read('preview-v8/app.js'),legacy=read('preview-v6/app.js'),home=read('preview-v35/home-v35.js'),coreCss=read('preview-v38/core-v38.css'),library=read('preview-v38/library-v38.js'),router=read('preview-v23/router-v23.js'),nav=read('preview-v27/navigation-v27.js'),page404=read('404.html');
const server=read('server.mjs'),pkg=JSON.parse(read('package.json')),newsWorker=read('lib/news-worker-v37.mjs'),newsUpdater=read('scripts/update-news-v36.mjs'),newsWorkflow=read('.github/workflows/update-news.yml'),nativeNews=read('lib/native-news.mjs');
const auth=read('lib/auth.mjs'),frontendAuth=read('preview-v38/auth-v38.js'),cache=read('lib/cache.mjs'),compose=read('docker-compose.yml'),dockerfile=read('Dockerfile'),schema=read('sql/schema.sql'),securityMigration=read('sql/010_security_hardening.sql');
const clerkConfig=JSON.parse(read('ops/clerk/instance-config.json')),apiDeploy=read('ops/deploy-api-vps.sh'),tlsInstall=read('ops/install-ip-tls.sh'),tlsNginx=read('ops/nginx/aninexus.conf'),tlsBootstrap=read('ops/nginx/aninexus-bootstrap.conf'),deployWorkflow=read('.github/workflows/deploy-vps.yml'),pagesWorkflow=read('.github/workflows/deploy-pages.yml');
const staticValidator=read('scripts/validate-static-deploy.mjs');

test('V40 shell cache-busts the unified media controller',()=>{inc(index,'2026-08-25-v40.5.1');inc(index,'runtime-config.js?v=40.5.1');inc(index,'preview-v38/auth-v38.js?v=40.5.1');inc(index,'preview-v39/media-actions-v39.js?v=40.0.2');inc(index,'preview-v39/media-actions-v39.css?v=40.0.2');inc(index,'preview-v19/media-state-v2.js?v=40.0.4');inc(index,'preview-v39/media-sync-v39.js?v=40.3.0');assert.ok(index.indexOf('media-actions-v39.js')<index.indexOf('media-state-v2.js'));assert.ok(index.indexOf('media-state-v2.js')<index.indexOf('media-sync-v39.js'))});
test('all Pages route helpers use V40 and Community is dedicated',()=>{inc(router,"BUILD='40.0.0'");inc(router,"'/comunidade'");inc(nav,"BUILD='40.0.0'");inc(page404,'build=40.3.0')});
test('one window-capture controller exclusively owns every current action selector',()=>{['[data-fav]','[data-nx-fav]','[data-nx-detail-fav]','[data-nx18-fav]','[data-nx17-fav]','[data-list]','[data-nx-list]','[data-nx-detail-list]','[data-nx18-status]','[data-nx17-list]'].forEach(x=>inc(actions,x));inc(actions,"window.addEventListener('click'");inc(actions,'stopImmediatePropagation');inc(actions,'a.favorite(id,!a.isFavorite(id))');inc(actions,'a.open(id)');inc(actions,"b.dataset.nxActionOwner='global'");inc(actions,"button.dataset.nxActionKind=labeled?'labeled':'compact'");inc(actions,'favLock');inc(actions,'now()-last<340');inc(actions,'listOpening');inc(actions,"window.addEventListener('dblclick'");not(state,"document.addEventListener('click'")});
test('media modal hydrates without replacing controls or swallowing progress saves',()=>{inc(state,'const ownedLayer=layer');inc(state,"ownedLayer.addEventListener('pointerdown'");inc(state,"ownedLayer.addEventListener('keydown'");inc(state,'input.oninput=updateProgress');inc(state,'input.onchange=updateProgress');inc(state,'void media(n).then');inc(state,'if(!fresh||layer!==ownedLayer)return');inc(state,'if(editing)return');inc(state,'Interaction is intentionally NOT bound here')});
test('legacy routes may render buttons but cannot be the interaction owner',()=>{inc(schedule,'data-nx18-status');inc(schedule,'data-nx18-fav');inc(season,'data-nx-list');inc(season,'data-nx-fav');inc(legacy,'data-list');inc(legacy,'data-fav');inc(actions,'b.onclick=null');inc(actions,'stop(e)')});
test('card actions have one 34px circular translucent geometry including Meus Animes',()=>{inc(actionsCss,'--nx39-action-size:34px');inc(actionsCss,'button[data-nx-action-kind="compact"]');inc(actionsCss,'border-radius:50%');inc(actionsCss,'rgba(8,6,9,.82)');inc(actionsCss,'width:17px!important');inc(actionsCss,'right:7px!important');inc(actionsCss,'bottom:7px!important');inc(actionsCss,'.nx38-library-card-actions');inc(library,'nx38-library-card-actions')});
test('media state remains mutually-exclusive while favorite stays independent',()=>{['PLANNING','CURRENT','COMPLETED','PAUSED','DROPPED'].forEach(x=>inc(state,`${x}:`));inc(state,"const FAV_KEY='aninexus:favorites'");inc(state,"document.dispatchEvent(new CustomEvent('aninexus:media-state-changed'");inc(state,"document.dispatchEvent(new CustomEvent('aninexus:favorite-changed'")});
test('server synchronization coalesces rapid writes so last intent wins',()=>{inc(sync,'favDesired=new Map()');inc(sync,'stateDesired=new Map()');inc(sync,'while(favDesired.has(id))');inc(sync,'while(stateDesired.has(id))')});

test('status changes are persisted as reusable Community activity history',()=>{inc(activity,"const KEY='aninexus:community:activity:v40'");inc(activity,"document.addEventListener('aninexus:media-state-changed'");inc(activity,'status:String(state.status)');inc(activity,'progress:Math.max');inc(activity,'score:state.score');inc(activity,'reaction:String');inc(activity,"dispatchEvent(new CustomEvent('aninexus:community-activity-changed'");inc(activity,'window.AniNexusCommunityActivity')});
test('Community V40 replaces static rooms with activity impressions and discussions',()=>{inc(community,"const BUILD='40.0.0'");['Tudo','Atividade','Impressões','Discussões'].forEach(x=>inc(community,x));inc(community,"/api/community/activity?limit=40");inc(community,"/api/community/impressions?limit=24");inc(community,"/api/community/threads?limit=30");inc(community,'localActivity()');inc(community,'localThreads()');inc(community,'nx40-community');inc(community,'Nova discussão');not(community,'O que você está assistindo hoje?')});
test('Community visual system is responsive and mirrors activity-centered ANIQuim density',()=>{inc(communityCss,'.nx40-card');inc(communityCss,'.nx40-stats');inc(communityCss,'.nx40-trending');inc(communityCss,'@media(max-width:620px)');inc(communityCss,'html.nx40-community-boot #app')});
test('Home Agora na Comunidade consumes the same activity stream',()=>{inc(homeBridge,'AniNexusCommunityActivity?.local');inc(homeBridge,"/api/community/activity?limit=12");inc(homeBridge,"/api/community/impressions?limit=8");inc(homeBridge,"/api/community/threads?limit=8");inc(homeBridge,"#nx35CommunityHero");inc(homeBridge,"#nx35Community");inc(homeBridge,"aninexus:community-activity-changed")});
test('V40 bootstrap shields malformed old Community URLs and prevents V6 ownership',()=>{inc(actions,"raw.split('?')[0]");inc(actions,"routeFrom()==='/comunidade'");inc(actions,"nx40-community-boot");inc(actions,"loadScript('preview-v40/activity-v40.js')");inc(actions,"loadScript('preview-v40/home-community-v40.js')");inc(actions,"loadScript('preview-v40/community-v40.js')");inc(actions,'location.assign(communityUrl())')});

test('existing server Community primitives stay available',()=>{inc(server,"app.get('/api/community/impressions'");inc(server,"app.get('/api/community/threads'");inc(server,"app.post('/api/community/threads'");inc(server,"app.get('/api/me/list'");inc(server,"app.put('/api/me/list/:mediaId'")});
test('private APIs authenticate before applying genuine per-user limits',()=>{inc(server,"hook:'preHandler'");inc(server,'preValidation:authenticateForRate');inc(server,'request.aninexusUser?.id');inc(server,"rateForUser(120,'1 minute','private-read')");inc(server,"rateForUser(20,'1 minute','private-heavy')");inc(server,"app.get('/api/me',privateReadRate");inc(server,"app.get('/api/me/library',privateHeavyRate");inc(server,"app.get('/api/me/export',privateHeavyRate");inc(auth,'const requestUsers = new WeakMap()')});
test('production auth and cache fail closed',()=>{inc(auth,'Math.max(19_456');inc(auth,'Legacy authentication is development-only');inc(compose,'COOKIE_SECURE: ${COOKIE_SECURE:-true}');inc(compose,'REDIS_PASSWORD: ${REDIS_PASSWORD:?');inc(cache,'password.length < 24');inc(cache,'password: password || undefined')});
test('account deletion uses deleted_at as a short fail-closed transition',()=>{inc(auth,'beginAccountDeletion');inc(auth,'cancelAccountDeletion');inc(server,'await beginAccountDeletion(user)');inc(server,'u.deleted_at IS NULL');inc(server,'await cancelAccountDeletion(user)')});
test('soft-deleted identities disappear from every public community surface',()=>{inc(server,"p.user_id IS NULL OR (pu.deleted_at IS NULL AND pu.privacy='public')");inc(server,"u.id IS NULL OR (u.deleted_at IS NULL AND u.privacy='public')")});
test('notification URLs are bounded in fresh and upgraded databases',()=>{inc(schema,'url text CHECK (url IS NULL OR char_length(url) <= 1200)');inc(securityMigration,'notifications_url_length');inc(securityMigration,'VALIDATE CONSTRAINT')});
test('obsolete news generations are removed',()=>{['lib/news-worker.mjs','lib/news-worker-v33.mjs','lib/news-worker-v34.mjs','lib/news-sources-v35.mjs','scripts/update-news.mjs','scripts/update-news-v34.mjs','scripts/update-news-v35.mjs'].forEach(p=>assert.ok(!exists(p),`obsolete file still exists: ${p}`))});
test('active HTML escape maps keep complete quote entities',()=>{not(homeBridge,'&quot\"');inc(homeBridge,"'&quot;'")});
test('Clerk policy exposes GitHub without unnecessary required identifiers',()=>{assert.equal(clerkConfig.connection_oauth_github.enabled,true);assert.equal(clerkConfig.auth_phone.required_for_sign_up,false);assert.equal(clerkConfig.auth_username.required_for_sign_up,false);assert.equal(clerkConfig.auth_password.required,false);assert.equal(clerkConfig.auth_multi_factor.authenticator_app.enabled,true)});
test('Clerk browser loader includes the current UI bundle contract',()=>{inc(frontendAuth,'@clerk/ui@1/dist/ui.browser.js');inc(frontendAuth,'window.__internal_ClerkUICtor');inc(frontendAuth,'ui: { ClerkUI: window.__internal_ClerkUICtor }')});
test('Home actions are accessible before their global controller hydrates',()=>{inc(home,'aria-label="${st?\'Alterar status de\':\'Adicionar à lista:\'} ${esc(t)}"');inc(home,'aria-label="${fav?\'Remover dos favoritos:\':\'Favoritar:\'} ${esc(t)}"');inc(coreCss,'html[data-theme="light"] .nx38-impressions-kicker{color:#941d3d}')});
test('production containers start Node without runtime package-manager downloads',()=>{inc(dockerfile,'CMD ["node","server.mjs"]');inc(compose,'command: ["node","lib/news-worker-v37.mjs"]');not(dockerfile,'CMD ["pnpm","start"]');not(compose,'command: ["pnpm","run","worker:news"]')});
test('API deploy is isolated, locked, health-checked and rejects archive links',()=>{inc(apiDeploy,"readonly HEALTH_URL='http://127.0.0.1:18080/health/ready'");inc(apiDeploy,"flock -w 300");inc(apiDeploy,'member.issym()');inc(apiDeploy,'member.islnk()');inc(apiDeploy,'A API nova falhou; restaurando a anterior.');inc(apiDeploy,'index=5')});
test('IP TLS deploy bootstraps ACME then serves API only through HTTPS',()=>{inc(tlsBootstrap,'/.well-known/acme-challenge/');inc(tlsInstall,'--preferred-profile shortlived');inc(tlsInstall,'aninexus-ip-staging');inc(tlsNginx,'listen 443 ssl');inc(tlsNginx,'proxy_pass http://aninexus_api');inc(tlsNginx,'return 308 https://$host$request_uri');inc(tlsNginx,'location = /runtime-config.js');inc(tlsNginx,'no-store, max-age=0');inc(deployWorkflow,"https://{0}")});
test('GitHub Pages builds the same authenticated shell without embedding secrets',()=>{inc(pagesWorkflow,'actions/deploy-pages@v4');inc(pagesWorkflow,'PUBLIC_BASE_PATH: /AniNexus/');inc(pagesWorkflow,'vars.PUBLIC_CLERK_PUBLISHABLE_KEY');inc(pagesWorkflow,'permissions:');inc(pagesWorkflow,'pages: write');not(pagesWorkflow,'CLERK_SECRET_KEY')});
test('static validation understands both root and GitHub Pages base paths',()=>{inc(staticValidator,"process.env.PUBLIC_BASE_PATH||'/'");inc(staticValidator,'<base href="${expectedBase}">');inc(staticValidator,'PUBLIC_BASE_PATH inválido')});
test('news resilience fixes remain intact',()=>{inc(newsUpdater,'NEWS_STALE_GRACE_DAYS');inc(nativeNews,'STALE_GRACE_DAYS');inc(newsWorker,'cleanup({archive:hasHealthyContent})');inc(newsWorkflow,"cron: '7,22,37,52 * * * *'")});
test('package check syntax-validates all V40 modules',()=>{['preview-v40/activity-v40.js','preview-v40/community-v40.js','preview-v40/home-community-v40.js','preview-v39/media-actions-v39.js','preview-v39/media-sync-v39.js'].forEach(x=>inc(pkg.scripts.check,x))});
test('critical V40 files exist',()=>['preview-v40/activity-v40.js','preview-v40/community-v40.js','preview-v40/community-v40.css','preview-v40/home-community-v40.js'].forEach(p=>assert.ok(exists(p),`missing ${p}`)));
if(process.exitCode)throw new Error('AniNexus core V40 tests failed');console.log(`\nAniNexus Core V40: ${passed} tests passed`);
