import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8'),exists=p=>fs.existsSync(path.join(root,p));let passed=0;
function test(name,fn){try{fn();passed++;console.log(`✓ ${name}`)}catch(err){console.error(`✗ ${name}\n  ${err.message}`);process.exitCode=1}}
const inc=(t,n)=>assert.ok(t.includes(n),`missing: ${n}`),not=(t,n)=>assert.ok(!t.includes(n),`unexpected: ${n}`);
const index=read('index.html'),actions=read('preview-v39/media-actions-v39.js'),actionsCss=read('preview-v39/media-actions-v39.css'),state=read('preview-v19/media-state-v2.js'),sync=read('preview-v39/media-sync-v39.js');
const activity=read('preview-v40/activity-v40.js'),community=read('preview-v40/community-v40.js'),communityCss=read('preview-v40/community-v40.css'),homeBridge=read('preview-v40/home-community-v40.js');
const schedule=read('preview-v18/schedule.js'),season=read('preview-v8/app.js'),legacy=read('preview-v6/app.js'),library=read('preview-v38/library-v38.js'),router=read('preview-v23/router-v23.js'),nav=read('preview-v27/navigation-v27.js'),page404=read('404.html');
const server=read('server.mjs'),pkg=JSON.parse(read('package.json')),newsWorker=read('lib/news-worker-v37.mjs'),newsUpdater=read('scripts/update-news-v36.mjs'),newsWorkflow=read('.github/workflows/update-news.yml'),nativeNews=read('lib/native-news.mjs');

test('V40 shell cache-busts the unified media controller',()=>{inc(index,'2026-08-23-v40.0.0');inc(index,'preview-v39/media-actions-v39.js?v=40.0.2');inc(index,'preview-v39/media-actions-v39.css?v=40.0.2');inc(index,'preview-v19/media-state-v2.js?v=40.0.0');inc(index,'preview-v39/media-sync-v39.js?v=40.0.0');assert.ok(index.indexOf('media-actions-v39.js')<index.indexOf('media-state-v2.js'));assert.ok(index.indexOf('media-state-v2.js')<index.indexOf('media-sync-v39.js'))});
test('all Pages route helpers use V40 and Community is dedicated',()=>{inc(router,"BUILD='40.0.0'");inc(router,"'/comunidade'");inc(nav,"BUILD='40.0.0'");inc(page404,'build=40.0.0')});
test('one window-capture controller exclusively owns every current action selector',()=>{['[data-fav]','[data-nx-fav]','[data-nx-detail-fav]','[data-nx18-fav]','[data-nx17-fav]','[data-list]','[data-nx-list]','[data-nx-detail-list]','[data-nx18-status]','[data-nx17-list]'].forEach(x=>inc(actions,x));inc(actions,"window.addEventListener('click'");inc(actions,'stopImmediatePropagation');inc(actions,'a.favorite(id,!a.isFavorite(id))');inc(actions,'a.open(id)');inc(actions,"b.dataset.nxActionOwner='global'");inc(actions,"button.dataset.nxActionKind=labeled?'labeled':'compact'");inc(actions,'favLock');inc(actions,'now()-last<340');inc(actions,'listOpening');inc(actions,"window.addEventListener('dblclick'")});
test('legacy routes may render buttons but cannot be the interaction owner',()=>{inc(schedule,'data-nx18-status');inc(schedule,'data-nx18-fav');inc(season,'data-nx-list');inc(season,'data-nx-fav');inc(legacy,'data-list');inc(legacy,'data-fav');inc(actions,'b.onclick=null');inc(actions,'stop(e)')});
test('card actions have one 34px circular translucent geometry including Meus Animes',()=>{inc(actionsCss,'--nx39-action-size:34px');inc(actionsCss,'button[data-nx-action-kind="compact"]');inc(actionsCss,'border-radius:50%');inc(actionsCss,'rgba(8,6,9,.82)');inc(actionsCss,'width:17px!important');inc(actionsCss,'right:7px!important');inc(actionsCss,'bottom:7px!important');inc(actionsCss,'.nx38-library-card-actions');inc(library,'nx38-library-card-actions')});
test('media state remains mutually-exclusive while favorite stays independent',()=>{['PLANNING','CURRENT','COMPLETED','PAUSED','DROPPED'].forEach(x=>inc(state,`${x}:`));inc(state,"const FAV_KEY='aninexus:favorites'");inc(state,"document.dispatchEvent(new CustomEvent('aninexus:media-state-changed'");inc(state,"document.dispatchEvent(new CustomEvent('aninexus:favorite-changed'")});
test('server synchronization coalesces rapid writes so last intent wins',()=>{inc(sync,'favDesired=new Map()');inc(sync,'stateDesired=new Map()');inc(sync,'while(favDesired.has(id))');inc(sync,'while(stateDesired.has(id))')});

test('status changes are persisted as reusable Community activity history',()=>{inc(activity,"const KEY='aninexus:community:activity:v40'");inc(activity,"document.addEventListener('aninexus:media-state-changed'");inc(activity,'status:String(state.status)');inc(activity,'progress:Math.max');inc(activity,'score:state.score');inc(activity,'reaction:String');inc(activity,"dispatchEvent(new CustomEvent('aninexus:community-activity-changed'");inc(activity,'window.AniNexusCommunityActivity')});
test('Community V40 replaces static rooms with activity impressions and discussions',()=>{inc(community,"const BUILD='40.0.0'");['Tudo','Atividade','Impressões','Discussões'].forEach(x=>inc(community,x));inc(community,"/api/community/activity?limit=40");inc(community,"/api/community/impressions?limit=24");inc(community,"/api/community/threads?limit=30");inc(community,'localActivity()');inc(community,'localThreads()');inc(community,'nx40-community');inc(community,'Nova discussão');not(community,'O que você está assistindo hoje?')});
test('Community visual system is responsive and mirrors activity-centered ANIQuim density',()=>{inc(communityCss,'.nx40-card');inc(communityCss,'.nx40-stats');inc(communityCss,'.nx40-trending');inc(communityCss,'@media(max-width:620px)');inc(communityCss,'html.nx40-community-boot #app')});
test('Home Agora na Comunidade consumes the same activity stream',()=>{inc(homeBridge,'AniNexusCommunityActivity?.local');inc(homeBridge,"/api/community/activity?limit=12");inc(homeBridge,"/api/community/impressions?limit=8");inc(homeBridge,"/api/community/threads?limit=8");inc(homeBridge,"#nx35CommunityHero");inc(homeBridge,"#nx35Community");inc(homeBridge,"aninexus:community-activity-changed")});
test('V40 bootstrap shields malformed old Community URLs and prevents V6 ownership',()=>{inc(actions,"raw.split('?')[0]");inc(actions,"routeFrom()==='/comunidade'");inc(actions,"nx40-community-boot");inc(actions,"loadScript('preview-v40/activity-v40.js')");inc(actions,"loadScript('preview-v40/home-community-v40.js')");inc(actions,"loadScript('preview-v40/community-v40.js')");inc(actions,'location.assign(communityUrl())')});

test('existing server Community primitives stay available',()=>{inc(server,"app.get('/api/community/impressions'");inc(server,"app.get('/api/community/threads'");inc(server,"app.post('/api/community/threads'");inc(server,"app.get('/api/me/list'");inc(server,"app.put('/api/me/list/:mediaId'")});
test('news resilience fixes remain intact',()=>{inc(newsUpdater,'NEWS_STALE_GRACE_DAYS');inc(nativeNews,'STALE_GRACE_DAYS');inc(newsWorker,'cleanup({archive:hasHealthyContent})');inc(newsWorkflow,"cron: '7,22,37,52 * * * *'")});
test('package check syntax-validates all V40 modules',()=>{['preview-v40/activity-v40.js','preview-v40/community-v40.js','preview-v40/home-community-v40.js','preview-v39/media-actions-v39.js','preview-v39/media-sync-v39.js'].forEach(x=>inc(pkg.scripts.check,x))});
test('critical V40 files exist',()=>['preview-v40/activity-v40.js','preview-v40/community-v40.js','preview-v40/community-v40.css','preview-v40/home-community-v40.js'].forEach(p=>assert.ok(exists(p),`missing ${p}`)));
if(process.exitCode)throw new Error('AniNexus core V40 tests failed');console.log(`\nAniNexus Core V40: ${passed} tests passed`);
