import {test,expect} from '@playwright/test';
const ORIGIN=process.env.ANINEXUS_E2E_ORIGIN||'http://qgbaltigo.github.io:4173/AniNexus/';
const LOCAL_STATIC_ORIGIN=process.env.ANINEXUS_LOCAL_STATIC_ORIGIN||'';
const pageUrl=route=>`${ORIGIN}?build=42.1.5&p=${encodeURIComponent(route)}`;
const firstVisitUrl=route=>{const url=new URL(pageUrl(route));if(url.hostname.endsWith('github.io'))url.hostname='127.0.0.1';return url.href};
async function fulfillLocalStatic(route){const requested=new URL(route.request().url()),local=new URL(requested.pathname+requested.search,LOCAL_STATIC_ORIGIN);let lastError;for(let attempt=0;attempt<3;attempt++){try{const response=await route.fetch({url:local.href});return await route.fulfill({response})}catch(error){lastError=error;if(!/ECONNRESET|socket hang up/i.test(String(error?.message))||attempt===2)throw error;await new Promise(resolve=>setTimeout(resolve,50*(attempt+1)))}}throw lastError}
async function noOverflow(page,t=7){const x=await page.evaluate(()=>({s:document.documentElement.scrollWidth,w:innerWidth}));expect(x.s).toBeLessThanOrEqual(x.w+t)}
async function clear(page){await page.evaluate(()=>{for(const k of ['aninexus:favorites','aninexus:mediaState:v2','aninexus:mediaState:v1','aninexus:list','aninexus:listStatus','aninexus:community:activity:v40','aninexus:community:threads:v40'])localStorage.removeItem(k);window.AniNexusMediaState?.sync?.()})}
const pixel='data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';
function anime(id=101){return{id,title:{romaji:`Anime Teste ${id}`,english:`Anime Teste ${id}`,native:`Teste ${id}`,userPreferred:`Anime Teste ${id}`},coverImage:{extraLarge:pixel,large:pixel},bannerImage:pixel,averageScore:82,popularity:1000,genres:['Action','Adventure'],episodes:12,format:'TV',status:'RELEASING',seasonYear:2026,description:'Uma história de teste.',externalLinks:[],startDate:{year:2026,month:1,day:1},endDate:null,studios:{nodes:[]},relations:{edges:[]},recommendations:{nodes:[]},characters:{edges:[]},staff:{edges:[]}}}
function graphData(query='',variables={}){
  const ids=Array.isArray(variables.ids)&&variables.ids.length?variables.ids:[101,102,103,104],media=ids.map(Number).filter(Boolean).map(anime),airingAt=Number(variables.start)||Math.floor(Date.now()/1000)+3600;
  const Page={pageInfo:{total:media.length,currentPage:1,lastPage:1,hasNextPage:false},media,airingSchedules:media.map((item,i)=>({airingAt:airingAt+3600*(i+1),episode:i+1,media:item}))};
  if(/studios\s*\(\s*sort\s*:/.test(query))return{Page:{...Page,studios:[{id:1,name:'Estúdio Teste',isAnimationStudio:true,favourites:1000,media:{nodes:media}}]}};
  if(/\bseason:Page/.test(query))return{season:Page,schedule:Page,top:Page,popular:Page,soon:Page,reading:Page};
  const aliases=[...query.matchAll(/\b(a\d+):Media/g)].map(x=>x[1]);if(aliases.length)return Object.fromEntries(aliases.map((key,i)=>[key,anime(201+i)]));
  if(/\bMedia\s*\(\s*id\s*:\s*\$id/.test(query))return{Media:anime(Number(variables.id)||101)};
  if(/\bMedia\s*\(/.test(query)&&!/\bmedia\s*\(/.test(query))return{Media:anime(Number(variables.id)||101)};
  return{Page};
}
function themeApiData(count=24){return{anime:[{slug:'anime-teste-101',animethemes:Array.from({length:count},(_,index)=>({type:index%3===2?'ED':'OP',sequence:index+1,song:{title:`Tema ${index+1}`,artists:[{name:`Artista ${index+1}`}]},animethemeentries:[{episodes:String(index+1),nsfw:false,spoiler:false,videos:[{link:`https://v.animethemes.moe/test-${index+1}.webm`,mimetype:'video/webm',resolution:1080,nc:true,subbed:false,lyrics:false}]}]}))}]}}
test.describe.configure({mode:'serial'});
test.beforeEach(async({page})=>{if(LOCAL_STATIC_ORIGIN){const publicOrigin=new URL(ORIGIN).origin;await page.route(`${publicOrigin}/**`,fulfillLocalStatic)}await page.route('https://graphql.anilist.co/',async route=>{let body={};try{body=route.request().postDataJSON()||{}}catch{}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:graphData(body.query,body.variables)})})});await page.route('https://api.jikan.moe/**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:null})}))});

test('V42 Home is the current renderer',async({page})=>{await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx35-home')).toBeVisible({timeout:30000});await expect(page.locator('.aqx-home')).toHaveCount(0);await expect(page.locator('.nx35-kicker,.nx35-signals')).toHaveCount(0);await expect(page.locator('meta[name="aninexus-build"]')).toHaveAttribute('content','2026-09-01-v42.1.5')});

test('Home theme is complete and empty achievements do not consume space',async({page})=>{await page.addInitScript(()=>localStorage.setItem('aninexus:theme','dark'));await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx35-home')).toBeVisible({timeout:30000});await expect(page.locator('.nx35-achievement-section')).toBeHidden();await page.locator('[data-action="theme"]').click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');await expect(page.locator('body')).toHaveCSS('background-color','rgb(246, 243, 244)');await expect(page.locator('.nx35-hero h1')).toHaveCSS('color','rgb(36, 24, 30)');await noOverflow(page,2)});

test('production Home falls back when its API returns empty successful payloads',async({page})=>{test.skip(new URL(ORIGIN).hostname.endsWith('github.io'),'This regression requires the production fetch bridge.');const origin=new URL(ORIGIN).origin;await page.route(`${origin}/api/home**`,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({season:[],schedule:[],top:[],popular:[],reading:[],soon:[]})}));await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});await expect(page.locator('#nx35Season .nx35-anime').first()).toBeVisible({timeout:30000});await expect(page.locator('#nx35Top .nx35-rank').first()).toBeVisible();await expect(page.locator('#nx35Popular .nx35-anime').first()).toBeVisible();await expect(page.locator('.nx35-data-empty')).toHaveCount(0)});

test('production schedule renders normalized VPS titles covers and scores on mobile',async({page})=>{test.skip(new URL(ORIGIN).hostname.endsWith('github.io'),'This regression requires the production API path.');await page.setViewportSize({width:390,height:844});const origin=new URL(ORIGIN).origin,now=Math.floor(Date.now()/1000)+3600,normalized={id:901,title:'Título Normalizado da VPS',titleRomaji:'VPS Normalized Title',cover:pixel,score:8.7,genres:['Action'],episodes:12,format:'TV',seasonYear:2026,streaming:[]};await page.route(`${origin}/api/schedule**`,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify([{airingAt:now,episode:4,media:normalized}])}));await page.goto(pageUrl('/animes/programacao'),{waitUntil:'domcontentloaded'});const card=page.locator('.nx18-card').first();await expect(card).toBeVisible({timeout:30000});await expect(card.locator('h3')).toHaveText('Título Normalizado da VPS');await expect(card.locator('.nx18-cover img')).toHaveAttribute('src',pixel);await expect(card.locator('.nx18-score')).toContainText('8.7');await noOverflow(page,2)});

test('mobile header always exposes account access while anonymous',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});await expect(page.locator('.top-actions>[data-action="login"]')).toBeVisible({timeout:15000});await expect(page.locator('.top-actions>[data-action="register"]')).toBeHidden();await expect(page.locator('.menu-btn')).toBeVisible();await noOverflow(page,2)});

test('mobile drawer exposes light dark and automatic appearance modes above first-visit consent',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto(firstVisitUrl('/'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx42-consent')).toBeVisible();await page.locator('[data-action="drawer-open"]').click();const theme=page.locator('.nx42-theme-card');await expect(theme).toBeVisible();for(const label of ['Claro','Escuro','Automático'])await expect(theme.getByRole('button',{name:label})).toBeVisible();await theme.getByRole('button',{name:'Claro'}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');await theme.getByRole('button',{name:'Escuro'}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await noOverflow(page,2)});

test('Home keeps anime and manga rankings separate and navigable',async({page})=>{await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});const animeRank=page.locator('#nx35Top .nx35-rank'),mangaRank=page.locator('#nx42TopManga [data-nx42-type="manga"]');await expect(animeRank.first()).toBeVisible({timeout:30000});await expect(mangaRank.first()).toBeVisible({timeout:30000});expect(await animeRank.count()).toBeGreaterThan(0);expect(await mangaRank.count()).toBeGreaterThan(0);await expect(page.locator('#nx35Top [data-nx42-type="manga"]')).toHaveCount(0);await expect(page.locator('#nx42TopManga [data-open-anime]')).toHaveCount(0)});

test('Home ranking clicks are not swallowed by horizontal drag support',async({page})=>{await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});await expect(page.locator('#nx35Top .nx35-rank h3').first()).toBeVisible({timeout:30000});await page.locator('#nx35Top .nx35-rank h3').first().click();await page.waitForURL(url=>url.searchParams.get('p')?.startsWith('/anime/')||url.pathname.startsWith('/anime/'),{timeout:10000});await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});const manga=page.locator('#nx42TopManga a[data-nx42-type="manga"]').first();await expect(manga).toBeVisible({timeout:30000});await expect(manga).toHaveAttribute('data-nx23-dedicated',/\/manga\/.+-\d+/);await manga.locator('h3').click();await page.waitForURL(url=>url.searchParams.get('p')?.startsWith('/manga/')||url.pathname.startsWith('/manga/'),{timeout:10000})});

test('Awards uses a compact editorial grid without dead desktop regions',async({page})=>{await page.setViewportSize({width:1440,height:900});await page.goto(pageUrl('/anime-awards'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx42-awards-page')).toBeVisible({timeout:30000});await expect(page.getByRole('heading',{name:'Os destaques de cada ano'})).toBeVisible();const cards=page.locator('.nx42-award-winner');await expect(cards.first()).toBeVisible();expect(await cards.count()).toBeGreaterThanOrEqual(4);const boxes=await cards.evaluateAll(nodes=>nodes.slice(0,6).map(node=>node.getBoundingClientRect()));expect(Math.max(...boxes.map(box=>box.height))).toBeLessThan(430);expect(new Set(boxes.slice(0,3).map(box=>Math.round(box.y))).size).toBe(1);await noOverflow(page,2)});

test('production detail paints from the internal API without waiting for external providers',async({page})=>{const origin=new URL(firstVisitUrl('/')).origin,base=anime(101),normalized={id:base.id,idMal:null,mediaType:'ANIME',title:base.title.english,titleRomaji:base.title.romaji,titleNative:base.title.native,synonyms:[],cover:pixel,coverColor:'#ef2a5c',banner:pixel,description:base.description,genres:base.genres,tags:['Action'],tagDetails:[{name:'Action',rank:90,isMediaSpoiler:false}],score:8.2,meanScore:8.1,popularity:1000,favourites:100,episodes:12,duration:24,format:'TV',status:'RELEASING',season:'SUMMER',seasonYear:2026,country:'JP',source:'ORIGINAL',startDate:base.startDate,endDate:null,studios:[],streaming:[],nextAiringEpisode:null,trailer:null,characters:[],staff:[],relations:[],recommendations:[]};let apiHits=0;await page.route(`${origin}/preview-v22/**`,async route=>{const requested=new URL(route.request().url()),response=await route.fetch({url:`${origin}/AniNexus${requested.pathname}${requested.search}`});await route.fulfill({response})});await page.route(`${origin}/api/anime/101`,async route=>{apiHits++;await new Promise(resolve=>setTimeout(resolve,80));await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(normalized)})});await page.unroute('https://graphql.anilist.co/');await page.route('https://graphql.anilist.co/',route=>route.abort('failed'));const started=Date.now();await page.goto(firstVisitUrl('/anime/anime-teste-101'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx22-detail:not(.nx22-loading):not(.nx22-fail)')).toBeVisible({timeout:3000});await expect(page.getByRole('heading',{name:'Anime Teste 101'})).toBeVisible();expect(Date.now()-started).toBeLessThan(3000);expect(apiHits).toBe(1);await noOverflow(page,2)});

test('native news slugs with underscores open the reader',async({page})=>{const slug='life-a-felicidade-depende-de-nos-sera-publicado-pela-newpop-jbox_manga-211a006a',origin=new URL(firstVisitUrl('/')).origin;await page.route(`${origin}/api/news/${slug}`,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({id:'211a006a',slug,title:'Life, A Felicidade Depende de Nós será publicado pela NewPOP',summary:'A editora confirmou a publicação brasileira do mangá.',event_type:'MANGA',source_name:'AniNexus Notícias',language:'pt-BR',published_at:new Date().toISOString(),facts:['A publicação foi confirmada.'],body:{sections:[{heading:'Publicação no Brasil',paragraphs:['A edição brasileira foi anunciada oficialmente.']}]}})}));await page.goto(firstVisitUrl(`/noticias/${slug}`),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx35-reader')).toBeVisible({timeout:15000});await expect(page.getByRole('heading',{name:/Felicidade Depende de Nós/})).toBeVisible();await expect(page.locator('#app')).not.toContainText('Página não encontrada');await noOverflow(page,2)});

test('manga catalog is a dedicated responsive product surface',async({page})=>{for(const width of [390,768,1440]){await page.setViewportSize({width,height:width===390?844:900});await page.goto(pageUrl('/mangas'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx42-manga-page')).toBeVisible({timeout:30000});await expect(page.getByRole('heading',{name:'Catálogo de Mangás'})).toBeVisible();await expect(page.locator('.nx42-manga-card').first()).toBeVisible();await expect(page.locator('#nx42MangaSearch')).toBeVisible();await noOverflow(page,3)}});

test('single Home impression is complete and does not look like a broken rail',async({page})=>{const impression={id:'imp-one',media_id:101,body:'Uma estreia excelente e cheia de personalidade.',created_at:new Date().toISOString(),username:'kayky',status:'CURRENT',progress:5,score:9,media:{id:101,title:'Anime Teste 101',cover:pixel}};await page.route(`${new URL(ORIGIN).origin}/api/community/impressions**`,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[impression]})}));await page.addInitScript(({pixel,impression})=>localStorage.setItem('aninexus:impressions:v1',JSON.stringify([{...impression,mediaId:101,createdAt:impression.created_at,media:{...impression.media,cover:pixel}}])),{pixel,impression});await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});const card=page.locator('.nx38-impression-home-card').first();await expect(card).toBeVisible({timeout:30000});await expect(card).toContainText('Uma estreia excelente');await expect(card.locator('.nx38-impression-meta-row')).toContainText('Assistindo');await expect(card.locator('.nx38-impression-meta-row')).toContainText('episódio 5');await expect(page.locator('.nx38-impressions-rail')).toHaveAttribute('data-count','1');await expect(page.getByRole('button',{name:'Impressão anterior'})).toBeDisabled();await noOverflow(page,2)});

test('dedicated pages have one renderer and never flash a legacy layout',async({page,browserName})=>{test.skip(browserName!=='chromium','A troca temporal de layout é auditada uma vez no Chromium.');await page.addInitScript(()=>{window.__nxLayouts=[];const record=()=>{const el=document.querySelector('#app')?.firstElementChild;if(!el)return;const value=`${el.tagName}.${String(el.className||'').trim()}`;if(window.__nxLayouts.at(-1)!==value)window.__nxLayouts.push(value)};new MutationObserver(record).observe(document,{childList:true,subtree:true});addEventListener('DOMContentLoaded',record,{once:true})});const cases=[['/','nx35-home'],['/animes/catalogo','nx21-catalog-page'],['/animes/programacao','nx18-schedule'],['/animes/temporadas','nx-season'],['/anime/anime-teste-101','nx22-detail'],['/noticias','nx35-news-page'],['/comunidade','nx40-community'],['/login','nx38-auth-page'],['/admin','nx38-admin-page'],['/meus-animes','nx38-library'],['/termos-de-uso','nx-legal'],['/quem-somos','nx-inst']];for(const[route,prefix]of cases){await page.goto(pageUrl(route),{waitUntil:'domcontentloaded'});await expect(page.locator(`.${prefix}`).first()).toBeVisible({timeout:30000});await page.waitForTimeout(300);const history=await page.evaluate(()=>window.__nxLayouts||[]);expect(history,`${route}: ${history.join(' -> ')}`).not.toContain(expect.stringMatching(/detail-hero|nx-detail(?:-loading)?|catalog-hero|community-page|news-hero|prose/));expect(history.every(value=>value.includes(prefix)),`${route}: ${history.join(' -> ')}`).toBe(true)}});

test('Home Catalog Programação Temporadas and Meus Animes share compact circular actions',async({page})=>{
  test.setTimeout(90000);
  const targets=[['/','button[data-fav]'],['/animes/catalogo','.nx21-actions button[data-fav]'],['/animes/programacao','.nx18-cover-actions button[data-nx18-fav]'],['/animes/temporadas','button[data-nx-fav]']];
  for(const [route,selector] of targets){await page.goto(pageUrl(route),{waitUntil:'domcontentloaded'});const b=page.locator(selector).first();await expect(b).toBeVisible({timeout:30000});await expect(b).toHaveCSS('width','34px');await expect(b).toHaveCSS('height','34px');await expect(b).toHaveCSS('border-radius',/50%|1[67]px/);await expect(b).toHaveCSS('display','grid')}
  await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});await expect(page.locator('button[data-fav]').first()).toBeVisible({timeout:30000});const ids=await page.evaluate(()=>[...document.querySelectorAll('button[data-fav]')].map(x=>Number(x.dataset.fav)).filter(Boolean).slice(0,1));await page.evaluate(ids=>{const id=ids[0],now=Date.now();localStorage.setItem('aninexus:favorites',JSON.stringify([id]));localStorage.setItem('aninexus:mediaState:v2',JSON.stringify({[id]:{status:'CURRENT',progress:1,score:null,reaction:'',updatedAt:now}}));localStorage.setItem('aninexus:mediaState:v1',localStorage.getItem('aninexus:mediaState:v2'))},ids);const id=ids[0];await page.route('**/api/me/library',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({user:{username:'teste'},list:[{media_id:id,status:'CURRENT',progress:1,media:anime(id)}],favorites:[{media_id:id,media:anime(id)}],impressions:[],impressionCount:0})}));await page.goto(pageUrl('/meus-animes'),{waitUntil:'domcontentloaded'});const lb=page.locator('.nx38-library-card-actions button[data-fav]').first();await expect(lb).toBeVisible({timeout:30000});await expect(lb).toHaveCSS('width','34px');await expect(lb).toHaveCSS('height','34px');await expect(lb).toHaveCSS('border-radius',/50%|1[67]px/)
});

test('favorite double click and burst represent one intention',async({page})=>{await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});await clear(page);const b=page.locator('button[data-fav]').first();await expect(b).toBeVisible({timeout:30000});await b.dblclick({delay:40});await expect(b).toHaveClass(/active/);await page.waitForTimeout(380);await b.click();await expect(b).not.toHaveClass(/active/);await page.waitForTimeout(380);await b.evaluate(el=>{for(let i=0;i<7;i++)el.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}))});await expect(b).toHaveClass(/active/)});

test('Programação opens one modal and saved status reaches Home and Community',async({page})=>{
  await page.goto(pageUrl('/animes/programacao'),{waitUntil:'domcontentloaded'});await clear(page);const card=page.locator('.nx18-card').first();await expect(card).toBeVisible({timeout:30000});const list=card.locator('button[data-nx18-status]').first();await expect(list).toBeVisible();const id=Number(await list.getAttribute('data-nx18-status'));const animeTitle=(await card.locator('h3').first().textContent())?.trim()||'';expect(id).toBeGreaterThan(0);
  await list.click();await expect(page.locator('.nx20-media-layer')).toHaveCount(1,{timeout:20000});await expect(page.locator('.nx20-modal')).toHaveCount(1);await page.locator('[data-nx20-status="CURRENT"]').click();const progress=page.locator('[data-nx20-progress]');if(await progress.count())await progress.fill('1');await page.locator('[data-nx20-save]').click();const savedStatus=await page.evaluate(id=>JSON.parse(localStorage.getItem('aninexus:mediaState:v2')||'{}')[id]?.status,id);expect(savedStatus).toBe('CURRENT');
  const activity=await page.evaluate(id=>(JSON.parse(localStorage.getItem('aninexus:community:activity:v40')||'[]')).find(x=>Number(x.media_id)===id&&x.status==='CURRENT'),id);expect(activity).toBeTruthy();
  await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx35-home')).toBeVisible({timeout:30000});await expect(page.locator('#nx35CommunityHero')).toContainText('está assistindo',{timeout:15000});if(animeTitle)await expect(page.locator('#nx35CommunityHero')).toContainText(animeTitle,{timeout:15000});
  const malformed=`${ORIGIN}?build=38.0.0&p=${encodeURIComponent('/comunidade?build=35.0.0')}`;await page.goto(malformed,{waitUntil:'domcontentloaded'});await expect(page.locator('.nx40-community')).toBeVisible({timeout:30000});await expect(page.locator('.nx40-community')).not.toContainText('O que você está assistindo hoje?');await expect(page.locator('.nx40-feed')).toContainText('está assistindo');if(animeTitle)await expect(page.locator('.nx40-feed')).toContainText(animeTitle);await noOverflow(page)
});

test('Community V40 exposes activity impressions discussions trends and local composer',async({page})=>{
  let postedThread=null;
  await page.route('**/api/community/threads**',async route=>{if(route.request().method()==='POST'){postedThread={id:'thread-test',username:'teste',...route.request().postDataJSON(),replies:0,created_at:new Date().toISOString()};return route.fulfill({status:201,contentType:'application/json',body:JSON.stringify(postedThread)})}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:postedThread?[postedThread]:[]})})});
  await page.goto(pageUrl('/comunidade'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx40-community')).toBeVisible({timeout:30000});for(const label of ['Tudo','Atividade','Impressões','Discussões'])await expect(page.getByRole('button',{name:label,exact:true})).toBeVisible();await expect(page.locator('#nx40Stats')).toBeVisible();await expect(page.locator('#nx40Trending')).toBeVisible();await page.locator('[data-nx40-new]').click();await expect(page.locator('#nx40ThreadModal')).toBeVisible();await page.locator('#nx40ThreadForm input[name="title"]').fill('Discussão de teste');await page.locator('#nx40ThreadForm textarea').fill('Uma conversa de teste para validar a Comunidade V40.');await page.locator('#nx40ThreadForm button[type="submit"]').click();await expect(page.locator('#nx40ThreadModal')).toBeHidden();await expect(page.locator('.nx40-feed')).toContainText('Discussão de teste');await noOverflow(page)
});

test('Catalog opens dedicated anime detail without action click leaking to card',async({page})=>{const origin=new URL(ORIGIN);if(!origin.hostname.endsWith('github.io'))await page.route(`${origin.origin}/anime/**`,async route=>route.fulfill({response:await route.fetch({url:`${origin.origin}/`})}));await page.goto(pageUrl('/animes/catalogo'),{waitUntil:'domcontentloaded'});const card=page.locator('.nx21-card').first();await expect(card).toBeVisible({timeout:30000});const before=page.url(),fav=card.locator('button[data-fav]').first();await fav.click();expect(page.url()).toBe(before);await page.waitForTimeout(380);await card.locator('h3').click();await page.waitForURL(u=>{const url=new URL(u);return url.searchParams.get('p')?.startsWith('/anime/')===true||url.pathname.startsWith('/anime/')},{timeout:15000});await expect(page.locator('.nx22-detail')).toBeVisible({timeout:30000})});

test('mobile openings load only the selected video and stay inside the viewport',async({page})=>{await page.setViewportSize({width:390,height:844});let mediaRequests=0;await page.route('https://api.animethemes.moe/**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(themeApiData())}));await page.route('https://v.animethemes.moe/**',route=>{mediaRequests++;return route.fulfill({status:200,contentType:'video/webm',body:''})});await page.goto(pageUrl('/anime/anime-teste-101'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx22-detail')).toBeVisible({timeout:30000});await page.getByRole('tab',{name:'Aberturas & encerramentos'}).click();await expect(page.locator('#nx22Themes')).toHaveAttribute('data-state','ready',{timeout:15000});await expect(page.locator('.nx22-theme-card')).toHaveCount(24);expect(mediaRequests).toBe(0);await expect(page.locator('.nx22-theme-card video[src]')).toHaveCount(0);await noOverflow(page);await page.locator('[data-nx22-theme-play]').first().click();await expect(page.locator('.nx22-theme-card video[src]')).toHaveCount(1);await expect(page.locator('.nx22-theme-card video[preload="metadata"]')).toHaveCount(1);await expect(page.locator('.nx22-theme-card:not(.is-loaded) video[src]')).toHaveCount(0);await noOverflow(page)});

test('mobile openings hide technical upstream errors',async({page})=>{await page.setViewportSize({width:390,height:844});await page.route('https://api.animethemes.moe/**',route=>route.abort('failed'));await page.goto(pageUrl('/anime/anime-teste-101'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx22-detail')).toBeVisible({timeout:30000});await page.getByRole('tab',{name:'Aberturas & encerramentos'}).click();await expect(page.locator('#nx22Themes')).toHaveAttribute('data-state','error',{timeout:15000});await expect(page.locator('#nx22Themes')).toContainText('Não foi possível carregar este acervo agora');await expect(page.locator('#nx22Themes')).not.toContainText(/Load failed|Failed to fetch|NetworkError/i);await expect(page.getByRole('button',{name:'Tentar novamente'})).toBeVisible();await noOverflow(page,2)});

test('anime detail failures hide provider diagnostics and dependent forms',async({page})=>{await page.unroute('https://graphql.anilist.co/');await page.route('https://graphql.anilist.co/',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({errors:[{message:'upstream diagnostic'}]})}));await page.goto(pageUrl('/anime/anime-teste-101'),{waitUntil:'domcontentloaded'});const failure=page.locator('.nx22-fail');await expect(failure).toBeVisible({timeout:30000});await expect(failure).toContainText('O catálogo está temporariamente indisponível');await expect(failure).not.toContainText(/AniList|upstream|503|diagnostic/i);await expect(page.locator('.nx42-impressions')).toHaveCount(0);await noOverflow(page,2)});

test('anime detail light theme styles navigation content and forms coherently',async({page})=>{await page.addInitScript(()=>localStorage.setItem('aninexus:theme','light'));await page.goto(pageUrl('/anime/anime-teste-101'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx22-detail:not(.nx22-fail)')).toBeVisible({timeout:30000});await expect(page.locator('html')).toHaveAttribute('data-theme','light');await expect(page.locator('.topbar')).toHaveCSS('background-color',/rgba?\(255, 250, 251/);await expect(page.locator('.nx22-info-card').first()).toHaveCSS('background-color','rgb(255, 255, 255)');await expect(page.locator('.nx42-impression-form')).toHaveCSS('background-color','rgb(255, 255, 255)');await noOverflow(page,2)});

test('News and authentication remain healthy after V40',async({page})=>{await page.goto(pageUrl('/noticias'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx35-news-page')).toBeVisible({timeout:30000});await noOverflow(page);await page.goto(pageUrl('/login'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx38-auth-page')).toBeVisible({timeout:15000});await expect(page.locator('.nx38-auth-card h2')).toHaveText('Ativação segura em andamento');await expect(page.locator('.nx38-auth-unavailable')).toContainText('Nenhum dado privado');await noOverflow(page)});

test('mobile authentication is compact readable and never overflows',async({page})=>{for(const width of [320,360,390,430]){await page.setViewportSize({width,height:844});await page.goto(pageUrl('/login'),{waitUntil:'domcontentloaded'});const auth=page.locator('.nx38-auth-page');await expect(auth).toBeVisible({timeout:15000});await expect(page.locator('.nx38-auth-benefits')).toBeHidden();await expect(page.locator('.nx38-auth-copy>p')).toBeHidden();const storyHeight=await page.locator('.nx38-auth-story').evaluate(element=>element.getBoundingClientRect().height);expect(storyHeight).toBeLessThan(140);await noOverflow(page,2)}});

test('menu keeps exactly the eight approved destinations and one main landmark',async({page})=>{await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});const labels=await page.locator('.main-nav>a').allTextContents();expect(labels.map(x=>x.trim())).toEqual(['Início','Catálogo','Temporadas','Programação','Anime Awards','Meus Animes','Notícias','Comunidade']);await expect(page.locator('#app main')).toHaveCount(1);await expect(page.locator('main main')).toHaveCount(0)});

test('all required widths stay inside the viewport',async({page,browserName})=>{test.skip(browserName!=='chromium','A matriz completa de larguras roda uma vez; Firefox e WebKit executam os fluxos críticos.');for(const width of [320,360,375,390,414,768,820,1024,1280,1440,1920]){await page.setViewportSize({width,height:width<600?844:900});await page.goto(pageUrl(width<600?'/animes/catalogo':'/'),{waitUntil:'domcontentloaded'});await page.locator('#app main').first().waitFor({state:'visible',timeout:30000});await noOverflow(page,8)}});

test('public navigation degrades gracefully when AniList is unavailable',async({page})=>{await page.unroute('https://graphql.anilist.co/');await page.route('https://graphql.anilist.co/',route=>route.abort('failed'));await page.goto(pageUrl('/animes/catalogo'),{waitUntil:'domcontentloaded'});await expect(page.locator('#app main').first()).toBeVisible({timeout:30000});await expect(page.locator('body')).not.toContainText('HTTP 500');await noOverflow(page)});

test('mobile Community and Programação do not overflow',async({page})=>{await page.setViewportSize({width:390,height:844});for(const route of ['/comunidade','/animes/programacao']){await page.goto(pageUrl(route),{waitUntil:'domcontentloaded'});await expect(page.locator(route==='/comunidade'?'.nx40-community':'.nx18-schedule').first()).toBeVisible({timeout:30000});await noOverflow(page)}});

test('public profile and profile editor are complete on mobile',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.route('**/runtime-config.js*',route=>route.fulfill({status:200,contentType:'application/javascript',body:`window.__ANINEXUS_CONFIG__=Object.freeze({environment:'test',siteOrigin:'https://qgbaltigo.github.io/AniNexus',apiOrigin:'https://graphql.anilist.co',clerkPublishableKey:'pk_test_profile',authEnabled:true});`}));
  await page.route('**/api/users/kayky',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({profile:{username:'kayky',displayName:'Kayky',avatarUrl:pixel,bannerUrl:pixel,bio:'Anime, mangá e boas conversas.',location:'Cuiabá, MT',websiteUrl:'https://example.com',instagramHandle:'kayky',telegramHandle:'kayky',role:'user',privacy:'public',isPrivate:false,createdAt:'2026-01-01T00:00:00.000Z'},stats:{list_total:18,watching:4,completed:10,episodes_watched:320,average_score:8.7},library:[{media_id:101,status:'CURRENT',progress:5,score:9,media:{id:101,title:'Anime Teste 101',cover:pixel}}],activity:[{media_id:101,status:'CURRENT',progress:5,created_at:new Date().toISOString(),media:{id:101,title:'Anime Teste 101',cover:pixel}}],impressions:[{id:'one',media_id:101,body:'Uma ótima estreia.',spoiler:false,created_at:new Date().toISOString(),media:{id:101,title:'Anime Teste 101',cover:pixel}}]})}));
  await page.goto(pageUrl('/u/kayky'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx38p-page')).toBeVisible({timeout:15000});await expect(page.locator('.nx38p-person h1')).toHaveText('Kayky');await expect(page.locator('.nx38p-stats')).toContainText('320');const svgBoxes=await page.locator('.nx38p-meta svg,.nx38p-socials svg,.nx38p-share svg,.nx38p-content-nav svg').evaluateAll(nodes=>nodes.map(node=>node.getBoundingClientRect()));expect(svgBoxes.length).toBeGreaterThan(4);for(const box of svgBoxes){expect(box.width).toBeLessThanOrEqual(20);expect(box.height).toBeLessThanOrEqual(20)}await page.getByRole('button',{name:'Assistindo'}).click();await expect(page.locator('.nx38p-media:visible')).toBeVisible();await noOverflow(page,2);
  await page.evaluate(()=>window.AniNexusProfileV38.openEditor({username:'kayky',displayName:'Kayky',avatarUrl:'',bannerUrl:'',bio:'Anime e mangá',privacy:'public',showLibrary:true,showActivity:true,showStats:true}));await expect(page.getByRole('heading',{name:'Personalizar perfil'})).toBeVisible();await expect(page.locator('input[name="username"]')).toHaveValue('kayky');await expect(page.locator('input[name="avatarUrl"]')).toBeVisible();await noOverflow(page,2)
});

test('discovery hubs replace placeholder pages and remain responsive',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto(pageUrl('/listas-de-animes'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx-list-group').first()).toBeVisible({timeout:15000});await expect(page.locator('#listsHub')).toContainText('Melhores animes para assistir');await noOverflow(page,2);await page.goto(pageUrl('/animes/estudios'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx-studio-card').first()).toBeVisible({timeout:15000});await noOverflow(page,2)});
