import {test,expect} from '@playwright/test';
const ORIGIN=process.env.ANINEXUS_E2E_ORIGIN||'http://qgbaltigo.github.io:4173/AniNexus/';
const pageUrl=route=>`${ORIGIN}?build=40.0.0&p=${encodeURIComponent(route)}`;
async function noOverflow(page,t=7){const x=await page.evaluate(()=>({s:document.documentElement.scrollWidth,w:innerWidth}));expect(x.s).toBeLessThanOrEqual(x.w+t)}
async function clear(page){await page.evaluate(()=>{for(const k of ['aninexus:favorites','aninexus:mediaState:v2','aninexus:mediaState:v1','aninexus:list','aninexus:listStatus','aninexus:community:activity:v40','aninexus:community:threads:v40'])localStorage.removeItem(k);window.AniNexusMediaState?.sync?.()})}
async function geometry(b){return b.evaluate(el=>{const s=getComputedStyle(el),box=el.getBoundingClientRect();return{w:box.width,h:box.height,r:s.borderRadius,d:s.display}})}
test.describe.configure({mode:'serial'});

test('V40 Home is the current renderer',async({page})=>{await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx35-home')).toBeVisible({timeout:30000});await expect(page.locator('.aqx-home')).toHaveCount(0);await expect(page.locator('meta[name="aninexus-build"]')).toHaveAttribute('content','2026-08-24-v40.2.0')});

test('Home Catalog Programação Temporadas and Meus Animes share compact circular actions',async({page})=>{
  const targets=[['/','button[data-fav]'],['/animes/catalogo','.nx21-actions button[data-fav]'],['/animes/programacao','.nx18-cover-actions button[data-nx18-fav]'],['/animes/temporadas','button[data-nx-fav]']];
  for(const [route,selector] of targets){await page.goto(pageUrl(route),{waitUntil:'domcontentloaded'});const b=page.locator(selector).first();await expect(b).toBeVisible({timeout:30000});const g=await geometry(b);expect(g.w).toBeGreaterThanOrEqual(33);expect(g.w).toBeLessThanOrEqual(35);expect(g.h).toBeGreaterThanOrEqual(33);expect(g.h).toBeLessThanOrEqual(35);expect(g.r).toMatch(/50%|1[67]px/);expect(g.d).toBe('grid')}
  await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});const ids=await page.evaluate(()=>[...document.querySelectorAll('button[data-fav]')].map(x=>Number(x.dataset.fav)).filter(Boolean).slice(0,1));await page.evaluate(ids=>{const id=ids[0],now=Date.now();localStorage.setItem('aninexus:favorites',JSON.stringify([id]));localStorage.setItem('aninexus:mediaState:v2',JSON.stringify({[id]:{status:'CURRENT',progress:1,score:null,reaction:'',updatedAt:now}}));localStorage.setItem('aninexus:mediaState:v1',localStorage.getItem('aninexus:mediaState:v2'))},ids);await page.goto(pageUrl('/meus-animes'),{waitUntil:'domcontentloaded'});const lb=page.locator('.nx38-library-card-actions button[data-fav]').first();await expect(lb).toBeVisible({timeout:30000});const g=await geometry(lb);expect(g.w).toBeGreaterThanOrEqual(33);expect(g.w).toBeLessThanOrEqual(35);expect(g.r).toMatch(/50%|1[67]px/)
});

test('favorite double click and burst represent one intention',async({page})=>{await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});await clear(page);const b=page.locator('button[data-fav]').first();await expect(b).toBeVisible({timeout:30000});await b.dblclick({delay:40});await expect(b).toHaveClass(/active/);await page.waitForTimeout(380);await b.click();await expect(b).not.toHaveClass(/active/);await page.waitForTimeout(380);await b.evaluate(el=>{for(let i=0;i<7;i++)el.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}))});await expect(b).toHaveClass(/active/)});

test('Programação rapid + clicks open one modal and saved status reaches Home and Community',async({page})=>{
  await page.goto(pageUrl('/animes/programacao'),{waitUntil:'domcontentloaded'});await clear(page);const card=page.locator('.nx18-card').first();await expect(card).toBeVisible({timeout:30000});const list=card.locator('button[data-nx18-status]').first();await expect(list).toBeVisible();const id=Number(await list.getAttribute('data-nx18-status'));const animeTitle=(await card.locator('h3').first().textContent())?.trim()||'';expect(id).toBeGreaterThan(0);
  await list.evaluate(el=>{for(let i=0;i<6;i++)el.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}))});await expect(page.locator('.nx20-media-layer')).toHaveCount(1,{timeout:20000});await expect(page.locator('.nx20-modal')).toHaveCount(1);await page.locator('[data-nx20-status="CURRENT"]').click();const progress=page.locator('[data-nx20-progress]');if(await progress.count())await progress.fill('1');await page.locator('[data-nx20-save]').click();await expect(list).toHaveAttribute('data-nx-unified-status','CURRENT');
  const activity=await page.evaluate(id=>(JSON.parse(localStorage.getItem('aninexus:community:activity:v40')||'[]')).find(x=>Number(x.media_id)===id&&x.status==='CURRENT'),id);expect(activity).toBeTruthy();
  await page.goto(pageUrl('/'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx35-home')).toBeVisible({timeout:30000});await expect(page.locator('#nx35CommunityHero')).toContainText('está assistindo',{timeout:15000});if(animeTitle)await expect(page.locator('#nx35CommunityHero')).toContainText(animeTitle,{timeout:15000});
  const malformed=`${ORIGIN}?build=38.0.0&p=${encodeURIComponent('/comunidade?build=35.0.0')}`;await page.goto(malformed,{waitUntil:'domcontentloaded'});await expect(page.locator('.nx40-community')).toBeVisible({timeout:30000});await expect(page.locator('.nx40-community')).not.toContainText('O que você está assistindo hoje?');await expect(page.locator('.nx40-feed')).toContainText('está assistindo');if(animeTitle)await expect(page.locator('.nx40-feed')).toContainText(animeTitle);await noOverflow(page)
});

test('Community V40 exposes activity impressions discussions trends and local composer',async({page})=>{await page.goto(pageUrl('/comunidade'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx40-community')).toBeVisible({timeout:30000});for(const label of ['Tudo','Atividade','Impressões','Discussões'])await expect(page.getByRole('button',{name:label,exact:true})).toBeVisible();await expect(page.locator('#nx40Stats')).toBeVisible();await expect(page.locator('#nx40Trending')).toBeVisible();await page.locator('[data-nx40-new]').click();await expect(page.locator('#nx40ThreadModal')).toBeVisible();await page.locator('#nx40ThreadForm input[name="title"]').fill('Discussão de teste');await page.locator('#nx40ThreadForm textarea').fill('Uma conversa de teste para validar a Comunidade V40.');await page.locator('#nx40ThreadForm button[type="submit"]').click();await expect(page.locator('#nx40ThreadModal')).toBeHidden();await expect(page.locator('.nx40-feed')).toContainText('Discussão de teste');await noOverflow(page)});

test('Catalog opens dedicated anime detail without action click leaking to card',async({page})=>{await page.goto(pageUrl('/animes/catalogo'),{waitUntil:'domcontentloaded'});const card=page.locator('.nx21-card').first();await expect(card).toBeVisible({timeout:30000});const before=page.url(),fav=card.locator('button[data-fav]').first();await fav.click();expect(page.url()).toBe(before);await page.waitForTimeout(380);await card.locator('h3').click();await page.waitForURL(u=>(new URL(u)).searchParams.get('p')?.startsWith('/anime/')===true,{timeout:15000});await expect(page.locator('.nx22-detail')).toBeVisible({timeout:30000})});

test('News and authentication remain healthy after V40',async({page})=>{await page.goto(pageUrl('/noticias'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx35-news-page')).toBeVisible({timeout:30000});await noOverflow(page);await page.goto(pageUrl('/login'),{waitUntil:'domcontentloaded'});await expect(page.locator('.nx38-auth-page')).toBeVisible({timeout:15000});await expect(page.locator('.nx38-auth-card h2')).toHaveText('Entre na sua conta');await noOverflow(page)});

test('mobile Community and Programação do not overflow',async({page})=>{await page.setViewportSize({width:390,height:844});for(const route of ['/comunidade','/animes/programacao']){await page.goto(pageUrl(route),{waitUntil:'domcontentloaded'});await expect(page.locator(route==='/comunidade'?'.nx40-community':'.nx18-schedule').first()).toBeVisible({timeout:30000});await noOverflow(page)}});
