import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {cleanText,canonicalUrl,sourceFingerprint,storyFingerprint,classifyNews,extractHtmlMetadata,qualityScore} from '../lib/news-core.mjs';
import {languageScore,likelyPortuguese} from '../lib/news-sources-v35.mjs';

const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8');let passed=0;
function test(name,fn){try{fn();passed++;console.log(`✓ ${name}`)}catch(err){console.error(`✗ ${name}\n  ${err.message}`);process.exitCode=1}}

test('core text and URL normalization remain stable',()=>{assert.equal(cleanText('<b>Anime</b>&nbsp; &amp; mangá'),'Anime & mangá');assert.equal(canonicalUrl('https://example.com/a/?utm_source=x#x'),'https://example.com/a');assert.equal(sourceFingerprint('https://example.com/a?utm_source=x'),sourceFingerprint('https://example.com/a'))});
test('story fingerprint and classifier remain deterministic',()=>{assert.equal(storyFingerprint('Anime ganha temporada','Nova temporada confirmada'),storyFingerprint('Anime ganha temporada','Nova temporada confirmada'));assert.equal(classifyNews({title:'Novo trailer de Chainsaw Man'}),'TRAILER');assert.equal(classifyNews({title:'Editora lança novo mangá'}),'MANGA')});
test('metadata extractor reads real article images',()=>{const h=`<script type="application/ld+json">${JSON.stringify({'@type':'NewsArticle',headline:'Nova temporada',description:'A produção confirmou novidades importantes.',image:'https://cdn.example.com/a.jpg',datePublished:'2026-08-22T10:00:00Z',articleBody:'A estreia foi confirmada para outubro e o elenco retorna.'})}</script>`;const m=extractHtmlMetadata(h,'https://example.com/a');assert.equal(m.imageUrl,'https://cdn.example.com/a.jpg');assert.match(m.articleText,/estreia/) });
test('quality score rewards complete reporting',()=>{const low=qualityScore({title:'Curta',summary:'Breve.'}),high=qualityScore({title:'Anime confirma nova temporada e estreia',summary:'A produção confirmou oficialmente a continuação, data e elenco principal.',imageUrl:'https://example.com/a.jpg',publishedAt:new Date().toISOString(),sources:[{name:'JBox'}],facts:['A estreia foi confirmada.']});assert.ok(high>low)});
test('Portuguese gate rejects the English examples that broke the site',()=>{assert.equal(likelyPortuguese('O anime ganhou uma nova temporada e a estreia foi confirmada para outubro.'),true);assert.equal(likelyPortuguese('Manga Mavericks Books Licenses Midnight Robot, Arai-kun & Haruma-senpai Manga'),false);assert.equal(likelyPortuguese('The anime reveals more cast and a worldwide release date for the new season.'),false);const pt=languageScore('Nova temporada foi anunciada com estreia no Brasil'),en=languageScore('The new season was announced with worldwide release');assert.ok(pt.pt>pt.en);assert.ok(en.en>en.pt)});

const source=read('lib/news-sources-v35.mjs'),sourceShim=read('lib/news-sources-v34.mjs'),worker=read('lib/news-worker-v34.mjs'),updater=read('scripts/update-news-v35.mjs'),workflow=read('.github/workflows/update-news.yml'),home=read('preview-v35/home-v35.js'),homeCss=read('preview-v35/home-v35.css'),guard=read('preview-v24/home-guard-v24.js'),newsData=read('preview-v35/news-data-v35.js'),newsUi=read('preview-v35/news-ui-v35.js'),newsCss=read('preview-v35/news-v35.css'),homeEntry=read('preview-v33/home-v33.js'),newsEntry=read('preview-v33/news-v33.js'),index=read('index.html');

test('V35 sources prioritize Brazilian JBox and Crunchyroll PT',()=>{['JBOX_ANIME','JBOX_MANGA','JBox Anime','JBox Mangá','Crunchyroll Notícias','pt-BR'].forEach(x=>assert.ok(source.includes(x),x));assert.ok(source.indexOf("['JBOX_ANIME'")<source.indexOf("['MAL'"))});
test('V35 still uses MAL and ANN only as supplemental sources',()=>{assert.ok(source.includes('myanimelist.net/rss/news.xml'));assert.ok(source.includes('animenewsnetwork.com/all/rss.xml'));assert.ok(source.includes("x.sourceKey?.startsWith('JBOX')?6"))});
test('V35 rejects roundups, English failures and image-less automated stories',()=>{assert.ok(source.includes('all the news and reviews'));assert.ok(source.includes("reason:'translation'"));assert.ok(source.includes("if(!imageUrl)return{reason:'quality'}"));assert.ok(source.includes('fallbackImage'))});
test('existing server worker is safely routed through V35 collector',()=>{assert.ok(sourceShim.includes("from './news-sources-v35.mjs'"));assert.ok(worker.includes("from './news-sources-v34.mjs'"));assert.ok(worker.includes("language='pt-BR'"));assert.ok(worker.includes("translation_status='ready'"))});
test('static updater purges old English and image-less fallback items',()=>{assert.ok(updater.includes('x?.image&&dateOk'));assert.ok(updater.includes('likelyPortuguese'));assert.ok(updater.includes('collectorVersion:35'));assert.ok(updater.includes('JBox Anime'))});
test('hourly news workflow runs V35 collector and updater',()=>{assert.ok(workflow.includes("cron: '17 * * * *'"));assert.ok(workflow.includes('news-sources-v35.mjs'));assert.ok(workflow.includes('update-news-v35.mjs'))});

test('Home V35 is a single renderer with no MutationObserver repaint loop',()=>{assert.equal(home.includes('MutationObserver'),false);assert.ok(home.includes('nx35-home'));assert.ok(home.includes('setInterval(updateCountdowns,1000)'));assert.equal(index.includes('preview-v28/home-v28.js'),false)});
test('Home boot hides legacy output until V35 mounts',()=>{assert.ok(guard.includes('__NX35_HOME_BOOT__'));assert.ok(guard.includes('__nx35_home_boot__'));assert.equal(guard.includes('__NX_HOME_DEDICATED__'),false);assert.ok(homeCss.includes('html.nx35-home-boot #app'))});
test('Home upcoming episodes reuse exact Programação card classes',()=>{['nx18-card','nx18-cover','nx18-cover-actions','nx18-info','nx18-air','nx18-countdown','nx18-stream','nx18-provider-logo','nx18-episode'].forEach(x=>assert.ok(home.includes(x),x))});
test('Home provider fallbacks use Programação brand treatments instead of letter hacks',()=>{['nx18-crunchy','nx18-netflix','nx18-prime','nx18-disney','nx18-apple','nx18-hidive'].forEach(x=>assert.ok(home.includes(x),x))});
test('Community activity includes anime cover/banner/status context',()=>{['mediaByIds','banner(m)','nx35-community-cover',"PAUSED:{verb:'pausou'","COMPLETED:{verb:'terminou'"].forEach(x=>assert.ok(home.includes(x),x))});
test('Every horizontal Home rail has smooth weak directional fades',()=>{assert.ok(home.includes('scrollWidth-el.clientWidth'));assert.ok(home.includes("host.dataset.left"));assert.ok(home.includes("host.dataset.right"));assert.ok(homeCss.includes('.nx35-edge[data-left="1"]:before'));assert.ok(homeCss.includes('.nx35-edge[data-right="1"]:after'));assert.ok(homeCss.includes('opacity:.55'));assert.ok(homeCss.includes('scroll-behavior:smooth'))});
test('Top 10 and achievements use AniNexus red and centered layout',()=>{assert.ok(homeCss.includes('.nx35-rank-copy small{color:#e24967'));assert.ok(homeCss.includes('.nx35-achievement-section .nx35-head{justify-content:center;text-align:center}'));assert.equal(homeCss.includes('#a96ee8'),false)});

test('News V35 data layer fail-closes bad content',()=>{assert.ok(newsData.includes('likelyPt'));assert.ok(newsData.includes('weekly roundup'));assert.ok(newsData.includes("/api/news?limit=50"));assert.ok(newsData.includes('data/news.json?v=${BUILD}'))});
test('News V35 stays internal and avoids giant typography',()=>{assert.ok(newsUi.includes('Ler no AniNexus'));assert.equal(newsUi.includes('Ler na fonte'),false);assert.equal(newsUi.includes('window.open('),false);assert.ok(newsUi.includes('EM RESUMO'));assert.ok(newsCss.includes('clamp(34px,4vw,52px)'));assert.ok(newsCss.includes('.nx35-ncard.feature h3{font-size:22px'))});
test('V35 entrypoints and cache bust are active',()=>{assert.ok(homeEntry.includes('home-v35.js?v=35.0.0'));assert.ok(newsEntry.includes('news-data-v35.js'));assert.ok(newsEntry.includes('news-ui-v35.js'));assert.ok(index.includes('2026-08-22-v35.0.0'));assert.ok(index.includes('preview-v33/home-v33.js?v=35.0.0'));assert.ok(index.includes('preview-v33/news-v33.js?v=35.0.0'))});

if(process.exitCode)throw new Error('AniNexus V35 tests failed');
console.log(`\nAniNexus V35: ${passed} tests passed`);
