import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {cleanText,canonicalUrl,sourceFingerprint,storyFingerprint,classifyNews,extractHtmlMetadata,qualityScore} from '../lib/news-core.mjs';
import {languageScore,likelyPortuguese} from '../lib/news-sources-v36.mjs';

const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8');let passed=0;
function test(name,fn){try{fn();passed++;console.log(`✓ ${name}`)}catch(err){console.error(`✗ ${name}\n  ${err.message}`);process.exitCode=1}}

test('core normalization remains stable',()=>{assert.equal(cleanText('<b>Anime</b>&nbsp; &amp; mangá'),'Anime & mangá');assert.equal(canonicalUrl('https://example.com/a/?utm_source=x#x'),'https://example.com/a');assert.equal(sourceFingerprint('https://example.com/a?utm_source=x'),sourceFingerprint('https://example.com/a'))});
test('story fingerprint and classifier remain deterministic',()=>{assert.equal(storyFingerprint('Anime ganha temporada','Nova temporada confirmada'),storyFingerprint('Anime ganha temporada','Nova temporada confirmada'));assert.equal(classifyNews({title:'Novo trailer de Chainsaw Man'}),'TRAILER');assert.equal(classifyNews({title:'Editora lança novo mangá'}),'MANGA')});
test('metadata extractor reads article image and body',()=>{const h=`<script type="application/ld+json">${JSON.stringify({'@type':'NewsArticle',headline:'Nova temporada',description:'A produção confirmou novidades importantes.',image:'https://cdn.example.com/a.jpg',datePublished:'2026-08-22T10:00:00Z',articleBody:'A estreia foi confirmada para outubro e o elenco principal retorna. O estúdio também divulgou um novo visual.'})}</script>`;const m=extractHtmlMetadata(h,'https://example.com/a');assert.equal(m.imageUrl,'https://cdn.example.com/a.jpg');assert.match(m.articleText,/estúdio/) });
test('Portuguese gate rejects the English examples that broke the site',()=>{assert.equal(likelyPortuguese('O anime ganhou uma nova temporada e a estreia foi confirmada para outubro.'),true);assert.equal(likelyPortuguese('Manga Mavericks Books Licenses Midnight Robot, Arai-kun & Haruma-senpai Manga'),false);assert.equal(likelyPortuguese('The anime reveals more cast and a worldwide release date for the new season.'),false);const pt=languageScore('Nova temporada foi anunciada com estreia no Brasil'),en=languageScore('The new season was announced with worldwide release');assert.ok(pt.pt>pt.en);assert.ok(en.en>en.pt)});
test('quality score still rewards complete reporting',()=>{const low=qualityScore({title:'Curta',summary:'Breve.'}),high=qualityScore({title:'Anime confirma nova temporada e estreia',summary:'A produção confirmou oficialmente a continuação, data e elenco principal.',imageUrl:'https://example.com/a.jpg',publishedAt:new Date().toISOString(),sources:[{name:'JBox'}],facts:['A estreia foi confirmada.','O elenco principal retorna.']});assert.ok(high>low)});

const source=read('lib/news-sources-v36.mjs'),normalized=read('lib/news-sources-v36-normalized.mjs'),sourceShim=read('lib/news-sources-v34.mjs'),worker=read('lib/news-worker-v34.mjs'),updater=read('scripts/update-news-v36.mjs'),workflow=read('.github/workflows/update-news.yml'),newsData=read('preview-v35/news-data-v35.js'),newsUi=read('preview-v35/news-ui-v35.js'),newsCss=read('preview-v35/news-v35.css'),feed=JSON.parse(read('data/news.json')),seed=JSON.parse(read('data/news-v36-seed.json'));

test('V36 uses JBox WordPress REST as the deepest primary ingestion path',()=>{assert.ok(source.includes('/wp-json/wp/v2/posts?per_page=50'));assert.ok(source.includes('page<=2'));assert.ok(source.includes("ingestMode:'wp-rest'"));assert.ok(source.includes('articleHtml:content'));assert.ok(source.includes('articleText:rich.articleText'))});
test('V36 keeps JBox category RSS fallback and Crunchyroll PT',()=>{assert.ok(source.includes("jboxCategory('/categoria/anime/'"));assert.ok(source.includes("jboxCategory('/categoria/manga/'"));assert.ok(source.includes('Crunchyroll Notícias'));assert.ok(source.includes("['pt-BR','pt-PT']"))});
test('MAL and ANN remain supplemental only',()=>{assert.ok(source.includes('myanimelist.net/rss/news.xml'));assert.ok(source.includes('animenewsnetwork.com/all/rss.xml'));assert.ok(source.includes("x.sourceKey?.startsWith('JBOX')?8"));assert.ok(source.includes("x.sourceKey==='CRUNCHYROLL'?6"))});
test('V36 reads far more of each article than the old summary collector',()=>{assert.ok(source.includes('blocks.length>=46'));assert.ok(source.includes('22000'));assert.ok(source.includes('splitFacts(paragraphs,28)'));assert.ok(source.includes('uniqueFacts'));assert.ok(source.includes('max=22'))});
test('V36 structures rich reader sections from all confirmed details',()=>{['Estreia, lançamento e disponibilidade','Produção, equipe e elenco','Materiais divulgados','História e contexto da obra','Outros detalhes confirmados','Acompanhamento AniNexus'].forEach(x=>assert.ok(source.includes(x),x));assert.ok(source.includes('facts.length<2'));assert.ok(source.includes('sections.length>=5'))});
test('V36 stores coverage metrics and requires at least two-minute rich reads',()=>{assert.ok(source.includes('coverage:{facts:facts.length'));assert.ok(source.includes('Math.max(2,Math.ceil(wordCount/210))'));assert.ok(updater.includes('deepArticles'));assert.ok(updater.includes('avgWords'))});
test('date-normalization wrapper derives article publication time from real source timestamps',()=>{assert.ok(normalized.includes('sourcePublishedAt'));assert.ok(normalized.includes("Date.parse(source?.publishedAt||'')"));assert.ok(normalized.includes('Math.max(...times)'));assert.ok(normalized.includes('new Date(b.publishedAt)-new Date(a.publishedAt)'));assert.ok(updater.includes("from '../lib/news-sources-v36-normalized.mjs'"))});
test('server worker compatibility shim now points to normalized V36',()=>{assert.ok(sourceShim.includes("from './news-sources-v36-normalized.mjs'"));assert.ok(worker.includes("from './news-sources-v34.mjs'"));assert.ok(worker.includes("language='pt-BR'"));assert.ok(worker.includes("translation_status='ready'"));assert.ok(worker.includes('splitFacts(a.facts||[],22)'))});
test('V36 updater keeps a seven-day, up-to-60-item feed and never overwrites it empty',()=>{assert.ok(updater.includes('NEWS_RETENTION_DAYS||7'));assert.ok(updater.includes('NEWS_STATIC_MAX_ITEMS||60'));assert.ok(updater.includes('NEWS_MIN_SAFE_FEED||10'));assert.ok(updater.includes('previousItems'));assert.ok(updater.includes('nenhuma matéria PT-BR válida'));assert.ok(updater.includes('collectorVersion:36'))});
test('V36 workflow refreshes twice an hour with broader coverage',()=>{assert.ok(workflow.includes("cron: '17,47 * * * *'"));assert.ok(workflow.includes('news-sources-v36.mjs'));assert.ok(workflow.includes('news-sources-v36-normalized.mjs'));assert.ok(workflow.includes('update-news-v36.mjs'));assert.ok(workflow.includes("NEWS_MAX_PER_SOURCE: '45'"));assert.ok(workflow.includes("NEWS_MAX_STORIES: '60'"))});
test('News client sorts newest first and merges deep recovery seed with automated feed',()=>{const dateSort='new Date(b.publishedAt||0)-new Date(a.publishedAt||0)';assert.ok(newsData.includes(dateSort));assert.ok(newsData.includes("BUILD='36.0.1'"));assert.ok(newsData.includes('/api/news?limit=60'));assert.ok(newsData.includes("readStatic('data/news.json')"));assert.ok(newsData.includes("readStatic('data/news-v36-seed.json')"));assert.ok(newsData.includes('x.mediaQuery||x.title'))});
test('Reader exposes deep coverage instead of only a shallow summary',()=>{assert.ok(newsUi.includes('slice(0,10)'));assert.ok(newsUi.includes('fatos reunidos'));assert.ok(newsUi.includes('fontes cruzadas'));assert.ok(newsUi.includes('COBERTURA'));assert.ok(newsUi.includes('conteúdo completo disponível nas fontes'));assert.equal(newsUi.includes('Ler na fonte'),false);assert.equal(newsUi.includes('window.open('),false);assert.ok(newsCss.includes('clamp(34px,4vw,52px)'))});
test('current deep seed contains substantive JBox articles while automated V36 takes over',()=>{assert.equal(seed.language,'pt-BR');assert.equal(seed.collectorVersion,36);assert.ok(seed.items.length>=5);assert.ok(seed.items.every(x=>x.slug&&x.title&&x.summary&&x.language==='pt-BR'));assert.ok(seed.items.every(x=>Number(x.wordCount||0)>=350));assert.ok(seed.items.every(x=>(x.facts||[]).length>=8));assert.ok(seed.items.every(x=>(x.contentSections||[]).length>=4));assert.ok(seed.items.some(x=>Number(x.wordCount||0)>=500))});
test('generated feed remains internal Portuguese during transition',()=>{assert.equal(feed.language,'pt-BR');assert.ok(Number(feed.collectorVersion)>=35);assert.ok(feed.items.length>=6);assert.ok(feed.items.every(x=>x.slug&&x.title&&x.summary&&x.language==='pt-BR'));if(Number(feed.collectorVersion)>=36){assert.ok(feed.items.some(x=>Number(x.wordCount||0)>=150));assert.ok(feed.items.some(x=>(x.contentSections||[]).length>=3));assert.ok(feed.items.every(x=>x.coverage))}});

if(process.exitCode)throw new Error('AniNexus V36 tests failed');
console.log(`\nAniNexus V36: ${passed} tests passed`);
