import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8'),exists=p=>fs.existsSync(path.join(root,p));let passed=0,failed=0;
function test(name,fn){try{fn();passed++;console.log(`✓ ${name}`)}catch(err){failed++;console.error(`✗ ${name}\n  ${err.message}`)}}
function ok(v,msg='assertion failed'){if(!v)throw new Error(msg)}function inc(t,n){ok(t.includes(n),`missing ${n}`)}function not(t,n){ok(!t.includes(n),`unexpected ${n}`)}
const index=read('index.html'),actions=read('preview-v39/media-actions-v39.js'),css=read('preview-v39/media-actions-v39.css'),activity=read('preview-v40/activity-v40.js'),community=read('preview-v40/community-v40.js'),communityCss=read('preview-v40/community-v40.css'),homeBridge=read('preview-v40/home-community-v40.js');
const mediaState=read('preview-v19/media-state-v2.js'),mediaSync=read('preview-v39/media-sync-v39.js'),catalog=read('preview-v20/catalog-v20.js'),schedule=read('preview-v18/schedule.js'),season=read('preview-v8/app.js'),library=read('preview-v38/library-v38.js');
const home=read('preview-v35/home-v35.js'),news=read('preview-v35/news-data-v35.js'),updater=read('scripts/update-news-v36.mjs'),worker=read('lib/news-worker-v37.mjs'),docker=read('Dockerfile');
test('V40 shell is active',()=>{inc(index,'2026-08-24-v40.2.0');inc(index,'media-actions-v39.js?v=40.0.2');inc(index,'media-actions-v39.css?v=40.0.2');inc(index,'media-state-v2.js?v=40.0.3');inc(index,'media-sync-v39.js?v=40.0.0')});
test('one action controller covers all live card families',()=>{['data-fav','data-nx-fav','data-nx18-fav','data-list','data-nx-list','data-nx18-status'].forEach(x=>inc(actions,x));inc(actions,"window.addEventListener('click'");inc(actions,'stopImmediatePropagation');inc(actions,'a.favorite(id,!a.isFavorite(id))');inc(actions,'a.open(id)');inc(actions,"b.dataset.nxActionOwner='global'");inc(catalog,'data-list=');inc(schedule,'data-nx18-status');inc(season,'data-nx-list');inc(library,'data-list=')});
test('media controls remain 34px circular and resilient to bursts',()=>{inc(css,'--nx39-action-size:34px');inc(css,'button[data-nx-action-kind="compact"]');inc(css,'border-radius:50%');inc(actions,"button.dataset.nxActionKind=labeled?'labeled':'compact'");inc(actions,'favLock');inc(actions,'now()-last<340');inc(actions,'listOpening');inc(actions,"window.addEventListener('dblclick'")});
test('state and account sync remain independent',()=>{['PLANNING','CURRENT','COMPLETED','PAUSED','DROPPED'].forEach(x=>inc(mediaState,`${x}:`));inc(mediaSync,'while(favDesired.has(id))');inc(mediaSync,'while(stateDesired.has(id))')});
test('list changes create durable community activity',()=>{inc(activity,'aninexus:community:activity:v40');inc(activity,'aninexus:media-state-changed');inc(activity,'aninexus:community-activity-changed')});
test('dedicated Community V40 has real social feeds',()=>{['Atividade','Impressões','Discussões','Nova discussão'].forEach(x=>inc(community,x));inc(community,'localActivity()');inc(community,"/api/community/impressions?limit=24");inc(communityCss,'.nx40-feed');not(community,'O que você está assistindo hoje?')});
test('Home now consumes shared community activity',()=>{inc(home,'nx35CommunityHero');inc(homeBridge,'AniNexusCommunityActivity?.local');inc(homeBridge,'aninexus:community-activity-changed')});
test('Home catalog schedule and library product layers remain present',()=>{inc(home,'nx18-card');inc(catalog,'nx21-card');inc(schedule,'nx18-card');inc(library,'nx38-library-card')});
test('news resilient auto-update remains present',()=>{inc(news,'/api/news?limit=60');inc(updater,'NEWS_STALE_GRACE_DAYS');inc(worker,'cleanup({archive:hasHealthyContent})')});
test('production still builds the complete frontend',()=>{inc(docker,'node scripts/build-public.mjs');not(docker,'COPY --chown=node:node preview-v6 ./public/preview-v6')});
test('critical V40 files exist',()=>['preview-v39/media-actions-v39.js','preview-v39/media-actions-v39.css','preview-v39/media-sync-v39.js','preview-v40/activity-v40.js','preview-v40/community-v40.js','preview-v40/community-v40.css','preview-v40/home-community-v40.js'].forEach(p=>ok(exists(p),`missing ${p}`)));
console.log(`\nAniNexus V40 smoke: ${passed} passed, ${failed} failed`);if(failed)process.exit(1);
