import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
const root=process.cwd(),read=p=>fs.readFileSync(path.join(root,p),'utf8'),exists=p=>fs.existsSync(path.join(root,p));let passed=0,failed=0;
function test(name,fn){try{fn();passed++;console.log(`✓ ${name}`)}catch(err){failed++;console.error(`✗ ${name}\n  ${err.message}`)}}function ok(v,msg='assertion failed'){if(!v)throw new Error(msg)}function includes(t,n,m){ok(t.includes(n),m||`missing ${n}`)}function notIncludes(t,n,m){ok(!t.includes(n),m||`unexpected ${n}`)}
const index=read('index.html'),guard=read('preview-v24/home-guard-v24.js'),home=read('preview-v35/home-v35.js'),homeCss=read('preview-v35/home-v35.css'),newsData=read('preview-v35/news-data-v35.js'),newsUi=read('preview-v35/news-ui-v35.js'),newsMediaCss=read('preview-v36/news-v36.css'),source=read('lib/news-sources-v36.mjs'),rich=read('lib/news-rich-v37.mjs'),sourceShim=read('lib/news-sources-v34.mjs'),worker=read('lib/news-worker-v37.mjs'),native=read('lib/native-news.mjs'),detail=read('preview-v22/detail-stable-v22.js'),detailCss=read('preview-v22/detail-v22.css'),mediaState=read('preview-v19/media-state-v2.js'),catalog=read('preview-v20/catalog-v20.js'),schedule=read('preview-v18/schedule.js'),season=read('preview-v8/app.js'),feed=JSON.parse(read('data/news.json'));

test('index cache-busts media-rich news V37',()=>{includes(index,'2026-08-22-v37.0.0');includes(index,'preview-v35/news-data-v35.js?v=37.0.0');includes(index,'preview-v35/news-ui-v35.js?v=37.0.0');includes(index,'preview-v33/news-v33.css?v=37.0.0');notIncludes(index,'preview-v28/home-v28.js')});
test('Home boot prevents old-frame flash',()=>{includes(guard,'__NX35_HOME_BOOT__');includes(guard,'__nx35_home_boot__');includes(homeCss,'html.nx35-home-boot #app')});
test('Home has no mutation-observer repaint loop',()=>{notIncludes(home,'MutationObserver');includes(home,'setInterval(updateCountdowns,1000)')});
test('Home uses exact Programação card classes',()=>['nx18-card','nx18-cover','nx18-info','nx18-air','nx18-countdown','nx18-stream','nx18-provider-logo','nx18-episode'].forEach(x=>includes(home,x)));
test('Home community remains media-rich',()=>['mediaByIds','banner(m)','nx35-community-cover',"PAUSED:{verb:'pausou'","COMPLETED:{verb:'terminou'"].forEach(x=>includes(home,x)));
test('Home rails keep gentle directional fades',()=>{includes(home,'scrollWidth-el.clientWidth');includes(homeCss,'.nx35-edge[data-left="1"]:before');includes(homeCss,'.nx35-edge[data-right="1"]:after');includes(homeCss,'scroll-behavior:smooth')});

test('deep news collector still reads JBox WordPress body',()=>{includes(source,'/wp-json/wp/v2/posts?per_page=50');includes(source,'blocks.length>=46');includes(source,'splitFacts(paragraphs,28)');includes(source,'uniqueFacts');includes(source,'coverage:{facts:facts.length')});
test('V37 media collector reads source images and official embeds',()=>{includes(rich,'MAX_MEDIA=12');includes(rich,'jsonLdImages');includes(rich,'og:image');includes(rich,'mediaGallery:all');includes(rich,'mediaEmbeds:embeds');includes(rich,'youtube-nocookie.com/embed')});
test('worker is routed to V37 and persists full detail plus media',()=>{includes(sourceShim,"from './news-rich-v37.mjs'");includes(worker,'splitFacts(a.facts||[],32)');includes(worker,'mediaGallery:a.mediaGallery');includes(worker,'mediaEmbeds:a.mediaEmbeds');includes(worker,'coverage:a.coverage');includes(worker,'MAX_STORIES');includes(worker,"language='pt-BR'");includes(native,"language='pt-BR'")});
test('news client is newest-first and exposes rich coverage and only live categories',()=>{includes(newsData,"BUILD='37.0.0'");includes(newsData,'new Date(b.publishedAt||0)-new Date(a.publishedAt||0)');includes(newsData,'mediaGallery:gallery');includes(newsData,'/api/news?limit=60');includes(newsUi,'slice(0,14)');includes(newsUi,'liveCategories');includes(newsUi,'Galeria da matéria');includes(newsUi,'Assista sem sair do AniNexus');includes(newsUi,'COBERTURA');includes(newsMediaCss,'.nx37-gallery');notIncludes(newsUi,'Ler na fonte');notIncludes(newsUi,'window.open(')});
test('feed remains internal Portuguese during automatic migration',()=>{ok(feed.language==='pt-BR');ok(feed.items.length>=6);ok(feed.items.every(x=>x.slug&&x.title&&x.summary))});

test('anime detail contracts remain intact',()=>{includes(detail,'https://www.youtube-nocookie.com/embed/');['LANÇAMENTO','TÉRMINO','Personagens','Franquia e relações','Recomendações'].forEach(x=>includes(detail,x));includes(detailCss,'aspect-ratio:16/9')});
test('shared media state remains unified',()=>{['PLANNING','CURRENT','COMPLETED','PAUSED','DROPPED'].forEach(x=>includes(mediaState,`${x}:`));includes(catalog,'data-list=');includes(catalog,'data-fav=');ok(/data-nx18-(?:status|fav)/.test(schedule));ok(/data-nx-(?:list|fav)/.test(season))});
test('critical V37 files exist',()=>['lib/news-sources-v36.mjs','lib/news-rich-v37.mjs','lib/news-worker-v37.mjs','scripts/update-news-v36.mjs','preview-v35/news-data-v35.js','preview-v35/news-ui-v35.js','preview-v36/news-v36.css','tests/news-system.mjs'].forEach(p=>ok(exists(p),`missing ${p}`)));
console.log(`\nAniNexus V37 smoke: ${passed} passed, ${failed} failed`);if(failed)process.exit(1);
