'use strict';
(() => {
  const root=document.querySelector('#app');if(!root)return;
  const API='https://graphql.anilist.co';
  const JIKAN='https://api.jikan.moe/v4';
  const IS_PAGES=location.hostname.endsWith('github.io');
  const BASE=IS_PAGES?'/AniNexus':'';
  const BUILD='23.0.0';
  const CACHE_TTL=20*60*1000;
  let token=0,currentId=0,media=null,extras=null,jikan=null,activeTab='geral';

  const SVG={back:'<svg viewBox="0 0 24 24"><path d="m15 5-7 7 7 7"/></svg>',plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',heart:'<svg viewBox="0 0 24 24"><path d="M20.5 8.8c0 5-8.5 10-8.5 10s-8.5-5-8.5-10A4.6 4.6 0 0 1 12 6.4a4.6 4.6 0 0 1 8.5 2.4Z"/></svg>',star:'<svg viewBox="0 0 24 24"><path d="m12 3 2.8 5.5 6.1.9-4.4 4.3 1 6.1-5.5-2.9-5.5 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z"/></svg>',clock:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3.5 2"/></svg>',share:'<svg viewBox="0 0 24 24"><circle cx="18" cy="5" r="2.5"/><circle cx="6" cy="12" r="2.5"/><circle cx="18" cy="19" r="2.5"/><path d="m8.2 10.8 7.5-4.4M8.2 13.2l7.5 4.4"/></svg>',external:'<svg viewBox="0 0 24 24"><path d="M13 5h6v6M19 5l-8 8"/><path d="M11 7H5v12h12v-6"/></svg>',play:'<svg viewBox="0 0 24 24"><path d="m9 6 9 6-9 6V6Z"/></svg>'};
  const FORMAT={TV:'Série',TV_SHORT:'Série curta',MOVIE:'Filme',OVA:'OVA',ONA:'ONA',SPECIAL:'Especial',MUSIC:'Música'};
  const STATUS={RELEASING:'Em exibição',FINISHED:'Finalizado',NOT_YET_RELEASED:'Ainda não lançado',HIATUS:'Em hiato',CANCELLED:'Cancelado'};
  const SOURCE={MANGA:'Mangá',LIGHT_NOVEL:'Light novel',ORIGINAL:'Original',NOVEL:'Novel',GAME:'Jogo',VISUAL_NOVEL:'Visual novel',WEB_NOVEL:'Web novel',OTHER:'Outra mídia'};
  const SEASON={WINTER:'Inverno',SPRING:'Primavera',SUMMER:'Verão',FALL:'Outono'};
  const COUNTRY={JP:'Japão',KR:'Coreia do Sul',CN:'China',TW:'Taiwan',US:'Estados Unidos',FR:'França'};
  const GENRE={Action:'Ação',Adventure:'Aventura',Comedy:'Comédia',Drama:'Drama',Fantasy:'Fantasia',Horror:'Terror',Mystery:'Mistério',Romance:'Romance','Sci-Fi':'Ficção Científica','Slice of Life':'Cotidiano',Sports:'Esportes',Supernatural:'Sobrenatural',Thriller:'Suspense',Psychological:'Psicológico',Music:'Música',Mecha:'Mecha'};
  const REL={ADAPTATION:'Adaptação',PREQUEL:'Prequela',SEQUEL:'Sequência',PARENT:'Obra principal',SIDE_STORY:'História paralela',SUMMARY:'Resumo',ALTERNATIVE:'Alternativa',SPIN_OFF:'Spin-off',SOURCE:'Fonte',COMPILATION:'Compilação',CONTAINS:'Contém',OTHER:'Relacionado'};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const strip=v=>{const d=document.createElement('div');d.innerHTML=String(v||'');return(d.textContent||'').replace(/\s+/g,' ').trim()};
  const title=m=>m?.title?.english||m?.title?.userPreferred||m?.title?.romaji||m?.title?.native||'Anime';
  const image=m=>m?.coverImage?.extraLarge||m?.coverImage?.large||`${BASE}/assets/logo.png`;
  const banner=m=>m?.bannerImage||image(m);
  const score=m=>m?.averageScore?String((m.averageScore/10).toFixed(1)).replace('.0',''):'—';
  const compact=n=>n?new Intl.NumberFormat('pt-BR',{notation:'compact',maximumFractionDigits:1}).format(Number(n)):'—';
  const slug=s=>String(s||'anime').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,80)||'anime';

  function requestedPath(){if(window.__NX_DETAIL_V23_BOOT__)return window.__NX_DETAIL_V23_BOOT__;try{const u=new URL(location.href),p=u.searchParams.get('p');if(p)return p.split('?')[0].replace(/\/+$/,'')||'/';let x=u.pathname;if(IS_PAGES)x=x.replace(/^\/AniNexus/,'')||'/';return x.replace(/\/+$/,'')||'/'}catch{return'/'}}
  function restoreBoot(){const p=window.__NX_DETAIL_V23_BOOT__;if(!p)return;history.replaceState({},'',IS_PAGES?`${BASE}/?build=${BUILD}&p=${encodeURIComponent(p)}`:p);delete window.__NX_DETAIL_V23_BOOT__;document.documentElement.classList.remove('nx23-detail-boot')}
  function animeId(){const m=requestedPath().match(/^\/anime\/.+-(\d+)$/);return m?Number(m[1]):0}
  function pagesUrl(path){return `${BASE}/?build=${BUILD}&p=${encodeURIComponent(path)}`}
  function fmtDate(d){if(!d?.year)return'—';const x=new Date(Date.UTC(+d.year,Math.max(0,+(d.month||1)-1),+(d.day||1),12));return new Intl.DateTimeFormat('pt-BR',{day:d.day?'2-digit':undefined,month:d.month?'short':undefined,year:'numeric',timeZone:'UTC'}).format(x).replace('.','')}
  function until(ts){const ms=Number(ts||0)*1000-Date.now();if(ms<=0)return'Em instantes';const d=Math.floor(ms/864e5),h=Math.floor(ms%864e5/36e5),m=Math.floor(ms%36e5/6e4);return d?`${d}d ${h}h ${m}min`:`${h}h ${m}min`}
  function activate(id){currentId=id;document.body.classList.add('nx23-detail-active');document.body.classList.remove('nx22-detail-active','nx-detail-active','nx-season-active','nx22-news-active');document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav==='anime'))}
  function deactivate(){document.body.classList.remove('nx23-detail-active');currentId=0}

  async function gql(q,v){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({query:q,variables:v})});if(!r.ok)throw new Error(`Falha ao carregar (${r.status})`);const j=await r.json();if(j.errors?.length)throw new Error(j.errors[0]?.message||'Falha ao consultar o anime');return j.data}
  const CORE=`id idMal title{romaji english native userPreferred} synonyms coverImage{extraLarge large color} bannerImage description genres tags{name rank isMediaSpoiler} averageScore meanScore popularity favourites episodes duration format status season seasonYear countryOfOrigin source startDate{year month day} endDate{year month day} studios(isMain:true){nodes{id name}} nextAiringEpisode{airingAt episode timeUntilAiring} trailer{id site thumbnail} externalLinks{site url type icon color}`;
  async function fetchCore(id){const d=await gql(`query($id:Int){Media(id:$id,type:ANIME){${CORE}}}`,{id});if(!d?.Media)throw new Error('Anime não encontrado');return d.Media}
  async function fetchExtras(id){const q=`query($id:Int){Media(id:$id,type:ANIME){characters(perPage:18,sort:[ROLE,RELEVANCE]){edges{role node{id name{full native} image{large medium}}}} staff(perPage:18,sort:[RELEVANCE]){edges{role node{id name{full native} image{large medium}}}} relations{edges{relationType node{id format status seasonYear averageScore title{romaji english native userPreferred} coverImage{extraLarge large}}}} recommendations(perPage:10,sort:RATING_DESC){nodes{rating mediaRecommendation{id format status seasonYear averageScore title{romaji english native userPreferred} coverImage{extraLarge large}}}}}}`;try{return(await gql(q,{id}))?.Media||{}}catch{return{}}}
  async function fetchJikan(id){if(!id)return null;try{const r=await fetch(`${JIKAN}/anime/${id}/full`,{headers:{accept:'application/json'}});if(!r.ok)return null;return(await r.json())?.data||null}catch{return null}}
  function cacheRead(id){try{const x=JSON.parse(sessionStorage.getItem(`nx23:core:${id}`)||'null');if(x&&Date.now()-x.t<CACHE_TTL&&x.data?.id)return x.data}catch{}return null}
  function cacheWrite(id,data){try{sessionStorage.setItem(`nx23:core:${id}`,JSON.stringify({t:Date.now(),data}))}catch{}}

  function generatedSynopsis(m){const g=(m.genres||[]).slice(0,3).map(x=>GENRE[x]||x).join(', ');return `${title(m)} é ${m.format==='MOVIE'?'um filme':'um anime'}${g?` de ${g}`:''}${m.source?`, baseado em ${SOURCE[m.source]||String(m.source).toLowerCase()}`:''}. A descrição completa em português está sendo carregada.`}
  async function translatePT(raw){raw=strip(raw);if(!raw)return'';const key='nx23:pt:'+btoa(unescape(encodeURIComponent(raw.slice(0,120)))).replace(/=/g,'').slice(0,80);try{const c=localStorage.getItem(key);if(c)return c}catch{}try{const u=`https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=pt&dt=t&q=${encodeURIComponent(raw.slice(0,3800))}`;const r=await fetch(u);if(!r.ok)return'';const j=await r.json(),x=(j?.[0]||[]).map(v=>v?.[0]||'').join('').trim();if(x){try{localStorage.setItem(key,x)}catch{}return x}}catch{}return''}
  async function hydrateSynopsis(m){const el=root.querySelector('#nx23Synopsis');if(!el)return;const pt=await translatePT(m.description);if(el&&currentId===m.id)el.textContent=pt||generatedSynopsis(m)}

  function filterButton(type,value,label,cls=''){return `<button type="button" class="nx23-chip ${cls}" data-nx23-filter="${esc(type)}" data-value="${esc(value)}">${esc(label)}</button>`}
  function goCatalog(type,value){try{sessionStorage.setItem('nx23:catalog:incoming',JSON.stringify({[type]:value}))}catch{}const p='/animes/catalogo';location.assign(IS_PAGES?pagesUrl(p):p)}
  function openAnime(m){if(!m?.id)return;const p=`/anime/${slug(title(m))}-${m.id}`;location.assign(IS_PAGES?pagesUrl(p):p)}
  function officialLinks(m){return (m.externalLinks||[]).filter(x=>x.url&&String(x.type||'').toUpperCase()!=='STREAMING').slice(0,6)}
  function infoRows(m,j){const studios=(m.studios?.nodes||[]).map(x=>x.name).filter(Boolean).join(', ')||'—';const rows=[['Origem',COUNTRY[m.countryOfOrigin]||m.countryOfOrigin||'—'],['Tipo',FORMAT[m.format]||m.format||'—'],['Episódios',m.episodes||j?.episodes||'—'],['Duração',m.duration?`${m.duration} min`:j?.duration||'—'],['Ano',m.seasonYear||m.startDate?.year||'—'],['Temporada',m.season?SEASON[m.season]||m.season:'—'],['Início',fmtDate(m.startDate)],['Término',fmtDate(m.endDate)],['Status',STATUS[m.status]||'—'],['Classificação',j?.rating||'—'],['Baseado em',SOURCE[m.source]||m.source||'—'],['Estúdios',studios]];return rows.map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}
  function people(edges,staff=false){return (edges||[]).map(e=>{const n=e.node||{};return `<article class="nx23-person"><img loading="lazy" src="${esc(n.image?.large||n.image?.medium||BASE+'/assets/logo.png')}" alt=""><strong>${esc(n.name?.full||'')}</strong><span>${esc(staff?(e.role||'Equipe'):(e.role==='MAIN'?'Principal':'Coadjuvante'))}</span></article>`}).join('')}
  function relationCards(edges){return (edges||[]).filter(e=>e.node).map(e=>{const m=e.node;return `<article class="nx23-related" data-nx23-open="${m.id}" data-title="${esc(title(m))}"><img loading="lazy" src="${esc(image(m))}" alt=""><div><small>${esc(REL[e.relationType]||'Relacionado')}</small><strong>${esc(title(m))}</strong><span>${esc([FORMAT[m.format]||m.format,m.seasonYear].filter(Boolean).join(' · '))}</span></div></article>`}).join('')}
  function recCards(nodes){return (nodes||[]).filter(x=>x.mediaRecommendation).map(x=>{const m=x.mediaRecommendation;return `<article class="nx23-rec" data-nx23-open="${m.id}" data-title="${esc(title(m))}"><div><img loading="lazy" src="${esc(image(m))}" alt="">${m.averageScore?`<span>${SVG.star}${score(m)}</span>`:''}</div><strong>${esc(title(m))}</strong><small>${esc([FORMAT[m.format]||m.format,m.seasonYear].filter(Boolean).join(' · '))}</small></article>`}).join('')}
  function loaderCards(n=6){return `<div class="nx23-inline-loading">${Array.from({length:n},()=>'<i></i>').join('')}</div>`}

  function hero(m){
    const yr=m.seasonYear||m.startDate?.year||'';
    const tags=(m.tags||[]).filter(t=>!t.isMediaSpoiler&&(t.rank||0)>=55).slice(0,8);
    return `<section class="nx23-hero"><div class="nx23-bg"><img src="${esc(banner(m))}" alt=""></div><div class="nx23-shade"></div><div class="nx23-shell nx23-hero-inner"><button class="nx23-back" data-nx23-back>${SVG.back}<span>Voltar</span></button><div class="nx23-cover"><img src="${esc(image(m))}" alt="${esc(title(m))}"></div><div class="nx23-copy"><span class="nx23-alt">${esc(m.title?.romaji||m.title?.native||'')}</span><h1>${esc(title(m))}</h1><div class="nx23-chips"><span class="nx23-chip static">${esc(STATUS[m.status]||'Anime')}</span>${filterButton('format',m.format,FORMAT[m.format]||m.format||'Anime','format')}${yr?filterButton('year',yr,String(yr),'year'):''}${(m.genres||[]).slice(0,5).map(g=>filterButton('genre',g,GENRE[g]||g,'genre')).join('')}</div>${tags.length?`<div class="nx23-tags">${tags.map(t=>`<span>${esc(t.name)}</span>`).join('')}</div>`:''}<div class="detail-actions nx23-actions"><button class="btn nx23-list" data-list="${m.id}">${SVG.plus}<span>Adicionar à lista</span></button><button class="nx23-fav" data-fav="${m.id}" aria-label="Favoritar">${SVG.heart}</button><button class="nx23-share" data-nx23-share>${SVG.share}<span>Compartilhar</span></button></div><div class="nx23-stats"><div><strong>${score(m)}</strong><span>nota média</span></div><div><strong>${compact(m.popularity)}</strong><span>popularidade</span></div><div><strong>${compact(m.favourites)}</strong><span>favoritos</span></div></div></div></div></section>`
  }
  function quick(m){return `<div class="nx23-quick"><article><small>LANÇAMENTO</small><strong>${esc(fmtDate(m.startDate))}</strong></article><article><small>TÉRMINO</small><strong>${esc(fmtDate(m.endDate))}</strong></article><article><small>EPISÓDIOS</small><strong>${esc(m.episodes||'—')}</strong></article><article><small>STATUS</small><strong>${esc(STATUS[m.status]||'—')}</strong></article></div>`}
  function generalPanel(){if(!media)return'';const m=media,stream=(m.externalLinks||[]).filter(x=>String(x.type||'').toUpperCase()==='STREAMING'&&x.url),trailer=m.trailer?.id&&String(m.trailer.site||'').toLowerCase()==='youtube'?m.trailer.id:'',links=officialLinks(m);return `<div class="nx23-layout"><main>${m.nextAiringEpisode?`<section class="nx23-next">${SVG.clock}<div><small>PRÓXIMO EPISÓDIO</small><strong>Episódio ${m.nextAiringEpisode.episode}</strong><span>${until(m.nextAiringEpisode.airingAt)}</span></div></section>`:''}<section class="nx23-section"><header><div><small>HISTÓRIA</small><h2>Sinopse</h2></div><span>sempre em português</span></header><p class="nx23-synopsis" id="nx23Synopsis">${esc(generatedSynopsis(m))}</p></section>${trailer?`<section class="nx23-section"><header><div><small>VÍDEO</small><h2>Trailer oficial</h2></div></header><div class="nx23-video"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(trailer)}?rel=0&modestbranding=1" title="Trailer de ${esc(title(m))}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div></section>`:''}${stream.length?`<section class="nx23-section"><header><div><small>STREAMING</small><h2>Onde assistir</h2></div></header><div class="nx23-streams">${stream.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${s.icon?`<img src="${esc(s.icon)}" alt="">`:SVG.play}<span>${esc(s.site||'Streaming')}</span>${SVG.external}</a>`).join('')}</div></section>`:''}<section class="nx23-section"><header><div><small>ELENCO</small><h2>Personagens</h2></div><button data-nx23-tab-jump="personagens">ver todos</button></header><div id="nx23PeoplePreview" class="nx23-people">${extras?.characters?.edges?.length?people(extras.characters.edges.slice(0,12)):loaderCards()}</div></section><section class="nx23-section"><header><div><small>PRODUÇÃO</small><h2>Equipe principal</h2></div><button data-nx23-tab-jump="equipe">ver equipe</button></header><div id="nx23StaffPreview" class="nx23-people">${extras?.staff?.edges?.length?people(extras.staff.edges.slice(0,10),true):loaderCards()}</div></section></main><aside><h3>Informações</h3><div class="nx23-info" id="nx23Info">${infoRows(m,jikan)}</div><h3>Outros títulos</h3><div class="nx23-info"><div><span>Romaji</span><strong>${esc(m.title?.romaji||'—')}</strong></div><div><span>Japonês</span><strong>${esc(m.title?.native||'—')}</strong></div><div><span>Inglês</span><strong>${esc(m.title?.english||'—')}</strong></div>${(m.synonyms||[]).slice(0,2).map(s=>`<div><span>Alternativo</span><strong>${esc(s)}</strong></div>`).join('')}</div>${links.length?`<h3>Links oficiais</h3><div class="nx23-links">${links.map(l=>`<a href="${esc(l.url)}" target="_blank" rel="noopener noreferrer"><span>${esc(l.site||'Site')}</span>${SVG.external}</a>`).join('')}</div>`:''}</aside></div>`}
  function charactersPanel(){if(!extras)return `<section class="nx23-full"><h2>Personagens</h2>${loaderCards(10)}</section>`;return `<section class="nx23-full"><div class="nx23-section-title"><small>PERSONAGENS</small><h2>Elenco</h2></div><div class="nx23-people nx23-people-full">${people(extras.characters?.edges||[])||'<p>Sem personagens disponíveis.</p>'}</div></section>`}
  function staffPanel(){if(!extras)return `<section class="nx23-full"><h2>Equipe</h2>${loaderCards(10)}</section>`;return `<section class="nx23-full"><div class="nx23-section-title"><small>PRODUÇÃO</small><h2>Equipe</h2></div><div class="nx23-people nx23-people-full">${people(extras.staff?.edges||[],true)||'<p>Sem equipe disponível.</p>'}</div></section>`}
  function franchisePanel(){if(!extras)return `<section class="nx23-full"><h2>Franquia</h2>${loaderCards(6)}</section>`;return `<section class="nx23-full"><div class="nx23-section-title"><small>UNIVERSO</small><h2>Franquia e relações</h2></div><div class="nx23-related-grid">${relationCards(extras.relations?.edges||[])||'<p>Não há relações cadastradas.</p>'}</div></section>`}
  function recPanel(){if(!extras)return `<section class="nx23-full"><h2>Recomendações</h2>${loaderCards(8)}</section>`;return `<section class="nx23-full"><div class="nx23-section-title"><small>PARA ASSISTIR DEPOIS</small><h2>Recomendações</h2></div><div class="nx23-rec-grid">${recCards(extras.recommendations?.nodes||[])||'<p>Sem recomendações disponíveis agora.</p>'}</div></section>`}
  const panels={geral:generalPanel,personagens:charactersPanel,equipe:staffPanel,franquia:franchisePanel,recomendacoes:recPanel};
  function paintPanel(tab=activeTab){activeTab=tab;root.querySelectorAll('[data-nx23-tab]').forEach(b=>b.classList.toggle('active',b.dataset.nx23Tab===tab));const host=root.querySelector('#nx23Panel');if(host)host.innerHTML=(panels[tab]||generalPanel)();if(tab==='geral')hydrateSynopsis(media)}

  function shell(m){activate(m.id);media=m;extras=null;jikan=null;activeTab='geral';root.innerHTML=`<article class="nx23-detail">${hero(m)}<nav class="nx23-tabs"><div class="nx23-shell"><button class="active" data-nx23-tab="geral">Geral</button><button data-nx23-tab="personagens">Personagens</button><button data-nx23-tab="equipe">Equipe</button><button data-nx23-tab="franquia">Franquia</button><button data-nx23-tab="recomendacoes">Recomendações</button></div></nav><div class="nx23-shell nx23-content">${quick(m)}<div id="nx23Panel"></div></div></article>`;paintPanel('geral');window.AniNexusMediaState?.sync?.(m.id);document.title=`${title(m)} | AniNexus`}
  function loading(id){activate(id);root.innerHTML=`<article class="nx23-detail nx23-loading"><div class="nx23-loading-banner"></div><div class="nx23-shell nx23-loading-row"><div></div><section><i></i><i></i><i></i><p>Carregando o anime…</p></section></div></article>`}
  function fail(id,e){activate(id);root.innerHTML=`<article class="nx23-detail nx23-fail"><div><img src="${BASE}/assets/logo.png" alt=""><h1>Não foi possível carregar este anime</h1><p>${esc(e?.message||'Falha de conexão.')}</p><button data-nx23-retry>Tentar novamente</button></div></article>`}

  async function render(force=false){const id=animeId();if(!id){deactivate();return}const mine=++token;let core=!force?cacheRead(id):null;if(!core)loading(id);try{if(!core){core=await fetchCore(id);cacheWrite(id,core)}if(mine!==token||animeId()!==id)return;shell(core);const extraP=fetchExtras(id).then(x=>{if(mine!==token||animeId()!==id)return;extras=x;if(activeTab==='geral'||activeTab==='personagens'||activeTab==='equipe'||activeTab==='franquia'||activeTab==='recomendacoes')paintPanel(activeTab)});const jP=fetchJikan(core.idMal).then(x=>{if(mine!==token||animeId()!==id)return;jikan=x;const info=root.querySelector('#nx23Info');if(info)info.innerHTML=infoRows(core,jikan)});await Promise.allSettled([extraP,jP])}catch(e){if(mine===token&&animeId()===id)fail(id,e)}}

  root.addEventListener('click',e=>{
    const back=e.target.closest('[data-nx23-back]');if(back){history.length>1?history.back():location.assign(IS_PAGES?pagesUrl('/animes/catalogo'):'/animes/catalogo');return}
    const tab=e.target.closest('[data-nx23-tab]');if(tab){paintPanel(tab.dataset.nx23Tab);return}
    const jump=e.target.closest('[data-nx23-tab-jump]');if(jump){paintPanel(jump.dataset.nx23TabJump);root.querySelector('.nx23-tabs')?.scrollIntoView({behavior:'smooth',block:'start'});return}
    const filter=e.target.closest('[data-nx23-filter]');if(filter){goCatalog(filter.dataset.nx23Filter,filter.dataset.value);return}
    const open=e.target.closest('[data-nx23-open]');if(open){const id=Number(open.dataset.nx23Open),t=open.dataset.title||'anime';openAnime({id,title:{userPreferred:t}});return}
    const share=e.target.closest('[data-nx23-share]');if(share){(async()=>{try{if(navigator.share)await navigator.share({title:title(media),url:location.href});else await navigator.clipboard.writeText(location.href)}catch{}})();return}
    const retry=e.target.closest('[data-nx23-retry]');if(retry){render(true);return}
  });

  addEventListener('popstate',()=>setTimeout(render,0));document.addEventListener('aninexus:routechange',()=>setTimeout(render,0));
  restoreBoot();render();
})();