'use strict';
(() => {
  if(window.AniNexusDiary)return;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pageUrl=path=>location.hostname.endsWith('github.io')?'/AniNexus/?p='+encodeURIComponent(path):path;
  const zone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone||'America/Sao_Paulo';
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
  const dateLabel=value=>new Intl.DateTimeFormat('pt-BR',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(value+'T12:00:00Z'));
  const reactions=['Amei','Chorei','Surpreendeu','Divertido','Tenso','Inspirador'];
  let current=null,dialog=null;
  const api=(path,options)=>window.AniNexusAuth.api(path,options);
  const active=state=>current===state&&state.host.isConnected;
  function closeDialog(){if(dialog){dialog.close();dialog.remove();dialog=null;}}
  function openDialog(title,body,trigger){closeDialog();dialog=document.createElement('dialog');dialog.className='nx61-diary-dialog';dialog.setAttribute('aria-labelledby','nx61DiaryDialogTitle');dialog.innerHTML=`<header><h2 id="nx61DiaryDialogTitle">${esc(title)}</h2><button type="button" data-close aria-label="Fechar">×</button></header>${body}`;document.body.append(dialog);const el=dialog;el.querySelector('[data-close]').onclick=()=>closeDialog();el.addEventListener('close',()=>{trigger?.isConnected&&trigger.focus();});el.showModal();return el;}
  function unitLabel(item){if(item.kind==='WORK')return item.completed?'Obra concluída':'Registro da obra';const unit=item.kind==='CHAPTER'?'Capítulo':'Episódio';return `${unit}${item.end_unit!==item.start_unit?'s':''} ${item.start_unit}${item.end_unit!==item.start_unit?'–'+item.end_unit:''}`;}
  function entryMarkup(item){return `<article class="nx61-diary-entry" data-entry="${esc(item.id)}"><header><div><time datetime="${esc(item.entry_date)}">${esc(dateLabel(item.entry_date))}</time><h3>${esc(item.media_snapshot?.title||'Obra')}</h3><p>${esc(unitLabel(item))}${item.rewatch?' · Reassistido / relido':''}</p></div><div class="nx61-diary-entry-tools"><button type="button" data-edit="${esc(item.id)}" aria-label="Editar registro de ${esc(item.media_snapshot?.title)}">Editar</button><button type="button" data-delete="${esc(item.id)}" aria-label="Excluir registro de ${esc(item.media_snapshot?.title)}">Excluir</button></div></header><div class="nx61-diary-facts">${item.score!==null&&item.score!==undefined?`<span>Nota ${esc(String(item.score).replace('.',','))}/10</span>`:''}${item.favorite?'<span>Favorito nesta data</span>':''}${(item.reactions||[]).map(r=>`<span>${esc(r)}</span>`).join('')}</div>${item.note?item.spoiler?`<details><summary>Mostrar anotação com spoiler</summary><p class="nx61-diary-note">${esc(item.note)}</p></details>`:`<p class="nx61-diary-note">${esc(item.note)}</p>`:''}</article>`;}
  function renderRecap(state){const stats=state.recap?.stats;if(!stats)return;const section=state.host.querySelector('[data-diary-recap]');section.innerHTML=`<h2>Resumo do período</h2><p class="nx61-diary-recap-period">${esc(dateLabel(state.loadedPeriod.start))} a ${esc(dateLabel(state.loadedPeriod.end))}</p><div class="nx61-diary-metrics">${[['Animes',stats.anime_works],['Mangás',stats.manga_works],['Episódios',stats.episodes],['Capítulos',stats.chapters],['Tempo registrado',Math.floor(stats.minutes/60)+'h '+stats.minutes%60+'min'],['Média das notas',stats.average_score===null?'—':String(stats.average_score).replace('.',',')]].map(([label,value])=>`<div><strong>${esc(value??0)}</strong><span>${esc(label)}</span></div>`).join('')}</div><p class="nx61-diary-muted">${Number(stats.entries)||0} registros · ${Number(stats.rewatches)||0} reassistidos/releituras · ${Number(stats.completions)||0} conclusões. ${Number(stats.estimated_minutes)||0} minutos são estimados pela duração cadastrada.${Number(stats.without_duration)?` ${Number(stats.without_duration)} registros sem duração.`:''}</p>${stats.genres?.length?`<p class="nx61-diary-muted">Gêneros mais registrados: ${stats.genres.slice(0,3).map(g=>esc(({Fantasy:'Fantasia',Action:'Ação',Adventure:'Aventura',Comedy:'Comédia',Romance:'Romance',Drama:'Drama',Mystery:'Mistério','Sci-Fi':'Ficção científica',Sports:'Esportes',Horror:'Terror',Thriller:'Suspense',Supernatural:'Sobrenatural','Slice of Life':'Cotidiano'})[g.genre]||g.genre)).join(' · ')}.</p>`:''}<button type="button" data-share-recap${stats.entries?'':' disabled'}>Criar card do período</button>`;section.querySelector('[data-share-recap]').onclick=event=>shareCard(state,event.currentTarget);}
  async function load(state,append=false){
    if(!active(state))return;const version=++state.version;const host=state.host,feedback=host.querySelector('[data-diary-feedback]'),more=host.querySelector('[data-diary-more]');
    feedback.textContent=append?'Carregando mais registros...':'Carregando seu diário...';more.disabled=true;if(!append){state.cursor=null;more.hidden=true;}
    const query=new URLSearchParams({start:state.start,end:state.end,timeZone:zone()});if(append&&state.cursor)query.set('cursor',state.cursor);
    try{
      const [data,recap]=await Promise.all([api('/api/me/diary?'+query,{signal:state.controller.signal}),append?Promise.resolve(state.recap):api('/api/me/diary/recap?'+query,{signal:state.controller.signal})]);
      if(!active(state)||version!==state.version)return;
      state.items=append?[...new Map([...state.items,...data.items].map(item=>[item.id,item])).values()]:data.items;state.cursor=data.nextCursor;state.recap=recap;state.loadedPeriod={start:state.start,end:state.end};
      host.querySelector('[data-diary-entries]').innerHTML=state.items.length?state.items.map(entryMarkup).join(''):'<div class="nx61-diary-empty"><strong>Seu diário começa com um registro.</strong><p>Não presumimos as datas da sua biblioteca antiga. Registre o que viu ou leu para construir uma retrospectiva fiel.</p></div>';
      renderRecap(state);feedback.textContent='';more.hidden=!state.cursor;
      host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>entryForm(state,state.items.find(i=>i.id===b.dataset.edit),b));
      host.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeEntry(state,state.items.find(i=>i.id===b.dataset.delete),b));
    }catch(error){if(!active(state)||version!==state.version||state.controller.signal.aborted)return;feedback.textContent=error.status===400?'Confira as datas: o período pode ter até um ano e não pode estar no futuro.':'Não foi possível carregar. Seus registros foram preservados.';const retry=document.createElement('button');retry.type='button';retry.textContent='Tentar novamente';retry.onclick=()=>load(state,append);feedback.append(' ',retry);}
    finally{if(active(state)&&version===state.version)more.disabled=false;}
  }
  async function entryForm(state,item,trigger){
    const editing=!!item,clientKey=crypto.randomUUID();let titles=[],searchGeneration=0;
    const formDialog=openDialog(editing?'Editar registro':'Novo registro',`<form data-diary-form><p class="nx61-diary-muted">Este registro é privado. Ele não altera o progresso, os favoritos ou a nota atual da biblioteca.</p>${editing?`<strong>${esc(item.media_snapshot?.title)}</strong><p>${esc(unitLabel(item))}</p>`:'<label>Buscar na sua biblioteca<input name="search" type="search" maxlength="80" autocomplete="off" placeholder="Nome do anime ou mangá"></label><label>Obra<select aria-label="Obra" name="work" required disabled><option value="">Carregando obras...</option></select></label><p data-title-feedback role="status"></p><label>Tipo de registro<select aria-label="Tipo de registro" name="kind"><option value="EPISODE">Episódios assistidos</option><option value="WORK">Registro da obra</option></select></label><div class="nx61-diary-form-grid" data-unit-fields><label>Do episódio / capítulo<input name="startUnit" type="number" min="1" max="100000" value="1" required></label><label>Até o episódio / capítulo<input name="endUnit" type="number" min="1" max="100000" value="1" required></label></div>'}<div class="nx61-diary-form-grid"><label>Data<input name="date" type="date" required min="1900-01-01" max="${today()}" value="${esc(item?.entry_date||today())}"></label><label>Nota nesta data<input name="score" type="number" step="0.1" min="0" max="10" placeholder="Sem nota" value="${esc(item?.score??'')}"></label></div>${editing?'':'<label>Tempo em minutos (opcional)<input name="minutes" type="number" min="0" max="100000" placeholder="Estimar pela duração dos episódios, se disponível"></label>'}<div class="nx61-diary-checks">${[['favorite','Favorito nesta data'],['rewatch','Reassistido / relido'],['completed','Concluí a obra'],['spoiler','Minha anotação contém spoiler']].map(([key,label])=>`<label><input type="checkbox" name="${key}"${item?.[key]?' checked':''}>${label}</label>`).join('')}</div><fieldset><legend>Como foi? (até 3)</legend><div class="nx61-diary-reactions">${reactions.map(value=>`<label><input type="checkbox" name="reaction" value="${esc(value)}"${item?.reactions?.includes(value)?' checked':''}>${esc(value)}</label>`).join('')}</div></fieldset><label>Anotação<textarea name="note" maxlength="2000" rows="4" placeholder="O que ficou desta experiência?">${esc(item?.note||'')}</textarea></label><p data-form-feedback role="status"></p><footer><button type="button" data-cancel>Cancelar</button><button type="submit">${editing?'Salvar alterações':'Salvar registro'}</button></footer></form>`,trigger);
    const form=formDialog.querySelector('form'),feedback=form.querySelector('[data-form-feedback]');form.querySelector('[data-cancel]').onclick=()=>closeDialog();
    function updateKind(){if(editing)return;const work=titles.find(t=>`${t.media_type}:${t.media_id}`===form.elements.work.value),manga=work?.media_type==='MANGA',selected=form.elements.kind.value;form.elements.kind.innerHTML=`<option value="${manga?'CHAPTER':'EPISODE'}">${manga?'Capítulos lidos':'Episódios assistidos'}</option><option value="WORK">Registro da obra</option>`;if(selected==='WORK')form.elements.kind.value='WORK';updateUnits();}
    function updateUnits(){const hidden=form.elements.kind.value==='WORK';form.querySelector('[data-unit-fields]').hidden=hidden;for(const name of ['startUnit','endUnit'])form.elements[name].disabled=hidden;}
    async function searchTitles(){if(!formDialog.isConnected)return;const ticket=++searchGeneration;try{const data=await api('/api/me/diary/titles?search='+encodeURIComponent(form.elements.search.value),{signal:state.controller.signal});if(!formDialog.isConnected||ticket!==searchGeneration)return;titles=data.items||[];const selected=form.elements.work.value;form.elements.work.innerHTML='<option value="">Selecione uma obra</option>'+titles.map(t=>`<option value="${esc(t.media_type)}:${Number(t.media_id)}">${esc(t.title)} · ${t.media_type==='MANGA'?'Mangá':'Anime'}</option>`).join('');if(titles.some(t=>`${t.media_type}:${t.media_id}`===selected))form.elements.work.value=selected;form.elements.work.disabled=false;form.querySelector('[data-title-feedback]').textContent=titles.length?'':'Nenhuma obra encontrada na sua biblioteca. Adicione uma obra à lista ou procure outro nome.';updateKind();}catch{if(formDialog.isConnected){const f=form.querySelector('[data-title-feedback]');f.textContent='Não foi possível consultar a biblioteca. ';const b=document.createElement('button');b.type='button';b.textContent='Tentar novamente';b.onclick=searchTitles;f.append(b);}}}
    if(!editing){let timer;form.elements.search.addEventListener('input',()=>{clearTimeout(timer);searchGeneration++;timer=setTimeout(searchTitles,300);});form.elements.work.onchange=updateKind;form.elements.kind.onchange=updateUnits;searchTitles();}
    form.onsubmit=async event=>{
      event.preventDefault();const button=form.querySelector('[type=submit]');if(button.disabled)return;const selected=[...form.querySelectorAll('[name=reaction]:checked')].map(e=>e.value);if(selected.length>3){feedback.textContent='Selecione no máximo três reações.';return;}
      const value={date:form.elements.date.value,score:form.elements.score.value===''?null:Number(form.elements.score.value),favorite:form.elements.favorite.checked,rewatch:form.elements.rewatch.checked,completed:form.elements.completed.checked,spoiler:form.elements.spoiler.checked,reactions:selected,note:form.elements.note.value};
      if(!editing){const work=titles.find(t=>`${t.media_type}:${t.media_id}`===form.elements.work.value);if(!work){feedback.textContent='Selecione uma obra da sua biblioteca.';return;}Object.assign(value,{clientKey,mediaId:Number(work.media_id),mediaType:work.media_type,timeZone:zone(),kind:form.elements.kind.value,startUnit:form.elements.kind.value==='WORK'?null:Number(form.elements.startUnit.value),endUnit:form.elements.kind.value==='WORK'?null:Number(form.elements.endUnit.value),minutes:form.elements.minutes.value===''?null:Number(form.elements.minutes.value)});if(value.kind!=='WORK'&&(value.endUnit<value.startUnit||value.endUnit-value.startUnit>=1000)){feedback.textContent='Informe um intervalo válido de até 1.000 episódios ou capítulos.';return;}}
      button.disabled=true;feedback.textContent='Salvando...';
      try{await api('/api/me/diary'+(editing?'/'+item.id:''),{method:editing?'PATCH':'POST',body:JSON.stringify(value),signal:state.controller.signal});if(!active(state))return;if(dialog===formDialog)closeDialog();load(state);}catch(error){if(formDialog.isConnected){feedback.textContent=error.status===409?'Este envio já foi recebido com outros dados. Feche e abra um novo registro.':error.status===422?'Confira a obra, a data, a nota e o intervalo informado.':'Não foi possível salvar. Seu texto continua aqui; tente novamente.';button.disabled=false;}}
    };
  }
  function removeEntry(state,item,trigger){const el=openDialog('Excluir registro?',`<p>Excluir o registro de ${esc(item.media_snapshot?.title)} em ${esc(dateLabel(item.entry_date))}? Sua biblioteca não será alterada.</p><p data-delete-feedback role="status"></p><footer><button type="button" data-cancel>Cancelar</button><button type="button" data-confirm>Excluir registro</button></footer>`,trigger);el.querySelector('[data-cancel]').onclick=()=>closeDialog();el.querySelector('[data-confirm]').onclick=async event=>{event.currentTarget.disabled=true;try{await api('/api/me/diary/'+item.id,{method:'DELETE',signal:state.controller.signal});if(active(state)){if(dialog===el)closeDialog();load(state);}}catch{if(el.isConnected){el.querySelector('[data-delete-feedback]').textContent='Não foi possível excluir. Tente novamente.';el.querySelector('[data-confirm]').disabled=false;}}};}
  async function shareCard(state,trigger){
    const s=state.recap?.stats;if(!s?.entries)return;const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1080;const ctx=canvas.getContext('2d');ctx.fillStyle='#100b0f';ctx.fillRect(0,0,1080,1080);ctx.fillStyle='#e84464';ctx.fillRect(72,96,70,6);ctx.fillStyle='#fff7fb';ctx.font='700 44px sans-serif';ctx.fillText('Meu período no AniNexus',72,185);ctx.fillStyle='#c4b0bc';ctx.font='25px sans-serif';ctx.fillText(`${dateLabel(state.loadedPeriod.start)} — ${dateLabel(state.loadedPeriod.end)}`,72,240);
    const values=[['animes',s.anime_works],['mangás',s.manga_works],['episódios',s.episodes],['capítulos',s.chapters],['horas registradas',(s.minutes/60).toFixed(1).replace('.',',')],['nota média',s.average_score===null?'—':String(s.average_score).replace('.',',')]];
    values.forEach(([label,value],i)=>{const x=72+(i%2)*485,y=385+Math.floor(i/2)*175;ctx.fillStyle='#fff7fb';ctx.font='700 66px sans-serif';ctx.fillText(String(value),x,y);ctx.fillStyle='#c4b0bc';ctx.font='26px sans-serif';ctx.fillText(label,x,y+45);});ctx.fillStyle='#c4b0bc';ctx.font='21px sans-serif';ctx.fillText('Com base nos meus registros do diário.',72,945);ctx.fillText(`${s.estimated_minutes||0} min estimados · aninexus.com.br`,72,982);
    const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob||!active(state))return;const url=URL.createObjectURL(blob),el=openDialog('Seu card está pronto',`<p>O card contém somente os números deste período. Nenhuma anotação ou dado da sua conta é incluído.</p><img class="nx61-recap-preview" src="${canvas.toDataURL('image/png')}" alt="Card com seu resumo do diário"><footer><a download="aninexus-${state.loadedPeriod.start}-${state.loadedPeriod.end}.png" href="${url}">Baixar card</a><button type="button" data-native-share>Compartilhar</button></footer><p data-share-feedback role="status"></p>`,trigger);el.addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});const file=new File([blob],`aninexus-${state.loadedPeriod.start}.png`,{type:'image/png'}),button=el.querySelector('[data-native-share]');button.hidden=!navigator.canShare?.({files:[file]});button.onclick=async()=>{try{await navigator.share({files:[file],title:'Meu período no AniNexus'});}catch(error){if(error.name!=='AbortError')el.querySelector('[data-share-feedback]').textContent='Não foi possível abrir o compartilhamento. Use Baixar card.'}};
  }
  async function mount(app){
    document.documentElement.classList.remove('nx38-library-boot');
    current?.controller.abort();closeDialog();const state={host:app,controller:new AbortController(),version:0,items:[],start:today().slice(0,7)+'-01',end:today()};current=state;
    document.body.classList.add('nx38-library-active','nx49-library-active');document.title='Meu diário | AniNexus';app.innerHTML='<main class="nx61-diary nx49-shell"><p role="status">Carregando seu diário...</p></main>';
    try{const user=await window.AniNexusAuth?.getUser?.();if(!active(state))return;if(!user){app.innerHTML='<main class="nx61-diary nx49-shell"><h1>Seu diário começa aqui.</h1><p>Entre para registrar o que assistiu ou leu, com suas notas e datas.</p><a href="/login">Entrar</a></main>';return;}state.providerOwner=String(user.id);
      app.innerHTML=`<main class="nx61-diary nx49-shell"><header class="nx61-diary-head"><div><a class="nx61-diary-back" href="${pageUrl('/minha-biblioteca')}" aria-label="Voltar à biblioteca"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m14 6-6 6 6 6"/></svg></a><h1>Meu diário</h1><p>O que você viu, leu e sentiu. Guardado na data certa.</p></div><button type="button" data-diary-new>Novo registro</button></header><form class="nx61-diary-period"><label>De<input type="date" name="start" value="${state.start}" min="1900-01-01" max="${today()}" required></label><label>Até<input type="date" name="end" value="${state.end}" min="1900-01-01" max="${today()}" required></label><button type="submit">Ver período</button><div>${[['week','Esta semana'],['month','Este mês'],['year','Este ano']].map(([key,label])=>`<button type="button" data-period="${key}">${label}</button>`).join('')}</div></form><section data-diary-recap aria-label="Resumo do período"></section><p class="nx61-diary-muted">A retrospectiva considera apenas os registros datados do diário. As notas históricas não mudam quando você altera sua avaliação atual.</p><p data-diary-feedback role="status"></p><section data-diary-entries aria-label="Registros do diário"></section><button type="button" data-diary-more hidden>Carregar mais registros</button></main>`;
      const form=app.querySelector('.nx61-diary-period');form.onsubmit=event=>{event.preventDefault();state.start=form.elements.start.value;state.end=form.elements.end.value;load(state);};app.querySelector('[data-diary-new]').onclick=event=>entryForm(state,null,event.currentTarget);app.querySelector('[data-diary-more]').onclick=()=>load(state,true);
      form.querySelectorAll('[data-period]').forEach(button=>button.onclick=()=>{const end=today();let start=end.slice(0,7)+'-01';if(button.dataset.period==='year')start=end.slice(0,4)+'-01-01';if(button.dataset.period==='week'){const d=new Date(end+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);start=d.toISOString().slice(0,10);}form.elements.start.value=start;form.elements.end.value=end;form.requestSubmit();});load(state);
    }catch{if(active(state))app.innerHTML='<main class="nx61-diary nx49-shell"><h1>O diário não carregou agora.</h1><p>Tente abrir novamente pela biblioteca.</p><a href="/minha-biblioteca">Voltar à biblioteca</a></main>';}
  }
  addEventListener('popstate',()=>{current?.controller.abort();current=null;closeDialog();});
  addEventListener('aninexus:account-identity-changed',event=>{
    if(!current)return;
    const next=event.detail?.user;
    const provider=window.Clerk?.user?.id;
    if(event.detail?.confirmed===true&&next?.id&&provider&&String(provider)===current.providerOwner&&(!current.owner||current.owner===String(next.id))){current.owner=String(next.id);return;}
    const host=current.host;current.controller.abort();current=null;closeDialog();
    if(host.isConnected&&host.querySelector('.nx61-diary'))host.innerHTML='<main class="nx61-diary nx49-shell"><h1>Confirme sua conta para abrir o diário.</h1><p>Os registros foram ocultados enquanto sua identidade é verificada.</p><a href="'+pageUrl('/minha-biblioteca?view=diary')+'">Abrir meu diário novamente</a></main>';
  });
  window.AniNexusDiary={mount};
})();
