'use strict';
(() => {
  const ROOT = document.querySelector('#app');
  if (!ROOT) return;
  const IS_PAGES_V7 = location.hostname.endsWith('github.io');
  const BASE_V7 = IS_PAGES_V7 ? '/AniNexus' : '';
  const ENDPOINT_V7 = 'https://graphql.anilist.co';
  const REFRESH_MS = 10 * 60 * 1000;
  const SEASONS = [
    { key: 'WINTER', slug: 'inverno', name: 'Inverno', icon: 'snow' },
    { key: 'SPRING', slug: 'primavera', name: 'Primavera', icon: 'flower' },
    { key: 'SUMMER', slug: 'verao', name: 'Verão', icon: 'umbrella' },
    { key: 'FALL', slug: 'outono', name: 'Outono', icon: 'leaf' },
  ];
  const GENRE_PT = { Action:'Ação', Adventure:'Aventura', Comedy:'Comédia', Drama:'Drama', Fantasy:'Fantasia', Horror:'Terror', Mystery:'Mistério', Romance:'Romance', 'Sci-Fi':'Ficção Científica', 'Slice of Life':'Cotidiano', Sports:'Esportes', Supernatural:'Sobrenatural', Thriller:'Suspense', Psychological:'Psicológico', Music:'Música' };
  const TAG_PT = { Shounen:'Shounen', Isekai:'Isekai', School:'Escola', Magic:'Magia', Seinen:'Seinen', Josei:'Josei', Shoujo:'Shoujo', Demons:'Demônios', Samurai:'Samurai', Military:'Militar', Historical:'Histórico', 'Video Games':'Videogame', 'Time Manipulation':'Viagem no Tempo', 'Urban Fantasy':'Fantasia Urbana' };
  const TAG_PREFERRED = ['Fantasy','Action','Romance','Comedy','Adventure','Drama','Shounen','Isekai','School','Sci-Fi','Slice of Life','Supernatural','Mystery','Magic','Psychological','Sports','Horror','Seinen','Shoujo','Historical'];
  const TYPE_GROUPS = [
    { key:'SERIE', label:'Série', formats:['TV','TV_SHORT'] },
    { key:'MOVIE', label:'Filme', formats:['MOVIE'] },
    { key:'SPECIAL', label:'Especial', formats:['SPECIAL','OVA'] },
    { key:'ONA', label:'ONA', formats:['ONA'] },
  ];
  const V7_ICONS = {
    snow:`<svg viewBox="0 0 64 64" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="3.3" stroke-linecap="round" stroke-linejoin="round"><path d="M32 7v50M10 19l44 26M54 19 10 45M23 11l9 7 9-7M23 53l9-7 9 7M11 29l10 3-10 3M53 29l-10 3 10 3"/></g></svg>`,
    flower:`<svg viewBox="0 0 64 64" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="3.3" stroke-linecap="round" stroke-linejoin="round"><circle cx="32" cy="32" r="6"/><path d="M32 26c-8-5-10-13-4-17 6-4 12 2 9 12 6-7 15-7 17 0 2 7-5 11-14 10 9 2 14 9 10 15-4 6-12 3-16-5 2 10-3 16-10 14-7-2-7-11 0-18-9 4-16 0-15-7 1-7 10-9 17-4"/></g></svg>`,
    umbrella:`<svg viewBox="0 0 64 64" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="3.3" stroke-linecap="round" stroke-linejoin="round"><path d="M13 29c6-15 24-21 37-12 4 3 7 7 8 12-7-3-13-3-19 1-4-5-9-6-15-3-4-2-7-1-11 2Z"/><path d="m33 27-9 25M18 53h34M14 58h42"/></g></svg>`,
    leaf:`<svg viewBox="0 0 64 64" aria-hidden="true"><g fill="none" stroke="currentColor" stroke-width="3.3" stroke-linecap="round" stroke-linejoin="round"><path d="M49 10c-2 9 3 13 8 18-8 1-10 5-12 11-6-3-10-2-14 3-4-5-8-6-14-4 1-7-2-11-9-14 7-4 9-8 9-15 7 3 12 1 16-5 4 6 9 8 16 6Z"/><path d="M12 53c11-14 23-24 37-34"/></g></svg>`,
    tag:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 12.5 12 4h7.5v7.5L11 20l-7.5-7.5Z"/><circle cx="16.2" cy="7.8" r="1.3"/></svg>`,
    type:`<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3.5" y="4" width="17" height="16" rx="2"/><path d="M7 4v4M17 4v4M3.5 9h17"/><path d="m10 12 5 3-5 3v-6Z"/></svg>`,
    star:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z"/></svg>`,
    plus:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>`,
    heart:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.6 8.8c0 5-8.6 10-8.6 10s-8.6-5-8.6-10A4.6 4.6 0 0 1 12 6.4a4.6 4.6 0 0 1 8.6 2.4Z"/></svg>`,
    chevron:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m7 9 5 5 5-5"/></svg>`,
  };
  let activeFilter = { tag: null, type: null };
  let refreshTimer = null;
  let activeController = null;
  let renderToken = 0;
  let currentPayload = null;
  function currentPath() { try { if (typeof pathNow === 'function') return pathNow(); } catch {} let p=location.pathname; if(IS_PAGES_V7)p=p.replace(/^\/AniNexus/,'')||'/'; return p.replace(/\/+$/,'')||'/'; }
  function isSeasonPath(p=currentPath()) { return /^\/animes\/temporadas(?:\/\d{4}\/(?:inverno|primavera|verao|outono))?$/.test(p); }
  function currentAnimeSeason(){const d=new Date(),month=Number(new Intl.DateTimeFormat('en',{timeZone:'America/Sao_Paulo',month:'numeric'}).format(d)),year=Number(new Intl.DateTimeFormat('en',{timeZone:'America/Sao_Paulo',year:'numeric'}).format(d));return{year,season:month<=3?'WINTER':month<=6?'SPRING':month<=9?'SUMMER':'FALL'}}
  function selectionFromPath(){const p=currentPath(),m=p.match(/^\/animes\/temporadas\/(\d{4})\/(inverno|primavera|verao|outono)$/);if(m)return{year:+m[1],season:SEASONS.find(s=>s.slug===m[2])?.key||'SUMMER'};return currentAnimeSeason()}
  function routeFor(year,season){return`/animes/temporadas/${year}/${SEASONS.find(s=>s.key===season)?.slug||'verao'}`}
  function pushRoute(path,replace=false){history[replace?'replaceState':'pushState']({},'',`${BASE_V7}${path}`)}
  function escapeHTML(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function slugify(v='anime'){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,90)}
  function titleOf(m){return m?.title?.english||m?.title?.userPreferred||m?.title?.romaji||m?.title?.native||'Anime'}
  function scoreOf(m){return m?.averageScore?(m.averageScore/10).toFixed(1).replace('.0',''):''}
  function imgOf(m){return m?.coverImage?.extraLarge||m?.coverImage?.large||''}
  function cacheKey(year,season){return`aninexus:season:v7:${year}:${season}`}
  function getCache(year,season){try{const raw=localStorage.getItem(cacheKey(year,season));if(!raw)return null;const v=JSON.parse(raw);return v&&Array.isArray(v.items)?v:null}catch{return null}}
  function setCache(year,season,payload){try{localStorage.setItem(cacheKey(year,season),JSON.stringify({...payload,cachedAt:Date.now()}))}catch{}}
  function isContinuation(m){return(m.relations?.edges||[]).some(e=>e.relationType==='PREQUEL')}
  function seasonMeta(season){return SEASONS.find(s=>s.key===season)||SEASONS[2]}
  function sameSeason(a,b){return a.year===b.year&&a.season===b.season}
  async function gql(query,variables,signal){const res=await fetch(ENDPOINT_V7,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({query,variables}),signal});if(!res.ok)throw new Error(`HTTP ${res.status}`);const json=await res.json();if(json.errors?.length)throw new Error(json.errors[0].message||'Falha');return json.data}
  const FIELDS=`id title{romaji english native userPreferred} coverImage{extraLarge large color} averageScore popularity favourites format status genres tags{name rank} startDate{year month day} relations{edges{relationType}} nextAiringEpisode{airingAt episode}`;
  async function fetchSeason(year,season,signal){const query=`query($page:Int,$year:Int,$season:MediaSeason){Page(page:$page,perPage:50){pageInfo{hasNextPage}media(type:ANIME,isAdult:false,seasonYear:$year,season:$season,sort:[POPULARITY_DESC]){${FIELDS}}}}`;let page=1,items=[];while(page<=4){const d=await gql(query,{page,year,season},signal);items.push(...(d.Page?.media||[]));if(!d.Page?.pageInfo?.hasNextPage)break;page++}const unique=[...new Map(items.map(m=>[m.id,m])).values()];return{items:unique,hash:unique.map(m=>`${m.id}:${m.averageScore||0}:${m.status||''}`).join('|')}}
  async function fetchStillAiring(signal){const q=`query($page:Int){Page(page:$page,perPage:30){media(type:ANIME,isAdult:false,status:RELEASING,sort:[POPULARITY_DESC]){${FIELDS}}}}`;const d=await gql(q,{page:1},signal);return d.Page?.media||[]}
  function seasonIcon(meta){return V7_ICONS[meta.icon]||V7_ICONS.leaf}
  function renderSkeleton(sel){const meta=seasonMeta(sel.season);ROOT.innerHTML=`<section class="season-v7"><div class="season-v7-hero"><div class="season-v7-shell"><div class="season-v7-title"><span class="season-v7-season-icon">${seasonIcon(meta)}</span><div><h1>${meta.name} <em>${sel.year}</em></h1><p>TEMPORADA DE ANIMES</p></div></div><div class="season-v7-stats"><div><strong>—</strong><span>ANIMES</span></div><div><strong>—</strong><span>ESTREIAS</span></div><div><strong>—</strong><span>SEQUÊNCIAS</span></div></div>${controlsMarkup(sel,[],[])}</div></div><div class="season-v7-shell season-v7-body"><div class="season-v7-grid season-v7-skeleton">${Array.from({length:10},()=>'<div><span></span><i></i><i></i></div>').join('')}</div></div></section>`;activateChrome();wireControls(sel,[],[])}
  function tagRows(items){const counts=new Map();for(const m of items){const seen=new Set();for(const g of m.genres||[])seen.add(g);for(const t of m.tags||[])if((t.rank||0)>=40)seen.add(t.name);for(const k of seen)if(TAG_PREFERRED.includes(k))counts.set(k,(counts.get(k)||0)+1)}return[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10).map(([key,count])=>({key,label:GENRE_PT[key]||TAG_PT[key]||key,count}))}
  function typeRows(items){return TYPE_GROUPS.map(t=>({...t,count:items.filter(m=>t.formats.includes(m.format)).length})).filter(t=>t.count>0)}
  function matchesFilters(m){if(activeFilter.tag){const all=[...(m.genres||[]),...(m.tags||[]).map(t=>t.name)];if(!all.includes(activeFilter.tag))return false}if(activeFilter.type){const g=TYPE_GROUPS.find(x=>x.key===activeFilter.type);if(g&&!g.formats.includes(m.format))return false}return true}
  function controlsMarkup(sel,tags,types){const idx=SEASONS.findIndex(s=>s.key===sel.season),years=Array.from({length:45},(_,i)=>new Date().getFullYear()+1-i),selectedTag=tags.find(t=>t.key===activeFilter.tag),selectedType=types.find(t=>t.key===activeFilter.type);return`<div class="season-v7-controls"><div class="season-v7-control-row"><div class="season-v7-segment" style="--active-index:${idx}"><span class="season-v7-segment-slider"></span>${SEASONS.map(s=>`<button type="button" class="${s.key===sel.season?'active':''}" data-v7-season="${s.key}">${s.name}</button>`).join('')}</div><div class="season-v7-dropwrap year"><button type="button" class="season-v7-pill" data-v7-toggle="year"><b>${sel.year}</b>${V7_ICONS.chevron}</button><div class="season-v7-dropdown year-menu" data-v7-menu="year" hidden>${years.map(y=>`<button type="button" class="${y===sel.year?'active':''}" data-v7-year="${y}">${y}</button>`).join('')}</div></div></div><div class="season-v7-filter-row"><div class="season-v7-dropwrap"><button type="button" class="season-v7-pill ${activeFilter.tag?'selected':''}" data-v7-toggle="tag">${V7_ICONS.tag}<b>${escapeHTML(selectedTag?.label||'Tags')}</b>${V7_ICONS.chevron}</button><div class="season-v7-dropdown tag-menu" data-v7-menu="tag" hidden>${tags.map(t=>`<button type="button" class="${t.key===activeFilter.tag?'active':''}" data-v7-tag="${escapeHTML(t.key)}"><span>${escapeHTML(t.label)}</span><small>${t.count}</small></button>`).join('')}</div></div><div class="season-v7-dropwrap"><button type="button" class="season-v7-pill ${activeFilter.type?'selected':''}" data-v7-toggle="type">${V7_ICONS.type}<b>${escapeHTML(selectedType?.label||'Tipo')}</b>${V7_ICONS.chevron}</button><div class="season-v7-dropdown type-menu" data-v7-menu="type" hidden>${types.map(t=>`<button type="button" class="${t.key===activeFilter.type?'active':''}" data-v7-type="${t.key}"><span>${escapeHTML(t.label)}</span><small>${t.count}</small></button>`).join('')}</div></div></div></div>`}
  function readSet(key){try{return new Set((JSON.parse(localStorage.getItem(key)||'[]')||[]).map(v=>typeof v==='object'?v.id:v))}catch{return new Set()}}
  function cardMarkup(m,i){const score=scoreOf(m),liked=readSet('aninexus:favorites').has(m.id),listed=readSet('aninexus:list').has(m.id);return`<article class="season-v7-card" data-v7-media="${m.id}" style="--delay:${Math.min(i,18)*22}ms" tabindex="0" aria-label="Abrir ${escapeHTML(titleOf(m))}"><div class="season-v7-poster"><img loading="lazy" decoding="async" src="${escapeHTML(imgOf(m))}" alt="${escapeHTML(titleOf(m))}"><div class="season-v7-poster-fade"></div>${score?`<span class="season-v7-score">${V7_ICONS.star}<b>${score}</b></span>`:''}<div class="season-v7-actions"><button type="button" class="${listed?'active':''}" data-v7-list="${m.id}" aria-label="Adicionar à lista">${V7_ICONS.plus}</button><button type="button" class="${liked?'active':''}" data-v7-fav="${m.id}" aria-label="Favoritar">${V7_ICONS.heart}</button></div></div><h3>${escapeHTML(titleOf(m))}</h3></article>`}
  function stillMarkup(items){if(!items.length)return'';return`<section class="season-v7-still"><div class="season-v7-section-head"><div><h2>Ainda no ar</h2><p>Começaram antes e seguem em exibição.</p></div></div><div class="season-v7-rail">${items.slice(0,14).map(m=>`<article data-v7-media="${m.id}" tabindex="0"><div><img loading="lazy" decoding="async" src="${escapeHTML(imgOf(m))}" alt="${escapeHTML(titleOf(m))}">${scoreOf(m)?`<span>${V7_ICONS.star}${scoreOf(m)}</span>`:''}</div><strong>${escapeHTML(titleOf(m))}</strong></article>`).join('')}</div></section>`}
  function paint(sel,payload,{silent=false}={}){if(!isSeasonPath())return;currentPayload=payload;const meta=seasonMeta(sel.season),all=payload.items||[],cont=all.filter(isContinuation).length,first=Math.max(0,all.length-cont),tags=tagRows(all),types=typeRows(all),filtered=all.filter(matchesFilters),current=currentAnimeSeason(),still=sameSeason(sel,current)?(payload.still||[]).filter(m=>{if((m.startDate?.year||9999)>sel.year)return false;if((m.startDate?.year||9999)<sel.year)return true;const startMonth={WINTER:1,SPRING:4,SUMMER:7,FALL:10}[sel.season];return(m.startDate?.month||12)<startMonth}):[];ROOT.innerHTML=`<section class="season-v7"><div class="season-v7-hero"><div class="season-v7-shell"><div class="season-v7-title"><span class="season-v7-season-icon">${seasonIcon(meta)}</span><div><h1>${meta.name} <em>${sel.year}</em></h1><p>TEMPORADA DE ANIMES</p></div></div><div class="season-v7-stats"><div><strong>${all.length}</strong><span>ANIMES</span></div><div><strong>${first}</strong><span>ESTREIAS</span></div><div><strong>${cont}</strong><span>SEQUÊNCIAS</span></div></div>${controlsMarkup(sel,tags,types)}</div></div><div class="season-v7-shell season-v7-body"><div class="season-v7-grid">${filtered.map(cardMarkup).join('')||'<div class="season-v7-empty">Nenhum anime encontrado para este filtro.</div>'}</div>${stillMarkup(still)}</div></section>`;document.title=`${meta.name} ${sel.year} | AniNexus`;activateChrome();wireControls(sel,tags,types);wireCards();if(!silent)requestAnimationFrame(()=>document.querySelector('.season-v7')?.classList.add('ready'))}
  function writeSet(key,set){try{localStorage.setItem(key,JSON.stringify([...set]))}catch{}}
  function toggleStored(key,id,button){const set=readSet(key);set.has(id)?set.delete(id):set.add(id);writeSet(key,set);button.classList.toggle('active',set.has(id))}
  function navigateToAnime(m){const p=`/anime/${slugify(titleOf(m))}-${m.id}`;deactivateChrome();pushRoute(p);try{if(typeof render==='function')render();else location.href=BASE_V7+p}catch{location.href=BASE_V7+p}}
  function closeMenus(except=null){document.querySelectorAll('.season-v7-dropdown').forEach(menu=>{if(menu!==except){menu.hidden=true;menu.closest('.season-v7-dropwrap')?.classList.remove('open')}})}
  function wireControls(sel,tags,types){document.querySelectorAll('[data-v7-season]').forEach(btn=>btn.addEventListener('click',()=>{activeFilter={tag:null,type:null};const next={year:sel.year,season:btn.dataset.v7Season};pushRoute(routeFor(next.year,next.season));renderSeasonV7({selection:next})}));document.querySelectorAll('[data-v7-year]').forEach(btn=>btn.addEventListener('click',()=>{activeFilter={tag:null,type:null};const next={year:+btn.dataset.v7Year,season:sel.season};pushRoute(routeFor(next.year,next.season));renderSeasonV7({selection:next})}));document.querySelectorAll('[data-v7-toggle]').forEach(btn=>btn.addEventListener('click',ev=>{ev.stopPropagation();const kind=btn.dataset.v7Toggle,menu=document.querySelector(`[data-v7-menu="${kind}"]`),wrap=btn.closest('.season-v7-dropwrap'),willOpen=menu.hidden;closeMenus(menu);menu.hidden=!willOpen;wrap?.classList.toggle('open',willOpen)}));document.querySelectorAll('[data-v7-tag]').forEach(btn=>btn.addEventListener('click',()=>{activeFilter.tag=activeFilter.tag===btn.dataset.v7Tag?null:btn.dataset.v7Tag;paint(sel,currentPayload,{silent:true})}));document.querySelectorAll('[data-v7-type]').forEach(btn=>btn.addEventListener('click',()=>{activeFilter.type=activeFilter.type===btn.dataset.v7Type?null:btn.dataset.v7Type;paint(sel,currentPayload,{silent:true})}))}
  function wireCards(){const byId=new Map((currentPayload?.items||[]).map(m=>[m.id,m]));for(const m of currentPayload?.still||[])if(!byId.has(m.id))byId.set(m.id,m);document.querySelectorAll('[data-v7-media]').forEach(card=>{const open=()=>{const m=byId.get(+card.dataset.v7Media);if(m)navigateToAnime(m)};card.addEventListener('click',e=>{if(e.target.closest('button'))return;open()});card.addEventListener('keydown',e=>{if(e.key==='Enter')open()})});document.querySelectorAll('[data-v7-fav]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();toggleStored('aninexus:favorites',+b.dataset.v7Fav,b)}));document.querySelectorAll('[data-v7-list]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();toggleStored('aninexus:list',+b.dataset.v7List,b)}));document.querySelectorAll('.season-v7-poster img,.season-v7-rail img').forEach(img=>img.addEventListener('error',()=>{img.removeAttribute('src');img.classList.add('broken')},{once:true}))}
  function activateChrome(){document.body.classList.add('season-v7-active');document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav==='season'))}
  function deactivateChrome(){document.body.classList.remove('season-v7-active');closeMenus()}
  async function loadSeason(sel,{force=false}={}){const token=++renderToken;if(activeController)activeController.abort();activeController=new AbortController();const cached=getCache(sel.year,sel.season);if(cached&&!force)paint(sel,cached);else if(!cached)renderSkeleton(sel);try{const[fresh,still]=await Promise.all([fetchSeason(sel.year,sel.season,activeController.signal),sameSeason(sel,currentAnimeSeason())?fetchStillAiring(activeController.signal):Promise.resolve([])]);if(token!==renderToken||!isSeasonPath())return;const payload={...fresh,still};setCache(sel.year,sel.season,payload);if(!cached||cached.hash!==payload.hash||JSON.stringify((cached.still||[]).map(x=>x.id))!==JSON.stringify(still.map(x=>x.id)))paint(sel,payload,{silent:!!cached});else currentPayload=cached}catch(err){if(err?.name==='AbortError')return;if(!cached&&token===renderToken){const grid=document.querySelector('.season-v7-grid');if(grid)grid.innerHTML='<div class="season-v7-empty">Não foi possível atualizar a temporada agora. Tente novamente em instantes.</div>'}}}
  function renderSeasonV7({selection=null,force=false}={}){if(!isSeasonPath())return;activateChrome();const sel=selection||selectionFromPath(),canonical=routeFor(sel.year,sel.season);if(currentPath()==='/animes/temporadas')pushRoute(canonical,true);loadSeason(sel,{force});clearInterval(refreshTimer);refreshTimer=setInterval(()=>{if(!document.hidden&&isSeasonPath())loadSeason(selectionFromPath(),{force:true})},REFRESH_MS)}
  document.addEventListener('click',e=>{if(!e.target.closest('.season-v7-dropwrap'))closeMenus()});
  document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;const href=a.getAttribute('href')||'';let path=href;if(path.startsWith(BASE_V7))path=path.slice(BASE_V7.length)||'/';if(/^\/animes\/temporadas(?:\/|$)/.test(path)){e.preventDefault();e.stopImmediatePropagation();pushRoute(path);activeFilter={tag:null,type:null};renderSeasonV7();return}if(document.body.classList.contains('season-v7-active'))deactivateChrome()},true);
  window.addEventListener('popstate',()=>setTimeout(()=>{if(isSeasonPath())renderSeasonV7();else deactivateChrome()},0));
  document.addEventListener('visibilitychange',()=>{if(!document.hidden&&isSeasonPath()){const sel=selectionFromPath(),cached=getCache(sel.year,sel.season);if(!cached||Date.now()-(cached.cachedAt||0)>5*60*1000)loadSeason(sel,{force:true})}});
  window.addEventListener('resize',()=>closeMenus());
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{if(isSeasonPath())renderSeasonV7()},0));else setTimeout(()=>{if(isSeasonPath())renderSeasonV7()},0);
})();
