'use strict';
(() => {
  if(window.__ANINEXUS_MANGA_V42__)return;window.__ANINEXUS_MANGA_V42__=true;
  const app=document.querySelector('#app'),IS_PAGES=location.hostname.endsWith('github.io'),BASE=IS_PAGES?'/AniNexus':'';
  if(!app)return;
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const svg={star:'<svg viewBox="0 0 24 24"><path d="m12 3 2.8 5.5 6.1.9-4.4 4.3 1 6.1-5.5-2.9-5.5 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z"/></svg>',heart:'<svg viewBox="0 0 24 24"><path d="M20.5 8.8c0 5-8.5 10-8.5 10s-8.5-5-8.5-10A4.6 4.6 0 0 1 12 6.4a4.6 4.6 0 0 1 8.5 2.4Z"/></svg>',plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',check:'<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 7"/></svg>'};
  const statusLabels={PLANNING:'Quero ler',CURRENT:'Lendo',COMPLETED:'Terminei',PAUSED:'Pausado',DROPPED:'Desisti'};
  const state={items:new Map(),library:null};
  const actionState={list:new Map(),favorites:new Set(),pendingFavorites:new Set(),hydrated:false,hydratePromise:null};
  function route(){const url=new URL(location.href),restored=url.searchParams.get('p');if(restored)return restored.split('?')[0].replace(/\/+$/,'')||'/';let path=url.pathname;if(IS_PAGES)path=path.replace(/^\/AniNexus/,'')||'/';return path.replace(/\/+$/,'')||'/'}
  function go(path){if(IS_PAGES)location.assign(`${BASE}/?build=44.22.0&p=${encodeURIComponent(path)}`);else{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'))}}
  function slug(value){return String(value||'manga').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,90)}
  function title(item){return item?.title?.english||item?.title?.userPreferred||item?.title?.romaji||item?.title||'Mangá'}
  function cover(item){return item?.coverImage?.extraLarge||item?.coverImage?.large||item?.cover||''}
  function score(item){if(item?.metricsSource!=='aninexus')return'';const value=item?.averageScore?Number(item.averageScore)/10:Number(item?.score);return Number.isFinite(value)&&value>0?value.toFixed(1).replace('.0',''):''}
  function formatLabel(value){return({MANGA:'Mangá',NOVEL:'Light novel',ONE_SHOT:'One-shot'})[value]||'Mangá'}
  function normalized(item){if(item?.coverImage)return item;const internal=item?.metricsSource==='aninexus';return{...item,title:{english:item.title,userPreferred:item.title,romaji:item.titleRomaji},coverImage:{extraLarge:item.cover,large:item.cover},averageScore:internal&&item.score?Number(item.score)*10:null,score:internal?item.score:null,meanScore:internal?item.meanScore:null,popularity:internal?Number(item.popularity||0):0,favourites:internal?Number(item.favourites||0):0,ratingCount:internal?Number(item.ratingCount||0):0,listCount:internal?Number(item.listCount||0):0}}
  async function api(path,options={}){if(path.startsWith('/api/me/')){if(!window.AniNexusAuth?.enabled)throw Object.assign(new Error('AUTH_REQUIRED'),{status:401});return window.AniNexusAuth.api(path,options)}const response=await fetch(path,{...options,headers:{accept:'application/json',...(options.headers||{})}});if(!response.ok)throw Object.assign(new Error(`HTTP ${response.status}`),{status:response.status});return response.json()}
  function actionTitle(button){return button?.closest('[data-manga-open],[data-open-manga]')?.dataset?.title||'esta leitura'}
  function syncMangaActions(root=document){
    root.querySelectorAll?.('[data-manga-list]').forEach(button=>{const id=Number(button.dataset.mangaList),active=actionState.list.has(id),name=actionTitle(button);button.classList.toggle('active',active);if(button.dataset.nxActionKind==='compact')button.innerHTML=active?svg.check:svg.plus;button.setAttribute('aria-pressed',String(active));button.setAttribute('aria-label',active?`Alterar estado de leitura de ${name}`:`Adicionar ${name} à lista`)});
    root.querySelectorAll?.('[data-manga-fav]').forEach(button=>{const id=Number(button.dataset.mangaFav),active=actionState.favorites.has(id),name=actionTitle(button);button.classList.toggle('active',active);button.toggleAttribute('disabled',actionState.pendingFavorites.has(id));button.setAttribute('aria-pressed',String(active));button.setAttribute('aria-label',active?`Remover ${name} dos favoritos`:`Favoritar ${name}`)});
  }
  function absorbLibrary(data){
    actionState.list=new Map((data?.list||data?.items||[]).map(item=>[Number(item.media_id),item]).filter(([id])=>Number.isSafeInteger(id)&&id>0));
    if(Array.isArray(data?.favorites))actionState.favorites=new Set(data.favorites.filter(item=>String(item.media_type||'').toUpperCase()==='MANGA').map(item=>Number(item.media_id)).filter(id=>Number.isSafeInteger(id)&&id>0));
    actionState.hydrated=true;syncMangaActions();
  }
  async function hydrateMangaActions(force=false){
    if(actionState.hydrated&&!force){syncMangaActions();return}
    if(actionState.hydratePromise)return actionState.hydratePromise;
    if(!window.AniNexusAuth?.enabled){syncMangaActions();return}
    actionState.hydratePromise=Promise.all([api('/api/me/manga-list'),api('/api/me/favorites')]).then(([list,favorites])=>absorbLibrary({list:list?.items||[],favorites:favorites?.items||[]})).catch(()=>syncMangaActions()).finally(()=>{actionState.hydratePromise=null});
    return actionState.hydratePromise;
  }
  function animateAction(button){if(!button||matchMedia('(prefers-reduced-motion: reduce)').matches)return;button.classList.remove('nx39-pop');void button.offsetWidth;button.classList.add('nx39-pop');setTimeout(()=>button.classList.remove('nx39-pop'),260)}
  function claimMangaDetailActions(root=document){
    const match=route().match(/^\/manga\/.+-(\d+)$/);if(!match)return;
    const id=Number(match[1]),detail=root.matches?.('.nx22-detail')?root:root.querySelector?.('.nx22-detail');if(!detail)return;
    detail.querySelectorAll('[data-list],[data-nx-list],[data-nx-detail-list]').forEach(button=>{button.dataset.mangaList=String(id);button.dataset.nxActionKind='labeled';delete button.dataset.list;delete button.dataset.nxList;delete button.dataset.nxDetailList});
    detail.querySelectorAll('[data-fav],[data-nx-fav],[data-nx-detail-fav]').forEach(button=>{button.dataset.mangaFav=String(id);button.dataset.nxActionKind='compact';delete button.dataset.fav;delete button.dataset.nxFav;delete button.dataset.nxDetailFav});
    syncMangaActions(detail);
  }
  function skeletons(){return `<div class="nx42-manga-grid">${Array.from({length:18},()=>'<div class="nx21-skeleton"></div>').join('')}</div>`}
  function card(raw,libraryItem=null){const item=normalized(raw),name=title(item),image=cover(item),rating=score(item),id=Number(item.id),status=libraryItem?.status||actionState.list.get(id)?.status,favorite=actionState.favorites.has(id);state.items.set(id,item);if(libraryItem?.status)actionState.list.set(id,libraryItem);return `<article class="nx42-manga-card" tabindex="0" data-manga-open="${id}" data-title="${esc(name)}"><div class="nx42-manga-poster">${image?`<img src="${esc(image)}" alt="${esc(name)}" loading="lazy" decoding="async">`:''}${rating?`<span>${svg.star}${rating}</span>`:''}<div class="nx42-manga-actions"><button type="button" data-nx-action-kind="compact" data-manga-list="${id}" class="${status?'active':''}" aria-pressed="${Boolean(status)}" aria-label="${status?`Alterar estado de leitura de ${esc(name)}`:`Adicionar ${esc(name)} à lista`}">${status?svg.check:svg.plus}</button><button type="button" data-nx-action-kind="compact" data-manga-fav="${id}" class="${favorite?'active':''}" aria-pressed="${favorite}" aria-label="${favorite?`Remover ${esc(name)} dos favoritos`:`Favoritar ${esc(name)}`}">${svg.heart}</button></div></div><h3>${esc(name)}</h3><p>${esc([formatLabel(item.format),item.chapters?`${item.chapters} capítulos`:null,status?statusLabels[status]:null].filter(Boolean).join(' · '))}</p></article>`}
  function wireCards(){document.querySelectorAll('[data-manga-open]').forEach(item=>{item.onclick=event=>{if(event.target.closest('button'))return;go(`/manga/${slug(item.dataset.title)}-${item.dataset.mangaOpen}`)};item.onkeydown=event=>{if((event.key==='Enter'||event.key===' ')&&!event.target.closest('button')){event.preventDefault();item.click()}}});syncMangaActions();void hydrateMangaActions()}
  async function toggleFavorite(id,button){
    if(!Number.isSafeInteger(id)||id<=0||actionState.pendingFavorites.has(id))return;
    const wasFavorite=actionState.favorites.has(id),nextFavorite=!wasFavorite;
    nextFavorite?actionState.favorites.add(id):actionState.favorites.delete(id);actionState.pendingFavorites.add(id);syncMangaActions();animateAction(button);
    try{if(nextFavorite)await api(`/api/me/favorites/${id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({mediaType:'MANGA'})});else await api(`/api/me/favorites/${id}?mediaType=MANGA`,{method:'DELETE'})}
    catch(error){nextFavorite?actionState.favorites.delete(id):actionState.favorites.add(id);if(error?.status===401)setTimeout(()=>go('/login'),260)}
    finally{actionState.pendingFavorites.delete(id);syncMangaActions()}
  }
  function openState(id,current=actionState.list.get(id)||{}){document.querySelector('#nx42MangaState')?.remove();const layer=document.createElement('div');layer.id='nx42MangaState';layer.className='nx38pe-layer';layer.innerHTML=`<button class="nx38pe-backdrop" type="button" data-manga-close aria-label="Fechar"></button><form class="nx38pe-card"><header><div><small>SUA LEITURA</small><h2>Atualizar mangá</h2><p>Estado, capítulos lidos e sua nota.</p></div><button type="button" data-manga-close>×</button></header><div class="nx38pe-grid"><label>Estado<select name="status">${Object.entries(statusLabels).map(([value,label])=>`<option value="${value}" ${current.status===value?'selected':''}>${label}</option>`).join('')}</select></label><label>Capítulos lidos<input name="progress" type="number" min="0" max="100000" value="${Number(current.progress||0)}"></label><label>Sua nota<input name="score" type="number" min="0" max="10" step="0.5" value="${current.score??''}" placeholder="0 a 10"></label></div><p class="nx38pe-feedback" role="alert"></p><footer><button type="button" data-manga-remove>Remover da lista</button><span></span><button type="button" data-manga-close>Cancelar</button><button class="primary" type="submit">Salvar</button></footer></form>`;document.body.append(layer);const close=()=>layer.remove();layer.querySelectorAll('[data-manga-close]').forEach(button=>button.onclick=close);layer.querySelector('[data-manga-remove]').onclick=async()=>{try{await api(`/api/me/manga-list/${id}`,{method:'DELETE'});actionState.list.delete(id);syncMangaActions();close();if(route()==='/meus-mangas')mountLibrary()}catch{go('/login')}};layer.querySelector('form').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.currentTarget),scoreValue=String(data.get('score')||'').trim(),payload={status:data.get('status'),progress:Number(data.get('progress')||0),score:scoreValue===''?null:Number(scoreValue)};try{await api(`/api/me/manga-list/${id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});actionState.list.set(id,{media_id:id,...payload});syncMangaActions();close();if(route()==='/meus-mangas')mountLibrary()}catch(error){if(error.status===401)go('/login');else layer.querySelector('[role="alert"]').textContent='Não foi possível salvar agora.'}}}
  async function mountLibrary(){if(route()!=='/meus-mangas')return;document.body.classList.add('nx42-manga-active');app.innerHTML=`<main class="nx42-manga-page"><section class="nx42-manga-hero"><div class="shell"><small>SUA BIBLIOTECA</small><h1>Meus Mangás</h1><p>Leituras, progresso, favoritos e notas em um só lugar.</p><div class="nx42-manga-tools"><select id="nx42LibraryFilter"><option value="ALL">Todos</option>${Object.entries(statusLabels).map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}</select><select id="nx42LibrarySort"><option value="recent">Atualizados recentemente</option><option value="score">Minha nota</option><option value="progress">Progresso</option></select></div></div></section><section class="nx42-manga-body"><div class="shell"><header class="nx42-manga-head"><h2>Minha leitura</h2><a href="/mangas">Explorar catálogo</a></header><div id="nx42MangaLibrary">${skeletons()}</div></div></section></main>`;document.title='Meus Mangás | AniNexus';try{state.library=await api('/api/me/manga-library');absorbLibrary(state.library);paintLibrary();document.querySelector('#nx42LibraryFilter').onchange=paintLibrary;document.querySelector('#nx42LibrarySort').onchange=paintLibrary}catch(error){if(error.status===401){app.innerHTML='<main class="nx42-manga-page"><section class="nx42-manga-body"><div class="shell"><div class="nx21-empty"><strong>Entre para acessar seus mangás</strong><span>Sua leitura será sincronizada entre os dispositivos.</span><button type="button" data-manga-login>Entrar</button></div></div></section></main>';document.querySelector('[data-manga-login]').onclick=()=>go('/login')}else document.querySelector('#nx42MangaLibrary').innerHTML='<div class="nx21-error"><strong>Sua biblioteca não carregou agora.</strong></div>'}}
  function paintLibrary(){const filter=document.querySelector('#nx42LibraryFilter')?.value||'ALL',sortBy=document.querySelector('#nx42LibrarySort')?.value||'recent',merged=new Map();for(const item of state.library?.list||[])merged.set(Number(item.media_id),{...item,media:normalized(item.media||{id:item.media_id})});for(const item of state.library?.favorites||[]){const id=Number(item.media_id);if(!merged.has(id))merged.set(id,{media_id:id,status:null,media:normalized(item.media||{id})})}let items=[...merged.values()];if(filter!=='ALL')items=items.filter(item=>item.status===filter);items.sort(sortBy==='score'?(a,b)=>(b.score??-1)-(a.score??-1):sortBy==='progress'?(a,b)=>(b.progress||0)-(a.progress||0):(a,b)=>Date.parse(b.updated_at||0)-Date.parse(a.updated_at||0));state.items.clear();const root=document.querySelector('#nx42MangaLibrary');root.innerHTML=items.length?`<div class="nx42-manga-grid">${items.map(item=>card(item.media,item)).join('')}</div>`:'<div class="nx21-empty"><strong>Nada nesta categoria</strong><span>Explore o catálogo e adicione sua próxima leitura.</span></div>';wireCards()}
  function mount(){const path=route();if(path==='/mangas'){syncMangaActions();void hydrateMangaActions();return}if(path==='/meus-mangas')mountLibrary();else{document.body.classList.remove('nx42-manga-active');claimMangaDetailActions()}}
  window.addEventListener('pointerdown',event=>{const button=event.target.closest?.('[data-manga-list],[data-manga-fav]');if(button&&!button.disabled)button.classList.add('nx39-press')},true);
  for(const type of ['pointerup','pointercancel','pointerleave'])window.addEventListener(type,event=>event.target.closest?.('[data-manga-list],[data-manga-fav]')?.classList.remove('nx39-press'),true);
  window.addEventListener('click',event=>{const button=event.target.closest?.('[data-manga-list],[data-manga-fav]');if(!button||button.disabled)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();const listId=Number(button.dataset.mangaList),favoriteId=Number(button.dataset.mangaFav);if(Number.isSafeInteger(favoriteId)&&favoriteId>0){void toggleFavorite(favoriteId,button);return}if(Number.isSafeInteger(listId)&&listId>0){animateAction(button);openState(listId)}},true);
  const actionObserver=new MutationObserver(records=>{const added=records.flatMap(record=>[...record.addedNodes]).filter(node=>node.nodeType===1);if(!added.length)return;added.forEach(node=>claimMangaDetailActions(node));if(added.some(node=>node.matches?.('[data-manga-list],[data-manga-fav]')||node.querySelector?.('[data-manga-list],[data-manga-fav]'))){syncMangaActions();void hydrateMangaActions()}});
  actionObserver.observe(document.documentElement,{subtree:true,childList:true});
  addEventListener('aninexus:account-identity-changed',event=>{actionState.hydrated=false;actionState.hydratePromise=null;if(!event.detail?.user){actionState.list.clear();actionState.favorites.clear();actionState.pendingFavorites.clear();actionState.hydrated=true;syncMangaActions();return}void hydrateMangaActions(true)});
  document.addEventListener('click',event=>{if(!/^\/manga\/.+-\d+$/.test(route()))return;const list=event.target.closest('[data-list]'),fav=event.target.closest('[data-fav]'),match=route().match(/-(\d+)$/);if(!match)return;if(list){event.preventDefault();event.stopImmediatePropagation();openState(Number(match[1]))}if(fav){event.preventDefault();event.stopImmediatePropagation();toggleFavorite(Number(match[1]),fav)}},true);
  addEventListener('popstate',()=>setTimeout(()=>{mount();syncMangaActions();void hydrateMangaActions()},0));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{mount();syncMangaActions();void hydrateMangaActions()},{once:true});else{mount();syncMangaActions();void hydrateMangaActions()}
})();
