'use strict';
(() => {
  if(window.__ANINEXUS_MANGA_V42__)return;window.__ANINEXUS_MANGA_V42__=true;
  const app=document.querySelector('#app'),IS_PAGES=location.hostname.endsWith('github.io'),BASE=IS_PAGES?'/AniNexus':'';
  if(!app)return;
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const svg={star:'<svg viewBox="0 0 24 24"><path d="m12 3 2.8 5.5 6.1.9-4.4 4.3 1 6.1-5.5-2.9-5.5 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z"/></svg>',heart:'<svg viewBox="0 0 24 24"><path d="M20.5 8.8c0 5-8.5 10-8.5 10s-8.5-5-8.5-10A4.6 4.6 0 0 1 12 6.4a4.6 4.6 0 0 1 8.5 2.4Z"/></svg>',plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',back:'<svg viewBox="0 0 24 24"><path d="m15 5-7 7 7 7"/></svg>',next:'<svg viewBox="0 0 24 24"><path d="m9 5 7 7-7 7"/></svg>'};
  const statusLabels={PLANNING:'Quero ler',CURRENT:'Lendo',COMPLETED:'Terminei',PAUSED:'Pausado',DROPPED:'Desisti'};
  const state={page:1,search:'',format:'MANGA',sort:'POPULAR',token:0,items:new Map(),library:null};
  function route(){const url=new URL(location.href),restored=url.searchParams.get('p');if(restored)return restored.split('?')[0].replace(/\/+$/,'')||'/';let path=url.pathname;if(IS_PAGES)path=path.replace(/^\/AniNexus/,'')||'/';return path.replace(/\/+$/,'')||'/'}
  function go(path){if(IS_PAGES)location.assign(`${BASE}/?build=42.1.4&p=${encodeURIComponent(path)}`);else{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'))}}
  function slug(value){return String(value||'manga').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,90)}
  function title(item){return item?.title?.english||item?.title?.userPreferred||item?.title?.romaji||item?.title||'Mangá'}
  function cover(item){return item?.coverImage?.extraLarge||item?.coverImage?.large||item?.cover||''}
  function score(item){const value=item?.averageScore?Number(item.averageScore)/10:Number(item?.score);return Number.isFinite(value)&&value>0?value.toFixed(1).replace('.0',''):''}
  function formatLabel(value){return({MANGA:'Mangá',NOVEL:'Light novel',ONE_SHOT:'One-shot'})[value]||'Mangá'}
  function normalized(item){if(item?.coverImage)return item;return{...item,title:{english:item.title,userPreferred:item.title,romaji:item.titleRomaji},coverImage:{extraLarge:item.cover,large:item.cover},averageScore:item.score?Number(item.score)*10:null}}
  async function api(path,options={}){if(path.startsWith('/api/me/')){if(!window.AniNexusAuth?.enabled)throw Object.assign(new Error('AUTH_REQUIRED'),{status:401});return window.AniNexusAuth.api(path,options)}const response=await fetch(path,{...options,headers:{accept:'application/json',...(options.headers||{})}});if(!response.ok)throw Object.assign(new Error(`HTTP ${response.status}`),{status:response.status});return response.json()}
  async function reading(params){
    try{return await api(`/api/reading?${params}`)}catch(error){
      const sortMap={POPULAR:'POPULARITY_DESC',SCORE:'SCORE_DESC',TRENDING:'TRENDING_DESC',NEW:'START_DATE_DESC'},query='query($page:Int,$perPage:Int,$search:String,$format:MediaFormat,$sort:[MediaSort]){Page(page:$page,perPage:$perPage){pageInfo{total currentPage lastPage hasNextPage}media(type:MANGA,isAdult:false,search:$search,format:$format,sort:$sort){id title{romaji english native userPreferred}coverImage{extraLarge large}bannerImage averageScore popularity favourites genres chapters volumes format status startDate{year month day}}}}',variables={page:Number(params.get('page')||1),perPage:Number(params.get('perPage')||24),search:params.get('search')||null,format:params.get('format')||null,sort:[sortMap[params.get('sort')]||sortMap.POPULAR]},controller=new AbortController(),timer=setTimeout(()=>controller.abort(),9000);
      try{const response=await fetch('https://graphql.anilist.co/',{method:'POST',headers:{'content-type':'application/json',accept:'application/json'},body:JSON.stringify({query,variables}),signal:controller.signal});if(!response.ok)throw error;const payload=await response.json();if(payload.errors?.length)throw error;return{pageInfo:payload.data?.Page?.pageInfo||{},items:payload.data?.Page?.media||[]}}finally{clearTimeout(timer)}
    }
  }
  function skeletons(){return `<div class="nx42-manga-grid">${Array.from({length:18},()=>'<div class="nx21-skeleton"></div>').join('')}</div>`}
  function card(raw,libraryItem=null){const item=normalized(raw),name=title(item),image=cover(item),rating=score(item),id=Number(item.id),status=libraryItem?.status;state.items.set(id,item);return `<article class="nx42-manga-card" tabindex="0" data-manga-open="${id}" data-title="${esc(name)}"><div class="nx42-manga-poster">${image?`<img src="${esc(image)}" alt="${esc(name)}" loading="lazy" decoding="async">`:''}${rating?`<span>${svg.star}${rating}</span>`:''}<div class="nx42-manga-actions"><button type="button" data-manga-list="${id}" class="${status?'active':''}" aria-label="${status?'Alterar estado de leitura':'Adicionar à lista'}">${svg.plus}</button><button type="button" data-manga-fav="${id}" aria-label="Favoritar">${svg.heart}</button></div></div><h3>${esc(name)}</h3><p>${esc([formatLabel(item.format),item.chapters?`${item.chapters} capítulos`:null,status?statusLabels[status]:null].filter(Boolean).join(' · '))}</p></article>`}
  function pagination(info){const current=Number(info.currentPage||state.page),last=Number(info.lastPage||current),hasNext=Boolean(info.hasNextPage);if(current<=1&&!hasNext)return'';return `<nav class="nx21-pages" aria-label="Paginação"><button type="button" data-manga-page="${Math.max(1,current-1)}" ${current<=1?'disabled':''} aria-label="Página anterior">${svg.back}</button><span class="nx21-pages-label">Página ${current}${Number.isFinite(last)&&last>=current?` de ${last}`:''}</span><button type="button" data-manga-page="${current+1}" ${!hasNext?'disabled':''} aria-label="Próxima página">${svg.next}</button></nav>`}
  function catalogShell(){document.body.classList.add('nx42-manga-active');document.querySelectorAll('[data-nav]').forEach(link=>link.classList.remove('active'));app.innerHTML=`<main class="nx42-manga-page"><section class="nx42-manga-hero"><div class="shell"><small>LEITURA</small><h1>Catálogo de Mangás</h1><p>Descubra mangás, organize sua leitura e acompanhe seu progresso.</p><div class="nx42-manga-tools"><input id="nx42MangaSearch" type="search" placeholder="Buscar mangá pelo título" value="${esc(state.search)}"><select id="nx42MangaFormat" aria-label="Formato"><option value="MANGA">Mangás</option><option value="ONE_SHOT">One-shots</option><option value="NOVEL">Light novels</option></select><select id="nx42MangaSort" aria-label="Ordenação"><option value="POPULAR">Mais populares</option><option value="SCORE">Melhores notas</option><option value="TRENDING">Em alta</option><option value="NEW">Mais recentes</option></select></div></div></section><section class="nx42-manga-body"><div class="shell"><header class="nx42-manga-head"><h2>Explorar leituras</h2><span id="nx42MangaCount"></span></header><div id="nx42MangaResults">${skeletons()}</div><div id="nx42MangaPages"></div></div></section></main>`;document.title='Mangás | AniNexus';document.querySelector('#nx42MangaFormat').value=state.format;document.querySelector('#nx42MangaSort').value=state.sort;let timer;document.querySelector('#nx42MangaSearch').oninput=event=>{clearTimeout(timer);timer=setTimeout(()=>{state.search=event.target.value.trim();state.page=1;loadCatalog()},340)};document.querySelector('#nx42MangaFormat').onchange=event=>{state.format=event.target.value;state.page=1;loadCatalog()};document.querySelector('#nx42MangaSort').onchange=event=>{state.sort=event.target.value;state.page=1;loadCatalog()}}
  async function loadCatalog(){const token=++state.token,root=document.querySelector('#nx42MangaResults');if(!root)return;root.innerHTML=skeletons();try{const params=new URLSearchParams({page:String(state.page),perPage:'24',format:state.format,sort:state.sort});if(state.search)params.set('search',state.search);const data=await reading(params);if(token!==state.token)return;state.items.clear();root.innerHTML=(data.items||[]).length?`<div class="nx42-manga-grid">${data.items.map(item=>card(item)).join('')}</div>`:'<div class="nx21-empty"><strong>Nenhuma leitura encontrada</strong><span>Tente outro título ou filtro.</span></div>';document.querySelector('#nx42MangaCount').textContent=data.pageInfo?.total?`${Number(data.pageInfo.total).toLocaleString('pt-BR')} títulos`:'';document.querySelector('#nx42MangaPages').innerHTML=pagination(data.pageInfo||{});wireCards()}catch{root.innerHTML='<div class="nx21-error"><strong>Não foi possível carregar os mangás</strong><p>Tente novamente em instantes.</p><button type="button" data-manga-retry>Tentar novamente</button></div>';root.querySelector('[data-manga-retry]').onclick=loadCatalog}}
  function wireCards(){document.querySelectorAll('[data-manga-open]').forEach(item=>{item.onclick=event=>{if(event.target.closest('button'))return;go(`/manga/${slug(item.dataset.title)}-${item.dataset.mangaOpen}`)};item.onkeydown=event=>{if((event.key==='Enter'||event.key===' ')&&!event.target.closest('button')){event.preventDefault();item.click()}}});document.querySelectorAll('[data-manga-page]').forEach(button=>button.onclick=()=>{state.page=Number(button.dataset.mangaPage);loadCatalog();document.querySelector('.nx42-manga-body')?.scrollIntoView({behavior:'smooth'})});document.querySelectorAll('[data-manga-list]').forEach(button=>button.onclick=event=>{event.stopPropagation();openState(Number(button.dataset.mangaList))});document.querySelectorAll('[data-manga-fav]').forEach(button=>button.onclick=event=>{event.stopPropagation();toggleFavorite(Number(button.dataset.mangaFav),button)})}
  async function toggleFavorite(id,button){try{const active=button.classList.toggle('active');if(active)await api(`/api/me/favorites/${id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({mediaType:'MANGA'})});else await api(`/api/me/favorites/${id}?mediaType=MANGA`,{method:'DELETE'});button.setAttribute('aria-label',active?'Remover dos favoritos':'Favoritar')}catch{button.classList.remove('active');go('/login')}}
  function openState(id,current={}){document.querySelector('#nx42MangaState')?.remove();const layer=document.createElement('div');layer.id='nx42MangaState';layer.className='nx38pe-layer';layer.innerHTML=`<button class="nx38pe-backdrop" type="button" data-manga-close aria-label="Fechar"></button><form class="nx38pe-card"><header><div><small>SUA LEITURA</small><h2>Atualizar mangá</h2><p>Estado, capítulos lidos e sua nota.</p></div><button type="button" data-manga-close>×</button></header><div class="nx38pe-grid"><label>Estado<select name="status">${Object.entries(statusLabels).map(([value,label])=>`<option value="${value}" ${current.status===value?'selected':''}>${label}</option>`).join('')}</select></label><label>Capítulos lidos<input name="progress" type="number" min="0" max="100000" value="${Number(current.progress||0)}"></label><label>Sua nota<input name="score" type="number" min="0" max="10" step="0.5" value="${current.score??''}" placeholder="0 a 10"></label></div><p class="nx38pe-feedback" role="alert"></p><footer><button type="button" data-manga-remove>Remover da lista</button><span></span><button type="button" data-manga-close>Cancelar</button><button class="primary" type="submit">Salvar</button></footer></form>`;document.body.append(layer);const close=()=>layer.remove();layer.querySelectorAll('[data-manga-close]').forEach(button=>button.onclick=close);layer.querySelector('[data-manga-remove]').onclick=async()=>{try{await api(`/api/me/manga-list/${id}`,{method:'DELETE'});close();if(route()==='/meus-mangas')mountLibrary()}catch{go('/login')}};layer.querySelector('form').onsubmit=async event=>{event.preventDefault();const data=new FormData(event.currentTarget),scoreValue=String(data.get('score')||'').trim();try{await api(`/api/me/manga-list/${id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({status:data.get('status'),progress:Number(data.get('progress')||0),score:scoreValue===''?null:Number(scoreValue)})});close();if(route()==='/meus-mangas')mountLibrary();else document.querySelector(`[data-manga-list="${id}"]`)?.classList.add('active')}catch(error){if(error.status===401)go('/login');else layer.querySelector('[role="alert"]').textContent='Não foi possível salvar agora.'}}}
  async function mountLibrary(){if(route()!=='/meus-mangas')return;document.body.classList.add('nx42-manga-active');app.innerHTML=`<main class="nx42-manga-page"><section class="nx42-manga-hero"><div class="shell"><small>SUA BIBLIOTECA</small><h1>Meus Mangás</h1><p>Leituras, progresso, favoritos e notas em um só lugar.</p><div class="nx42-manga-tools"><select id="nx42LibraryFilter"><option value="ALL">Todos</option>${Object.entries(statusLabels).map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}</select><select id="nx42LibrarySort"><option value="recent">Atualizados recentemente</option><option value="score">Minha nota</option><option value="progress">Progresso</option></select></div></div></section><section class="nx42-manga-body"><div class="shell"><header class="nx42-manga-head"><h2>Minha leitura</h2><a href="/mangas">Explorar catálogo</a></header><div id="nx42MangaLibrary">${skeletons()}</div></div></section></main>`;document.title='Meus Mangás | AniNexus';try{state.library=await api('/api/me/manga-library');paintLibrary();document.querySelector('#nx42LibraryFilter').onchange=paintLibrary;document.querySelector('#nx42LibrarySort').onchange=paintLibrary}catch(error){if(error.status===401){app.innerHTML='<main class="nx42-manga-page"><section class="nx42-manga-body"><div class="shell"><div class="nx21-empty"><strong>Entre para acessar seus mangás</strong><span>Sua leitura será sincronizada entre os dispositivos.</span><button type="button" data-manga-login>Entrar</button></div></div></section></main>';document.querySelector('[data-manga-login]').onclick=()=>go('/login')}else document.querySelector('#nx42MangaLibrary').innerHTML='<div class="nx21-error"><strong>Sua biblioteca não carregou agora.</strong></div>'}}
  function paintLibrary(){const filter=document.querySelector('#nx42LibraryFilter')?.value||'ALL',sortBy=document.querySelector('#nx42LibrarySort')?.value||'recent',favorites=new Map((state.library?.favorites||[]).map(item=>[Number(item.media_id),item])),merged=new Map();for(const item of state.library?.list||[])merged.set(Number(item.media_id),{...item,media:normalized(item.media||{id:item.media_id})});for(const item of state.library?.favorites||[]){const id=Number(item.media_id);if(!merged.has(id))merged.set(id,{media_id:id,status:null,media:normalized(item.media||{id})})}let items=[...merged.values()];if(filter!=='ALL')items=items.filter(item=>item.status===filter);items.sort(sortBy==='score'?(a,b)=>(b.score??-1)-(a.score??-1):sortBy==='progress'?(a,b)=>(b.progress||0)-(a.progress||0):(a,b)=>Date.parse(b.updated_at||0)-Date.parse(a.updated_at||0));state.items.clear();const root=document.querySelector('#nx42MangaLibrary');root.innerHTML=items.length?`<div class="nx42-manga-grid">${items.map(item=>card(item.media,item)).join('')}</div>`:'<div class="nx21-empty"><strong>Nada nesta categoria</strong><span>Explore o catálogo e adicione sua próxima leitura.</span></div>';wireCards();items.forEach(item=>{const fav=document.querySelector(`[data-manga-fav="${item.media_id}"]`);if(fav)fav.classList.toggle('active',favorites.has(Number(item.media_id)));const list=document.querySelector(`[data-manga-list="${item.media_id}"]`);if(list)list.onclick=event=>{event.stopPropagation();openState(Number(item.media_id),item)}})}
  function mountCatalog(){if(route()!=='/mangas')return;catalogShell();loadCatalog()}
  function mount(){const path=route();if(path==='/mangas')mountCatalog();else if(path==='/meus-mangas')mountLibrary();else document.body.classList.remove('nx42-manga-active')}
  document.addEventListener('click',event=>{if(!/^\/manga\/.+-\d+$/.test(route()))return;const list=event.target.closest('[data-list]'),fav=event.target.closest('[data-fav]'),match=route().match(/-(\d+)$/);if(!match)return;if(list){event.preventDefault();event.stopImmediatePropagation();openState(Number(match[1]))}if(fav){event.preventDefault();event.stopImmediatePropagation();toggleFavorite(Number(match[1]),fav)}},true);
  addEventListener('popstate',()=>setTimeout(mount,0));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
