'use strict';
(() => {
  if(window.__ANINEXUS_V42__)return;window.__ANINEXUS_V42__=true;
  const app=document.querySelector('#app'),IS_PAGES=location.hostname.endsWith('github.io'),BASE=IS_PAGES?'/AniNexus':'';
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const avatarMarkup=(user,options={})=>window.AniNexusAvatar?.markup(user,options)||`<img src="${BASE}/assets/avatars/mascot-pink.png" alt="">`;
  const icons={sun:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></svg>',moon:'<svg viewBox="0 0 24 24"><path d="M20 15.5A8.5 8.5 0 0 1 8.5 4 9 9 0 1 0 20 15.5Z"/></svg>',system:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="14" rx="2"/><path d="M8 22h8M12 18v4"/></svg>',user:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21c.8-5 3.5-7 8-7s7.2 2 8 7"/></svg>',heart:'<svg viewBox="0 0 24 24"><path d="M20.5 8.8c0 5-8.5 10-8.5 10s-8.5-5-8.5-10A4.6 4.6 0 0 1 12 6.4a4.6 4.6 0 0 1 8.5 2.4Z"/></svg>',book:'<svg viewBox="0 0 24 24"><path d="M4 4.5c3.5-.8 6.2-.2 8 1.7v14c-1.8-1.9-4.5-2.5-8-1.7v-14ZM20 4.5c-3.5-.8-6.2-.2-8 1.7v14c1.8-1.9 4.5-2.5 8-1.7v-14Z"/></svg>',bell:'<svg viewBox="0 0 24 24"><path d="M6 10a6 6 0 0 1 12 0c0 5 2 5 2 7H4c0-2 2-2 2-7Z"/><path d="M10 20h4"/></svg>',settings:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 13.5v-3l-2-.7-.7-1.7.9-2-2.2-2.2-2 .9-1.7-.7L10.5 2h-3l-.7 2.1-1.7.7-2-.9L1 6.1l.9 2-.7 1.7-2 .7v3l2 .7.7 1.7-.9 2 2.1 2.1 2-.9 1.7.7.7 2.1h3l.7-2.1 1.7-.7 2 .9 2.2-2.1-.9-2 .7-1.7 2.1-.7Z" transform="translate(2) scale(.9)"/></svg>',logout:'<svg viewBox="0 0 24 24"><path d="M10 4H5v16h5M14 8l4 4-4 4M8 12h10"/></svg>',play:'<svg viewBox="0 0 24 24"><path d="m9 6 9 6-9 6V6Z"/></svg>',plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',star:'<svg viewBox="0 0 24 24"><path d="m12 3 2.8 5.5 6.1.9-4.4 4.3 1 6.1-5.5-2.9-5.5 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z"/></svg>'};
  function route(){const url=new URL(location.href),restored=url.searchParams.get('p');if(restored)return restored.split('?')[0].replace(/\/+$/,'')||'/';let path=url.pathname;if(IS_PAGES)path=path.replace(/^\/AniNexus/,'')||'/';return path.replace(/\/+$/,'')||'/'}
  function go(path){if(IS_PAGES)location.assign(`${BASE}/?build=44.6.0&p=${encodeURIComponent(path)}`);else{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'))}}
  function themeChoice(){try{return localStorage.getItem('aninexus:theme')||'system'}catch{return'system'}}
  function applyTheme(choice){const resolved=choice==='system'?(matchMedia('(prefers-color-scheme:light)').matches?'light':'dark'):choice;try{localStorage.setItem('aninexus:theme',choice)}catch{}document.documentElement.dataset.theme=resolved;document.documentElement.style.colorScheme=resolved;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',resolved==='light'?'#fffafb':'#08060b');document.querySelectorAll('[data-nx42-theme]').forEach(button=>button.classList.toggle('active',button.dataset.nx42Theme===choice));dispatchEvent(new CustomEvent('aninexus:theme-changed',{detail:{choice,resolved}}))}
  function themeCard(){return `<section class="nx42-theme-card" aria-label="Aparência"><header><strong>Aparência</strong><span>Escolha como prefere ver</span></header><div class="nx42-theme-options"><button type="button" data-nx42-theme="light">${icons.sun}Claro</button><button type="button" data-nx42-theme="dark">${icons.moon}Escuro</button><button type="button" data-nx42-theme="system">${icons.system}Automático</button></div></section>`}
  function paintCompactTheme(button){const dark=document.documentElement.dataset.theme==='dark';button.innerHTML=dark?icons.moon:icons.sun;button.setAttribute('aria-label',dark?'Ativar tema claro':'Ativar tema escuro');button.title=dark?'Ativar tema claro':'Ativar tema escuro'}
  function mountTheme(){const host=document.querySelector('.drawer-content');if(!host)return;const compact=host.querySelector('[data-nx-drawer-theme]');if(compact){host.querySelector('.nx42-theme-card')?.remove();if(!compact.dataset.nxThemeBound){compact.dataset.nxThemeBound='1';compact.onclick=()=>{applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');paintCompactTheme(compact)};addEventListener('aninexus:theme-changed',()=>paintCompactTheme(compact))}applyTheme(themeChoice());paintCompactTheme(compact);return}if(host.querySelector('.nx42-theme-card'))return;host.insertAdjacentHTML('beforeend',themeCard());host.querySelectorAll('[data-nx42-theme]').forEach(button=>button.onclick=()=>applyTheme(button.dataset.nx42Theme));applyTheme(themeChoice())}
  matchMedia('(prefers-color-scheme:light)').addEventListener?.('change',()=>{if(themeChoice()==='system')applyTheme('system')});

  let account=null,menu=null;
  addEventListener('aninexus:account-identity-changed',event=>{if(event.detail&&Object.prototype.hasOwnProperty.call(event.detail,'user'))account=event.detail.user||null});
  async function accountData(){if(account)return account;try{account=window.AniNexusAccountData?await window.AniNexusAccountData():(await window.AniNexusAuth?.api?.('/api/me'))?.user||null}catch{}return account}
  function closeAccount(){menu?.remove();menu=null;document.removeEventListener('pointerdown',outsideAccount,true)}
  function outsideAccount(event){if(menu&&!menu.contains(event.target)&&!event.target.closest('.nx38-account-chip'))closeAccount()}
  async function openAccount(chip){if(menu){closeAccount();return}const user=await accountData(),rect=chip.getBoundingClientRect(),name=user?.displayName||chip.textContent.trim()||'Minha conta',handle=user?.username?`@${user.username}`:'Conta AniNexus',identity=user||{displayName:name,avatarUrl:chip.querySelector('img')?.src||''};menu=document.createElement('section');menu.className='nx42-account-menu';menu.setAttribute('role','menu');menu.style.top=`${Math.round(rect.bottom+8)}px`;menu.style.right=`${Math.max(10,Math.round(innerWidth-rect.right))}px`;menu.innerHTML=`<header><i>${avatarMarkup(identity,{name})}</i><div><strong>${esc(name)}</strong><span>${esc(handle)}</span></div></header><nav><button type="button" data-nx42-go="/meus-animes">${icons.heart}Meus animes</button><button type="button" data-nx42-go="/meus-mangas">${icons.book}Meus mangás</button>${user?.username?`<button type="button" data-nx42-go="/u/${encodeURIComponent(user.username)}">${icons.user}Meu perfil público</button>`:''}<button type="button" data-nx42-go="/minha-conta">${icons.settings}Conta e configurações</button><button type="button" data-nx42-logout class="danger">${icons.logout}Sair</button></nav>`;document.body.append(menu);menu.querySelectorAll('[data-nx42-go]').forEach(button=>button.onclick=()=>{closeAccount();go(button.dataset.nx42Go)});menu.querySelector('[data-nx42-logout]').onclick=async()=>{await window.AniNexusAuth?.signOut?.();closeAccount();location.assign('/')};setTimeout(()=>document.addEventListener('pointerdown',outsideAccount,true),0)}
  async function tuneAccountChip(chip){if(chip.dataset.nx42)return;chip.dataset.nx42='1';const user=await accountData();const holder=chip.querySelector('i');if(holder)holder.innerHTML=avatarMarkup(user||{avatarUrl:chip.querySelector('img')?.src},{name:user?.displayName||user?.username||'membro'});chip.setAttribute('aria-haspopup','menu');chip.setAttribute('aria-label','Abrir menu da conta');chip.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();openAccount(chip)},true)}

  function cleanVisibleText(root=document){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(node){if(!node.nodeValue?.trim()||node.parentElement?.closest('script,style,textarea,input,.nx40-source-flow'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){let value=node.nodeValue;value=value.replace(/\bno ep\.?\s*(\d+)/gi,'no episódio $1').replace(/\b(\d+)\s+eps\b/gi,'$1 episódios').replace(/^EP$/,'EPISÓDIO').replace(/\bep\.?\s*(\d+)/gi,'episódio $1');if(value!==node.nodeValue)node.nodeValue=value}}
  function mediaTitle(m){return m?.title?.english||m?.title?.userPreferred||m?.title?.romaji||m?.title||'Título'}
  function mediaCover(m){return m?.coverImage?.extraLarge||m?.coverImage?.large||m?.cover||''}
  function mediaScore(m){if(m?.metricsSource!=='aninexus')return'';const score=m?.averageScore?Number(m.averageScore)/10:Number(m?.score);return Number.isFinite(score)&&score>0?score.toFixed(1).replace('.0',''):''}
  function mediaSlug(value='titulo'){return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,90)||'titulo'}
  function rankCard(m,index,type='manga'){const title=mediaTitle(m),cover=mediaCover(m),score=mediaScore(m),path=`/${type}/${mediaSlug(title)}-${Number(m.id)}`;return `<a class="nx35-rank" href="${esc(path)}" data-nx42-media="${Number(m.id)}" data-nx42-type="${type}" data-title="${esc(title)}"><span class="nx35-rank-num">${index+1}</span><div class="nx35-rank-cover">${cover?`<img loading="lazy" src="${esc(cover)}" alt="${esc(title)}">`:''}${score?`<b>${icons.star}${score}</b>`:''}</div><div class="nx35-rank-copy"><small>${index+1}º LUGAR</small><h3>${esc(title)}</h3></div></a>`}
  async function mountHomeExtras(){if(route()!=='/'||!document.querySelector('.nx35-home')||document.querySelector('#nx42TopManga'))return;const animeRanking=document.querySelector('#nx35Top')?.closest('.nx35-section');if(animeRanking){const section=document.createElement('section');section.className='nx35-section tonal nx42-home-ranking';section.innerHTML=`<div class="nx35-shell"><div class="nx35-head"><div><small>RANKING DE LEITURA</small><h2>Top 10 <em>Mangás</em></h2><p>Os mangás mais bem avaliados, sem misturar formatos.</p></div><a href="/mangas">Ver catálogo ${icons.play}</a></div><div id="nx42TopManga" class="nx35-placeholder"><div class="nx35-skeleton-row"></div></div></div>`;animeRanking.insertAdjacentElement('afterend',section)}
    try{let items=[];if(!IS_PAGES){const response=await fetch('/api/reading?page=1&perPage=10&format=MANGA&sort=SCORE',{headers:{accept:'application/json'}});if(response.ok)items=((await response.json()).items||[]).filter(item=>item.metricsSource==='aninexus'&&Number(item.ratingCount)>0)}const root=document.querySelector('#nx42TopManga');if(root)root.innerHTML=items.length?`<div class="nx35-edge"><div class="nx35-rail nx35-rank-rail">${items.slice(0,10).map((m,i)=>rankCard(m,i)).join('')}</div></div>`:'<div class="nx35-data-empty"><strong>O ranking nasce com as avaliações da comunidade.</strong></div>'}catch{document.querySelector('#nx42TopManga')?.replaceChildren()}
    const community=document.querySelector('#nx35Community')?.closest('.nx35-section');if(community&&!document.querySelector('#nx42Trailers')){const section=document.createElement('section');section.className='nx35-section';section.innerHTML=`<div class="nx35-shell"><div class="nx35-head"><div><small>VÍDEOS</small><h2>Últimos <em>Trailers</em></h2><p>Materiais promocionais recentes em um só lugar.</p></div><a href="/noticias">Ver notícias ${icons.play}</a></div><div id="nx42Trailers" class="nx42-trailer-grid"><div class="nx35-skeleton-row"></div></div></div>`;community.insertAdjacentElement('beforebegin',section);loadTrailers()}
  }
  async function loadTrailers(){try{const response=await fetch('/api/catalog?page=1&perPage=18&sort=NEW',{headers:{accept:'application/json'}}),data=response.ok?await response.json():{items:[]},items=(data.items||[]).filter(item=>item.trailer?.id).slice(0,3),root=document.querySelector('#nx42Trailers');if(!root)return;root.innerHTML=items.length?items.map(item=>{const title=mediaTitle(item),youtube=item.trailer.site?.toLowerCase()==='youtube',video=youtube?`https://www.youtube.com/watch?v=${encodeURIComponent(item.trailer.id)}`:`/anime/${item.slug}`,thumbnail=youtube?`https://i.ytimg.com/vi/${encodeURIComponent(item.trailer.id)}/hqdefault.jpg`:(item.trailer.thumbnail||item.banner||item.cover);return `<a class="nx42-trailer" href="${esc(video)}" ${video.startsWith('http')?'target="_blank" rel="noopener noreferrer"':''}><img src="${esc(thumbnail)}" alt="Trailer de ${esc(title)}" loading="lazy"><i>${icons.play}</i><div><small>TRAILER</small><strong>${esc(title)}</strong><span>Assistir material promocional</span></div></a>`}).join(''):'<div class="nx35-data-empty"><strong>Novos trailers serão publicados aqui.</strong></div>'}catch{}}

  const GENRES={Ação:'Action',Aventura:'Adventure',Comédia:'Comedy',Drama:'Drama',Fantasia:'Fantasy',Terror:'Horror',Mistério:'Mystery',Romance:'Romance','Ficção Científica':'Sci-Fi',Cotidiano:'Slice of Life',Esportes:'Sports',Sobrenatural:'Supernatural',Suspense:'Thriller',Psicológico:'Psychological',Música:'Music',Mecha:'Mecha'};
  function enhanceDetail(){const match=route().match(/^\/anime\/.+-(\d+)$/);if(!match||!document.querySelector('.nx22-detail')||document.querySelector('.nx22-fail'))return;const chips=document.querySelector('.nx22-chips');chips?.querySelectorAll('span').forEach(span=>{const genre=GENRES[span.textContent.trim()];if(!genre)return;const link=document.createElement('a');link.href='/animes/catalogo';link.textContent=span.textContent;link.onclick=()=>{try{sessionStorage.setItem('nx23:catalog:incoming',JSON.stringify({genre}))}catch{}};span.replaceWith(link)});const stats=document.querySelector('.nx22-stats');if(stats&&!stats.dataset.community){stats.dataset.community='loading';fetch(`/api/anime/${Number(match[1])}/rating`,{headers:{accept:'application/json'}}).then(response=>response.ok?response.json():null).then(data=>{const cell=stats.firstElementChild;if(!cell)return;if(data?.votes){cell.querySelector('strong').textContent=Number(data.score).toFixed(1).replace('.0','');cell.querySelector('span').textContent=`nota de ${Number(data.votes).toLocaleString('pt-BR')} ${Number(data.votes)===1?'membro':'membros'}`}else{cell.querySelector('strong').textContent='—';cell.querySelector('span').textContent='sem avaliações ainda'}}).catch(()=>{}).finally(()=>stats.dataset.community='ready')}enhanceWatch();mountImpressions('ANIME')}
  async function mountImpressions(type){const match=route().match(type==='ANIME'?/^\/anime\/.+-(\d+)$/:/^\/manga\/.+-(\d+)$/);if(!match||document.querySelector('.nx42-impressions')||document.querySelector('.nx22-fail'))return;const id=Number(match[1]),host=document.querySelector('.nx22-content')||document.querySelector('.detail-content');if(!host)return;const section=document.createElement('section');section.className='nx42-impressions';section.innerHTML=`<div class="nx42-impressions-head"><div><small>COMUNIDADE</small><h2>Impressões dos membros</h2></div><span></span></div><form class="nx42-impression-form"><textarea maxlength="1200" placeholder="Compartilhe sua impressão sobre esta obra" aria-label="Sua impressão"></textarea><footer><label><input type="checkbox" name="spoiler"> Contém spoiler</label><button type="submit">Publicar impressão</button></footer></form><div class="nx42-impression-list" aria-live="polite">Carregando…</div>`;host.append(section);const endpoint=`/api/${type==='ANIME'?'anime':'manga'}/${id}/impressions`,list=section.querySelector('.nx42-impression-list');async function load(){try{const response=await fetch(endpoint,{headers:{accept:'application/json'}}),data=response.ok?await response.json():{items:[]};list.innerHTML=(data.items||[]).length?(data.items||[]).map(item=>`<article class="nx42-impression"><header>${item.avatar_url?`<img src="${esc(item.avatar_url)}" alt="">`:`<i>${esc(String(item.display_name||item.username||'?').charAt(0))}</i>`}<a href="/u/${encodeURIComponent(item.username)}">@${esc(item.username)}</a><time>${new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium'}).format(new Date(item.created_at))}</time></header><p class="${item.spoiler?'nx42-spoiler':''}" title="Toque para revelar">${esc(item.body)}</p></article>`).join(''):'<div class="nx35-data-empty"><strong>Seja a primeira pessoa a deixar uma impressão.</strong></div>';list.querySelectorAll('.nx42-spoiler').forEach(item=>item.onclick=()=>item.classList.toggle('revealed'))}catch{list.textContent='As impressões não carregaram agora.'}}section.querySelector('form').onsubmit=async event=>{event.preventDefault();const textarea=event.currentTarget.querySelector('textarea'),button=event.currentTarget.querySelector('button'),body=textarea.value.trim();if(!body)return;button.disabled=true;try{const response=await window.AniNexusAuth?.api?.(endpoint,{method:'POST',body:JSON.stringify({body,spoiler:event.currentTarget.elements.spoiler.checked})});if(!response)throw new Error();textarea.value='';await load()}catch{if(!window.AniNexusAuth?.enabled)go('/login');else button.textContent='Entre para publicar'}finally{button.disabled=false}};load()}

  function officialWatchMarkup(){const providers=[['Crunchyroll','crunchyroll.svg','https://www.crunchyroll.com/pt-br/'],['Netflix','netflix.svg','https://www.netflix.com/br/'],['Prime Video','amazon.svg','https://www.primevideo.com/'],['Apple TV','apple.svg','https://tv.apple.com/br/']];return `<section class="nx42-official-watch"><h3>Serviços oficiais no Brasil</h3><p>A disponibilidade varia por título, região e assinatura.</p><div class="nx42-official-logos">${providers.map(([name,logo,url])=>`<a href="${url}" target="_blank" rel="nofollow noopener noreferrer"><img src="${BASE}/assets/streaming/${logo}" alt="">${name}</a>`).join('')}</div><button type="button" class="nx42-member-watch" data-member-telegram>Acessar pelo Telegram</button><p data-member-message>O acesso ao Telegram é exclusivo para membros com conta.</p></section>`}
  function enhanceWatch(){let host;if(route()==='/animes/onde-assistir')host=document.querySelector('#watchGrid');else host=[...document.querySelectorAll('.nx22-section')].find(section=>/Onde assistir/i.test(section.querySelector('h2')?.textContent||''));if(!host||host.querySelector('.nx42-official-watch'))return;host.insertAdjacentHTML('afterbegin',officialWatchMarkup());host.querySelector('[data-member-telegram]').onclick=async event=>{const message=host.querySelector('[data-member-message]');event.currentTarget.disabled=true;try{const data=await window.AniNexusAuth?.api?.('/api/member/telegram');if(!data?.url)throw new Error('LOGIN');location.assign(data.url)}catch{if(message)message.textContent='Entre ou crie sua conta para liberar este acesso.';go('/login')}finally{event.currentTarget.disabled=false}}}

  function enhanceNews(){const match=route().match(/^\/noticias\/(.+)$/);if(!match||!document.querySelector('.nx35-reader'))return;mountNewsComments(decodeURIComponent(match[1]))}
  function mountNewsComments(slug){const host=document.querySelector('.nx35-article-main');if(!host||host.querySelector('.nx42-news-comments'))return;const section=document.createElement('section');section.className='nx42-news-comments';section.innerHTML=`<header><small>CONVERSA</small><h2>Comentários da comunidade</h2></header><form class="nx42-news-comment-form"><textarea maxlength="1800" placeholder="Comente com respeito e marque spoilers" aria-label="Seu comentário"></textarea><footer><label><input name="spoiler" type="checkbox"> Contém spoiler</label><button type="submit">Publicar comentário</button></footer></form><div class="nx42-news-comment-list" aria-live="polite">Carregando…</div>`;host.append(section);const endpoint=`/api/news/${encodeURIComponent(slug)}/comments`,list=section.querySelector('.nx42-news-comment-list');const relative=value=>{const days=Math.max(0,Math.floor((Date.now()-Date.parse(value||0))/86400000));return days?`há ${days}d`:'hoje'};async function load(){try{const response=await fetch(endpoint,{headers:{accept:'application/json'}}),data=response.ok?await response.json():{items:[]};list.innerHTML=(data.items||[]).length?data.items.map(item=>`<article class="nx42-news-comment" data-comment="${esc(item.id)}"><header>${item.avatar_url?`<img src="${esc(item.avatar_url)}" alt="">`:`<i>${esc(String(item.display_name||item.username||'?').charAt(0))}</i>`}<a href="/u/${encodeURIComponent(item.username)}">@${esc(item.username)}</a><time>${relative(item.created_at)}</time></header><p class="${item.spoiler?'nx42-spoiler':''}">${esc(item.body)}</p><button type="button" data-report-comment>Denunciar</button></article>`).join(''):'<div class="nx35-data-empty"><strong>Comece uma conversa respeitosa sobre esta notícia.</strong></div>';list.querySelectorAll('.nx42-spoiler').forEach(item=>item.onclick=()=>item.classList.toggle('revealed'));list.querySelectorAll('[data-report-comment]').forEach(button=>button.onclick=async()=>{const reason=prompt('Explique brevemente o motivo da denúncia:')?.trim();if(!reason)return;try{await window.AniNexusAuth?.api?.(`/api/news/comments/${button.closest('[data-comment]').dataset.comment}/report`,{method:'POST',body:JSON.stringify({reason})});button.textContent='Denúncia enviada';button.disabled=true}catch{go('/login')}})}catch{list.textContent='Os comentários não carregaram agora.'}}section.querySelector('form').onsubmit=async event=>{event.preventDefault();const textarea=event.currentTarget.querySelector('textarea'),button=event.currentTarget.querySelector('button'),body=textarea.value.trim();if(body.length<2)return;button.disabled=true;try{await window.AniNexusAuth.api(endpoint,{method:'POST',body:JSON.stringify({body,spoiler:event.currentTarget.elements.spoiler.checked})});textarea.value='';await load()}catch{go('/login')}finally{button.disabled=false}};load()}

  async function mountNotifications(){if(route().split('#')[0]!=='/minha-conta'||document.querySelector('.nx42-notifications'))return;const shell=document.querySelector('.nx38-account-shell');if(!shell)return;const section=document.createElement('section');section.className='nx42-notifications';section.id='notificacoes';section.innerHTML='<h2>Notificações</h2><p>Carregando…</p>';shell.append(section);try{const data=await window.AniNexusAuth?.api?.('/api/me/notifications?limit=20'),items=data?.items||[];section.innerHTML=`<h2>Notificações</h2>${items.length?items.map(item=>`<article class="nx42-notification${item.read_at?' read':''}" data-notification="${esc(item.id)}"><i></i><div><strong>${esc(item.title)}</strong>${item.body?`<p>${esc(item.body)}</p>`:''}</div><time>${new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(item.created_at))}</time></article>`).join(''):'<p>Você está em dia. Novidades da sua lista aparecerão aqui.</p>'}`;section.querySelectorAll('[data-notification]:not(.read)').forEach(row=>row.onclick=async()=>{await window.AniNexusAuth.api(`/api/me/notifications/${row.dataset.notification}/read`,{method:'POST'});row.classList.add('read')})}catch{section.innerHTML='<h2>Notificações</h2><p>Não foi possível consultar agora.</p>'}}

  function consent(){if(IS_PAGES)return;try{if(localStorage.getItem('aninexus:privacy:v1'))return}catch{}const card=document.createElement('section');card.className='nx42-consent';card.setAttribute('role','dialog');card.setAttribute('aria-label','Preferências de privacidade');card.innerHTML='<strong>Privacidade no AniNexus</strong><p>Usamos armazenamento necessário para manter login, tema e sua lista. Métricas opcionais só serão usadas com sua escolha.</p><div><button type="button" data-consent="necessary">Somente necessárias</button><button class="primary" type="button" data-consent="analytics">Permitir métricas</button></div>';document.body.append(card);card.querySelectorAll('[data-consent]').forEach(button=>button.onclick=()=>{try{localStorage.setItem('aninexus:privacy:v1',JSON.stringify({analytics:button.dataset.consent==='analytics',at:Date.now()}))}catch{}card.remove()})}

  function enhance(){mountTheme();document.querySelectorAll('.nx38-account-chip').forEach(tuneAccountChip);cleanVisibleText(app);const footerCopy=document.querySelector('.footer-about p');if(footerCopy)footerCopy.textContent='Seu espaço para organizar listas, acompanhar lançamentos, avaliar obras e conversar com a comunidade.';mountHomeExtras();enhanceDetail();enhanceWatch();enhanceNews();if(/^\/manga\/.+-\d+$/.test(route()))mountImpressions('MANGA');mountNotifications()}
  const observer=new MutationObserver(records=>{if(records.some(record=>[...record.addedNodes].some(node=>node.nodeType===1))){clearTimeout(observer.timer);observer.timer=setTimeout(enhance,20)}});observer.observe(document.documentElement,{subtree:true,childList:true});
  document.addEventListener('click',event=>{const media=event.target.closest('[data-nx42-media]');if(media&&!event.target.closest('button,a'))go(`/${media.dataset.nx42Type}/${String(media.dataset.title||'titulo').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}-${media.dataset.nx42Media}`)});
  addEventListener('popstate',()=>setTimeout(enhance,30));addEventListener('aninexus:home-v34-ready',()=>setTimeout(mountHomeExtras,20));addEventListener('aninexus:route-ready',()=>setTimeout(enhance,20));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{enhance();setTimeout(consent,800)},{once:true});else{enhance();setTimeout(consent,800)}
})();
