'use strict';
(() => {
  if(window.__NX38_AUTH__)return;window.__NX38_AUTH__=true;
  const app=document.querySelector('#app');if(!app)return;
  const IS_PAGES=location.hostname.endsWith('github.io'),BASE=IS_PAGES?'/AniNexus':'',BUILD='38.0.0';
  let currentUser=null,loadingUser=null,rendering=false;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function route(){try{const u=new URL(location.href),p=u.searchParams.get('p');if(p)return p.split('?')[0].replace(/\/+$/,'')||'/';let x=u.pathname;if(IS_PAGES)x=x.replace(/^\/AniNexus/,'')||'/';return x.replace(/\/+$/,'')||'/'}catch{return'/'}}
  const owns=()=>['/login','/criar-conta','/minha-conta'].includes(route());
  function url(path){return IS_PAGES?`${BASE}/?build=${BUILD}&p=${encodeURIComponent(path)}`:path}
  function go(path,replace=false){if(IS_PAGES){location.assign(url(path));return}history[replace?'replaceState':'pushState']({},'',path);render()}
  async function api(path,options={}){
    const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),12000);
    try{const r=await fetch(path,{credentials:'same-origin',cache:'no-store',...options,signal:ctl.signal,headers:{accept:'application/json',...(options.body?{'content-type':'application/json'}:{}),...(options.headers||{})}});let data={};try{data=await r.json()}catch{}if(!r.ok){const e=new Error(data?.error||`HTTP_${r.status}`);e.status=r.status;e.code=data?.error;throw e}return data}finally{clearTimeout(timer)}
  }
  function errorText(err){if(err?.status===429)return'Tentativas demais em pouco tempo. Aguarde um minuto e tente novamente.';return({INVALID_CREDENTIALS:'E-mail/usuário ou senha incorretos.',ACCOUNT_UNAVAILABLE:'Esse e-mail ou nome de usuário já está em uso.',INVALID_INPUT:'Confira os campos e tente novamente.',INVALID_ORIGIN:'A sessão de segurança expirou. Atualize a página e tente de novo.',INTERNAL_ERROR:'O AniNexus teve um problema interno. Tente novamente em instantes.'})[err?.code]||(/abort/i.test(err?.name||'')?'A conexão demorou demais. Verifique sua internet e tente novamente.':'Não foi possível concluir agora. Tente novamente.')}
  async function getUser(force=false){if(IS_PAGES)return null;if(currentUser&&!force)return currentUser;if(loadingUser&&!force)return loadingUser;loadingUser=api('/api/me').then(x=>currentUser=x?.user||null).catch(()=>currentUser=null).finally(()=>loadingUser=null);return loadingUser}
  function activate(){document.body.classList.remove('nx35-news-active','nx35-home-active','aqx-home-active');document.body.classList.add('nx38-auth-active');document.querySelectorAll('[data-nav]').forEach(a=>a.classList.remove('active'))}
  function story(mode){const create=mode==='register';return `<section class="nx38-auth-story"><a class="nx38-auth-brand" href="${url('/')}" data-auth-home><img src="${BASE}/assets/logo.png" alt=""><strong>AniNexus</strong></a><div class="nx38-auth-copy"><span class="nx38-auth-kicker">SUA CONTA ANINEXUS</span><h1>${create?'Monte sua jornada.<br><em>Do seu jeito.</em>':'Seu universo<br><em>continua aqui.</em>'}</h1><p>${create?'Uma conta conecta sua lista, favoritos, progresso, comunidade, notícias e conquistas em todos os seus dispositivos.':'Entre para continuar acompanhando episódios, listas, favoritos, notícias e conversas sem perder o que já construiu.'}</p><div class="nx38-auth-benefits"><div class="nx38-auth-benefit"><i>✓</i><div><strong>Uma lista só</strong><span>Assistindo, concluídos, pausados e quero ver.</span></div></div><div class="nx38-auth-benefit"><i>✦</i><div><strong>Experiência pessoal</strong><span>Home e recomendações evoluem com você.</span></div></div><div class="nx38-auth-benefit"><i>●</i><div><strong>Comunidade</strong><span>Impressões, discussões e atividades ligadas aos títulos.</span></div></div></div></div><span class="nx38-auth-footnote">AniNexus · feito para acompanhar anime e mangá em português.</span></section>`}
  function passwordField(name='password',label='Senha',autocomplete='current-password'){return `<div class="nx38-auth-field"><label for="nx38-${name}">${label}</label><div class="nx38-auth-input-wrap"><input class="nx38-auth-input" id="nx38-${name}" name="${name}" type="password" autocomplete="${autocomplete}" minlength="10" maxlength="128" required><button class="nx38-password-toggle" type="button" data-toggle-password="nx38-${name}" aria-label="Mostrar senha">MOSTRAR</button></div></div>`}
  function authCard(mode){const create=mode==='register';return `<section class="nx38-auth-panel"><div class="nx38-auth-card"><header class="nx38-auth-card-head"><small>${create?'CRIAR CONTA':'BEM-VINDO DE VOLTA'}</small><h2>${create?'Comece no AniNexus':'Entre na sua conta'}</h2><p>${create?'Leva menos de um minuto. Seus dados de acesso ficam protegidos e a senha nunca é armazenada em texto puro.':'Use seu e-mail ou nome de usuário para continuar de onde parou.'}</p></header>${IS_PAGES?'<div class="nx38-pages-note">O GitHub Pages é apenas o preview estático. Login e criação de conta funcionam no servidor oficial do AniNexus.</div>':''}<form class="nx38-auth-form" id="nx38AuthForm" novalidate>${create?`<div class="nx38-auth-field"><label for="nx38-username">Nome de usuário</label><input class="nx38-auth-input" id="nx38-username" name="username" autocomplete="username" minlength="3" maxlength="30" pattern="[A-Za-zÀ-ÿ0-9_.-]+" placeholder="Como você aparecerá na comunidade" required></div><div class="nx38-auth-field"><label for="nx38-email">E-mail</label><input class="nx38-auth-input" id="nx38-email" name="email" type="email" autocomplete="email" maxlength="254" placeholder="voce@exemplo.com" required></div>`:`<div class="nx38-auth-field"><label for="nx38-login">E-mail ou usuário</label><input class="nx38-auth-input" id="nx38-login" name="login" autocomplete="username" maxlength="254" required></div>`}${passwordField('password','Senha',create?'new-password':'current-password')}${create?`${passwordField('confirm','Confirmar senha','new-password')}<div class="nx38-password-rules" id="nx38Rules"><span data-rule="length">10 ou mais caracteres</span><span data-rule="letter">Pelo menos uma letra</span><span data-rule="number">Pelo menos um número</span><span data-rule="match">As duas senhas coincidem</span></div><label class="nx38-auth-check"><input type="checkbox" name="terms" required><span>Li e concordo com os <a class="nx38-auth-link" href="${url('/termos-de-uso')}">Termos de Serviço</a> e a <a class="nx38-auth-link" href="${url('/politica-de-privacidade')}">Política de Privacidade</a>.</span></label>`:''}<div class="nx38-auth-error" id="nx38AuthError" role="alert" aria-live="polite"></div><button class="nx38-auth-submit" type="submit" ${IS_PAGES?'disabled':''}><span>${create?'Criar minha conta':'Entrar'}</span></button></form><div class="nx38-auth-switch">${create?'Já tem uma conta?':'Ainda não tem conta?'} <button type="button" class="nx38-auth-link" data-auth-switch="${create?'login':'register'}">${create?'Entrar':'Criar conta'}</button></div></div></section>`}
  function setError(msg=''){const el=document.querySelector('#nx38AuthError');if(!el)return;el.textContent=msg;el.classList.toggle('show',!!msg)}
  function setPending(on,label){const btn=document.querySelector('.nx38-auth-submit');if(!btn)return;btn.disabled=on||IS_PAGES;btn.innerHTML=on?'<i class="nx38-spin"></i><span>Processando…</span>':`<span>${label}</span>`}
  function updateRules(){const p=document.querySelector('#nx38-password')?.value||'',c=document.querySelector('#nx38-confirm')?.value||'';const state={length:p.length>=10,letter:/[A-Za-zÀ-ÿ]/.test(p),number:/\d/.test(p),match:p.length>0&&p===c};for(const [k,v] of Object.entries(state))document.querySelector(`[data-rule="${k}"]`)?.classList.toggle('ok',v);return Object.values(state).every(Boolean)}
  function wireForm(mode){document.querySelectorAll('[data-toggle-password]').forEach(b=>b.onclick=()=>{const input=document.getElementById(b.dataset.togglePassword);if(!input)return;const show=input.type==='password';input.type=show?'text':'password';b.textContent=show?'OCULTAR':'MOSTRAR';b.setAttribute('aria-label',show?'Ocultar senha':'Mostrar senha')});document.querySelectorAll('[data-auth-switch]').forEach(b=>b.onclick=()=>go(b.dataset.authSwitch==='login'?'/login':'/criar-conta'));document.querySelector('[data-auth-home]')?.addEventListener('click',e=>{if(IS_PAGES)return;e.preventDefault();location.assign('/')});if(mode==='register'){document.querySelector('#nx38-password')?.addEventListener('input',updateRules);document.querySelector('#nx38-confirm')?.addEventListener('input',updateRules)}const f=document.querySelector('#nx38AuthForm');if(!f||IS_PAGES)return;f.onsubmit=async e=>{e.preventDefault();setError('');if(!f.reportValidity())return;if(mode==='register'&&!updateRules()){setError('A senha ainda não atende aos requisitos.');return}const fd=new FormData(f),payload=mode==='login'?{login:String(fd.get('login')||'').trim(),password:String(fd.get('password')||'')}:{username:String(fd.get('username')||'').trim(),email:String(fd.get('email')||'').trim(),password:String(fd.get('password')||'')};setPending(true,mode==='login'?'Entrar':'Criar minha conta');try{const data=await api(`/api/auth/${mode}`,{method:'POST',body:JSON.stringify(payload)});currentUser=data.user||null;syncHeader();location.assign('/')}catch(err){setError(errorText(err));setPending(false,mode==='login'?'Entrar':'Criar minha conta')}}}
  async function renderAuth(mode){activate();document.title=`${mode==='login'?'Entrar':'Criar conta'} | AniNexus`;const user=await getUser();if(user){go('/minha-conta',true);return}app.innerHTML=`<main class="nx38-auth-page">${story(mode)}${authCard(mode)}</main>`;wireForm(mode);dispatchEvent(new CustomEvent('aninexus:auth-v38-ready'))}
  async function renderAccount(){activate();document.title='Minha conta | AniNexus';if(IS_PAGES){app.innerHTML='<main class="nx38-account-page"><div class="nx38-account-shell"><div class="nx38-pages-note">A conta real está disponível no servidor oficial do AniNexus.</div></div></main>';dispatchEvent(new CustomEvent('aninexus:auth-v38-ready'));return}const user=await getUser(true);if(!user){go('/login',true);return}app.innerHTML='<main class="nx38-account-page"><div class="nx38-account-shell"><div class="nx38-auth-card" style="margin:auto"><i class="nx38-spin"></i></div></div></main>';let list=[],follows=[],notes=[];try{const r=await Promise.allSettled([api('/api/me/list'),api('/api/me/follows'),api('/api/me/notifications?limit=100')]);list=r[0].status==='fulfilled'?r[0].value.items||[]:[];follows=r[1].status==='fulfilled'?r[1].value.items||[]:[];notes=r[2].status==='fulfilled'?r[2].value.items||[]:[]}catch{}const initial=String(user.username||'?').trim().charAt(0).toUpperCase(),watching=list.filter(x=>x.status==='CURRENT').length,done=list.filter(x=>x.status==='COMPLETED').length,unread=notes.filter(x=>!x.read_at).length;app.innerHTML=`<main class="nx38-account-page"><div class="nx38-account-shell"><header class="nx38-account-head"><div class="nx38-account-person"><div class="nx38-account-avatar">${user.avatarUrl?`<img src="${esc(user.avatarUrl)}" alt="">`:esc(initial)}</div><div><h1>${esc(user.username)}</h1><p>${esc(user.email)}</p></div></div><button class="nx38-account-logout" data-logout>Sair da conta</button></header><div class="nx38-account-grid"><div class="nx38-account-stat"><small>ASSISTINDO</small><strong>${watching}</strong></div><div class="nx38-account-stat"><small>CONCLUÍDOS</small><strong>${done}</strong></div><div class="nx38-account-stat"><small>SEGUINDO</small><strong>${follows.length}</strong></div><div class="nx38-account-stat"><small>NOTIFICAÇÕES</small><strong>${unread}</strong></div></div><section class="nx38-account-info"><h2>Conta</h2><dl><dt>Nome de usuário</dt><dd>${esc(user.username)}</dd><dt>E-mail</dt><dd>${esc(user.email)}</dd><dt>Verificação</dt><dd>${user.emailVerified?'E-mail verificado':'Verificação de e-mail ainda não concluída'}</dd><dt>Membro desde</dt><dd>${user.createdAt?new Intl.DateTimeFormat('pt-BR',{dateStyle:'long'}).format(new Date(user.createdAt)):'—'}</dd></dl></section></div></main>`;document.querySelector('[data-logout]')?.addEventListener('click',async e=>{e.currentTarget.disabled=true;try{await api('/api/auth/logout',{method:'POST',body:'{}'})}catch{}currentUser=null;syncHeader();location.assign('/')});dispatchEvent(new CustomEvent('aninexus:auth-v38-ready'))}
  async function render(){if(rendering||!owns())return false;rendering=true;try{const p=route();if(p==='/login')await renderAuth('login');else if(p==='/criar-conta')await renderAuth('register');else await renderAccount();return true}finally{rendering=false}}
  async function syncHeader(){if(IS_PAGES)return;const user=await getUser();const actions=document.querySelector('.top-actions');if(!actions)return;actions.querySelector('.nx38-account-chip')?.remove();const login=actions.querySelector('[data-action="login"]'),register=actions.querySelector('[data-action="register"]');if(user){if(login)login.hidden=true;if(register)register.hidden=true;const b=document.createElement('button');b.className='nx38-account-chip';b.type='button';b.innerHTML=`<i>${esc(String(user.username||'?').charAt(0).toUpperCase())}</i><span>${esc(user.username)}</span>`;b.onclick=()=>go('/minha-conta');actions.insertBefore(b,actions.querySelector('.menu-btn')||null)}else{if(login)login.hidden=false;if(register)register.hidden=false}}
  document.addEventListener('click',e=>{const b=e.target.closest?.('[data-action="login"],[data-action="register"]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();go(b.dataset.action==='login'?'/login':'/criar-conta')},true);
  addEventListener('popstate',()=>setTimeout(render,0));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{syncHeader();render()},{once:true});else{syncHeader();render()}
})();
