'use strict';
(() => {
  const app=document.querySelector('#app');
  if(!app)return;

  const IS_PAGES=location.hostname.endsWith('github.io');
  const BASE=IS_PAGES?'/AniNexus':'';
  const TARGET='/animes/catalogo';
  const BUILD='20.2.0';
  const ENDPOINT='https://graphql.anilist.co';
  const CACHE_TTL=10*60*1000;
  const PER_PAGE=24;
  const GENRES=[['Action','Ação'],['Adventure','Aventura'],['Comedy','Comédia'],['Drama','Drama'],['Fantasy','Fantasia'],['Horror','Terror'],['Mystery','Mistério'],['Romance','Romance'],['Sci-Fi','Ficção Científica'],['Slice of Life','Cotidiano'],['Sports','Esportes'],['Supernatural','Sobrenatural'],['Thriller','Suspense'],['Psychological','Psicológico'],['Music','Música'],['Mecha','Mecha']];
  const FORMATS=[['','Todos os formatos'],['TV','Séries'],['MOVIE','Filmes'],['OVA','OVA'],['ONA','ONA'],['SPECIAL','Especiais']];
  const MODES=[['ALL','Todos','grid','red'],['SOON','Em Breve','clock','blue'],['SEASON','Temporada','leaf','green'],['TOP','Top Animes','trophy','gold'],['POPULAR','Mais Populares','fire','orange'],['MEMBERS','Mais Membros','heart','pink'],['SEARCH','Busca','search','cyan']];
  const ICON={
    grid:'<svg viewBox="0 0 24 24"><rect x="3.5" y="3.5" width="7" height="7" rx="1.7"/><rect x="13.5" y="3.5" width="7" height="7" rx="1.7"/><rect x="3.5" y="13.5" width="7" height="7" rx="1.7"/><rect x="13.5" y="13.5" width="7" height="7" rx="1.7"/></svg>',
    clock:'<svg viewBox="0 0 24 24"><path d="M7 4v3M17 4v3M4 9h16"/><rect x="3.5" y="5.5" width="17" height="15" rx="2.5"/><path d="M12 12v4l2.5 1.5"/></svg>',
    leaf:'<svg viewBox="0 0 24 24"><path d="M20 4C11 4 5 8 5 15c0 3 2 5 5 5 7 0 10-8 10-16Z"/><path d="M4 21c4-6 8-9 13-12"/></svg>',
    trophy:'<svg viewBox="0 0 24 24"><path d="M8 4h8v4c0 4-2 7-4 7s-4-3-4-7V4Z"/><path d="M8 6H4v2c0 2 2 4 4 4M16 6h4v2c0 2-2 4-4 4M12 15v4M8 21h8"/></svg>',
    fire:'<svg viewBox="0 0 24 24"><path d="M13 2c1 4-2 5-1 8 1-2 3-3 4-5 3 3 5 6 5 10a9 9 0 1 1-18 0c0-4 2-7 5-10 0 3 1 4 2 5 0-3 1-5 3-8Z"/></svg>',
    heart:'<svg viewBox="0 0 24 24"><path d="M20.5 8.8c0 5-8.5 10-8.5 10s-8.5-5-8.5-10A4.6 4.6 0 0 1 12 6.4a4.6 4.6 0 0 1 8.5 2.4Z"/></svg>',
    search:'<svg viewBox="0 0 24 24"><circle cx="10.7" cy="10.7" r="6.6"/><path d="m15.7 15.7 4.5 4.5"/></svg>',
    star:'<svg viewBox="0 0 24 24"><path d="m12 3 2.8 5.5 6.1.9-4.4 4.3 1 6.1-5.5-2.9-5.5 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z"/></svg>',
    plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',
    sliders:'<svg viewBox="0 0 24 24"><path d="M4 7h8M16 7h4M4 17h4M12 17h8M12 4v6M8 14v6"/></svg>',
    close:'<svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>',
    retry:'<svg viewBox="0 0 24 24"><path d="M20 7v5h-5"/><path d="M19 12a7 7 0 1 0-2 5"/></svg>',
    chevronDown:'<svg viewBox="0 0 24 24"><path d="m7 9 5 5 5-5"/></svg>'
  };

  const state={mode:'ALL',page:1,search:'',genre:'',format:'',year:'',controller:null,token:0,mounted:false,filtersOpen:false,lastY:Math.max(0,scrollY),scrollRaf:0};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const titleOf=m=>m?.title?.english||m?.title?.userPreferred||m?.title?.romaji||m?.title?.native||'Anime';
  const imageOf=m=>m?.coverImage?.extraLarge||m?.coverImage?.large||`${BASE}/assets/logo.png`;
  const scoreOf=m=>m?.averageScore?(m.averageScore/10).toFixed(1).replace('.0',''):'';
  const fmtNum=n=>new Intl.NumberFormat('pt-BR',{notation:'compact',maximumFractionDigits:1}).format(Number(n)||0);
  const slug=s=>String(s||'anime').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,90);
  const formatLabel=f=>({TV:'Série',TV_SHORT:'Série curta',MOVIE:'Filme',OVA:'OVA',ONA:'ONA',SPECIAL:'Especial',MUSIC:'Música'})[f]||f||'Anime';
  const statusLabel=s=>({RELEASING:'Em exibição',FINISHED:'Finalizado',NOT_YET_RELEASED:'Em breve',HIATUS:'Em hiato',CANCELLED:'Cancelado'})[s]||'';
  const genreLabel=g=>GENRES.find(x=>x[0]===g)?.[1]||g;

  function route(){const u=new URL(location.href),p=u.searchParams.get('p');if(p)return p.split('?')[0].replace(/\/+$/,'')||'/';let path=u.pathname;if(IS_PAGES)path=path.replace(/^\/AniNexus/,'')||'/';return path.replace(/\/+$/,'')||'/'}
  function onCatalog(){return route()===TARGET||!!window.__NX_CATALOG_BOOT__}
  function currentSeason(){const now=new Date(),month=Number(new Intl.DateTimeFormat('en',{timeZone:'America/Sao_Paulo',month:'numeric'}).format(now)),year=Number(new Intl.DateTimeFormat('en',{timeZone:'America/Sao_Paulo',year:'numeric'}).format(now));return{year,season:month<=3?'WINTER':month<=6?'SPRING':month<=9?'SUMMER':'FALL'}}
  function hardGo(path){location.href=IS_PAGES?`${BASE}/?build=${BUILD}&p=${encodeURIComponent(path)}`:path}
  function openAnime(m){history.pushState({},'',`${BASE}/anime/${slug(titleOf(m))}-${m.id}`);window.dispatchEvent(new PopStateEvent('popstate'))}
  function readCache(key){try{const x=JSON.parse(sessionStorage.getItem(`nx:v202:catalog:${key}`)||'null');if(x&&Date.now()-x.t<CACHE_TTL)return x.d}catch{}return null}
  function writeCache(key,data){try{sessionStorage.setItem(`nx:v202:catalog:${key}`,JSON.stringify({t:Date.now(),d:data}))}catch{}}
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));

  const FIELDS=`id title{romaji english native userPreferred} coverImage{extraLarge large color} averageScore popularity favourites episodes format status season seasonYear genres startDate{year month day} studios(isMain:true){nodes{name}}`;
  async function gql(query,variables,signal){let last;for(let attempt=0;attempt<2;attempt++){try{const res=await fetch(ENDPOINT,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({query,variables}),signal});if(res.status===429||res.status>=500)throw new Error(`HTTP ${res.status}`);if(!res.ok)throw new Error(`HTTP ${res.status}`);const json=await res.json();if(json.errors?.length)throw new Error(json.errors[0]?.message||'Consulta inválida');return json.data}catch(err){last=err;if(err?.name==='AbortError')throw err;if(attempt<1)await sleep(420+Math.floor(Math.random()*140))}}throw last||new Error('Falha de rede')}
  function queryOptions(){const o={page:state.page,perPage:PER_PAGE,search:state.search||null,genre:state.genre||null,format:state.format||null,year:state.year?Number(state.year):null,status:null,season:null,sort:['START_DATE_DESC']};if(state.mode==='SOON'){o.status='NOT_YET_RELEASED';o.sort=['POPULARITY_DESC']}else if(state.mode==='SEASON'){const s=currentSeason();o.season=s.season;o.year=state.year?Number(state.year):s.year;o.sort=['POPULARITY_DESC']}else if(state.mode==='TOP')o.sort=['SCORE_DESC','POPULARITY_DESC'];else if(state.mode==='POPULAR')o.sort=['POPULARITY_DESC'];else if(state.mode==='MEMBERS')o.sort=['FAVOURITES_DESC'];else if(state.mode==='SEARCH')o.sort=state.search?['SEARCH_MATCH','POPULARITY_DESC']:['POPULARITY_DESC'];if(state.search&&state.mode!=='SEARCH')o.sort=['SEARCH_MATCH','POPULARITY_DESC'];return o}
  async function fetchCatalog(){const o=queryOptions(),key=JSON.stringify(o),cached=readCache(key);if(cached)return cached;const q=`query($page:Int,$perPage:Int,$search:String,$genre:String,$format:MediaFormat,$season:MediaSeason,$year:Int,$status:MediaStatus,$sort:[MediaSort]){Page(page:$page,perPage:$perPage){pageInfo{total currentPage lastPage hasNextPage}media(type:ANIME,isAdult:false,search:$search,genre:$genre,format:$format,season:$season,seasonYear:$year,status:$status,sort:$sort){${FIELDS}}}}`;const data=await gql(q,o,state.controller?.signal),result={pageInfo:data?.Page?.pageInfo||{},items:data?.Page?.media||[]};writeCache(key,result);return result}

  function modeLabel(){return({ALL:'Todos os animes',SOON:'Chegando em breve',SEASON:'Temporada atual',TOP:'Top Animes',POPULAR:'Mais populares',MEMBERS:'Mais membros',SEARCH:'Resultados da busca'})[state.mode]||'Catálogo'}
  function modeButtons(cls=''){return MODES.map(([k,n,ic,color])=>`<button type="button" class="${cls} nx21-mode-${color} ${state.mode===k?'active':''}" data-nx20-mode="${k}"><i>${ICON[ic]}</i><span>${n}</span></button>`).join('')}
  function skeletons(n=PER_PAGE){return `<div class="nx20-cat-grid">${Array.from({length:n},()=>'<div class="nx20-cat-skeleton"></div>').join('')}</div>`}
  function card(m){const year=m.seasonYear||m.startDate?.year||'',score=scoreOf(m),studio=m.studios?.nodes?.[0]?.name||'',st=statusLabel(m.status);return `<article class="nx20-cat-card" tabindex="0" data-nx20-open="${m.id}"><div class="nx20-cat-poster"><img loading="lazy" decoding="async" src="${esc(imageOf(m))}" alt="${esc(titleOf(m))}"><div class="nx20-cat-shade"></div>${score?`<span class="nx20-cat-score">${ICON.star}<b>${score}</b></span>`:''}${st?`<span class="nx20-cat-status ${m.status==='NOT_YET_RELEASED'?'soon':''}">${esc(st)}</span>`:''}<div class="nx21-card-actions"><button type="button" class="nx21-card-action nx21-list" data-list="${m.id}" aria-label="Adicionar à lista">${ICON.plus}</button><button type="button" class="nx21-card-action nx21-fav" data-fav="${m.id}" aria-label="Favoritar">${ICON.heart}</button></div></div><div class="nx20-cat-copy"><h3>${esc(titleOf(m))}</h3><div class="nx20-cat-meta"><span>${esc(formatLabel(m.format))}</span>${year?`<i></i><span>${year}</span>`:''}${m.episodes?`<i></i><span>${m.episodes} eps</span>`:''}</div><p>${esc((m.genres||[]).slice(0,2).map(genreLabel).join(' · ')||studio||'Anime')}</p><div class="nx20-cat-pop"><span>${fmtNum(m.popularity)} em popularidade</span>${studio?`<span>${esc(studio)}</span>`:''}</div></div></article>`}
  function years(){const y=new Date().getFullYear()+1;return Array.from({length:34},(_,i)=>y-i)}
  function filterMarkup(){return `<label class="nx20-cat-search">${ICON.search}<input id="nx20CatSearch" type="search" autocomplete="off" placeholder="Buscar anime pelo título..." value="${esc(state.search)}"><button type="button" data-nx20-clear aria-label="Limpar busca">${ICON.close}</button></label><select id="nx20CatGenre"><option value="">Todos os gêneros</option>${GENRES.map(([v,n])=>`<option value="${v}" ${state.genre===v?'selected':''}>${n}</option>`).join('')}</select><select id="nx20CatFormat">${FORMATS.map(([v,n])=>`<option value="${v}" ${state.format===v?'selected':''}>${n}</option>`).join('')}</select><select id="nx20CatYear"><option value="">Todos os anos</option>${years().map(y=>`<option value="${y}" ${String(state.year)===String(y)?'selected':''}>${y}</option>`).join('')}</select><button type="button" class="nx20-cat-filter-reset" data-nx20-reset>${ICON.sliders}<span>Limpar</span></button>`}

  function renderShell(){document.body.classList.add('nx20-catalog-active','nx21-catalog-active');document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav==='anime'));app.innerHTML=`<section class="nx21-cat-hero" id="nx21CatalogHero"><div class="shell"><div class="nx21-cat-title"><div class="nx21-cat-title-icon">${ICON.grid}</div><div><h1>Catálogo de <em>Animes</em></h1><p>Todos os animes do catálogo, dos clássicos aos lançamentos da temporada.</p></div></div></div></section><section class="nx21-cat-dock" id="nx21CatalogDock"><div class="shell"><div class="nx21-cat-dock-head"><div class="nx21-cat-mini-title"><span>${ICON.grid}</span><div><strong>Catálogo de Animes</strong><small>EXPLORE E ENCONTRE SEU PRÓXIMO ANIME</small></div></div><button type="button" class="nx21-filter-toggle" data-nx21-filters aria-expanded="false">${ICON.sliders}<span>Filtros</span>${ICON.chevronDown}</button></div><div class="nx21-cat-nav"><button type="button" class="nx21-nav-menu" data-nx21-filters aria-label="Abrir filtros">${ICON.sliders}</button><div class="nx21-cat-tabs">${modeButtons()}</div></div><div class="nx21-filter-panel" id="nx21FilterPanel"><div class="nx20-cat-tools">${filterMarkup()}</div><div class="nx20-cat-chips" id="nx20CatChips"></div></div></div></section><section class="nx20-cat-body"><div class="shell"><div class="nx20-cat-line"><div><small>EXPLORAR</small><h2 id="nx20CatTitle">${modeLabel()}</h2></div><span id="nx20CatPageLabel"></span></div><div id="nx20CatGrid">${skeletons()}</div><nav class="nx20-cat-pages" id="nx20CatPages" aria-label="Paginação"></nav></div></section>`;bindControls();renderChips();load();setupScroll();}

  function renderChips(){const el=document.querySelector('#nx20CatChips');if(!el)return;const chips=[];if(state.search)chips.push(['search',`Busca: ${state.search}`]);if(state.genre)chips.push(['genre',genreLabel(state.genre)]);if(state.format)chips.push(['format',formatLabel(state.format)]);if(state.year)chips.push(['year',String(state.year)]);el.innerHTML=chips.map(([k,v])=>`<button type="button" data-nx20-chip="${k}">${esc(v)} ${ICON.close}</button>`).join('');el.querySelectorAll('[data-nx20-chip]').forEach(b=>b.onclick=()=>{state[b.dataset.nx20Chip]='';state.page=1;syncInputs();renderChips();load();if(innerWidth<700)closeFilters()})}
  function syncInputs(){const s=document.querySelector('#nx20CatSearch'),g=document.querySelector('#nx20CatGenre'),f=document.querySelector('#nx20CatFormat'),y=document.querySelector('#nx20CatYear');if(s)s.value=state.search;if(g)g.value=state.genre;if(f)f.value=state.format;if(y)y.value=state.year}
  function syncModeButtons(){document.querySelectorAll('[data-nx20-mode]').forEach(x=>x.classList.toggle('active',x.dataset.nx20Mode===state.mode));const t=document.querySelector('#nx20CatTitle');if(t)t.textContent=modeLabel()}
  function openFilters(){state.filtersOpen=true;const dock=document.querySelector('#nx21CatalogDock');dock?.classList.add('filters-open','expanded');document.querySelectorAll('[data-nx21-filters]').forEach(b=>b.setAttribute('aria-expanded','true'));document.body.classList.remove('nx21-cat-scroll-down');document.body.classList.add('nx21-cat-scroll-up')}
  function closeFilters(){state.filtersOpen=false;document.querySelector('#nx21CatalogDock')?.classList.remove('filters-open');document.querySelectorAll('[data-nx21-filters]').forEach(b=>b.setAttribute('aria-expanded','false'))}
  function bindControls(){document.querySelectorAll('[data-nx20-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.nx20Mode;state.page=1;syncModeButtons();if(state.mode==='SEARCH'){openFilters();setTimeout(()=>document.querySelector('#nx20CatSearch')?.focus(),50)}else if(innerWidth<700)closeFilters();load()});document.querySelectorAll('[data-nx21-filters]').forEach(b=>b.onclick=()=>state.filtersOpen?closeFilters():openFilters());let timer;const search=document.querySelector('#nx20CatSearch');search.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{state.search=search.value.trim();state.page=1;if(state.search)state.mode='SEARCH';syncModeButtons();renderChips();load()},300)};document.querySelector('[data-nx20-clear]').onclick=()=>{state.search='';state.page=1;search.value='';renderChips();load();search.focus()};document.querySelector('#nx20CatGenre').onchange=e=>{state.genre=e.target.value;state.page=1;renderChips();load();if(innerWidth<700)setTimeout(closeFilters,120)};document.querySelector('#nx20CatFormat').onchange=e=>{state.format=e.target.value;state.page=1;renderChips();load();if(innerWidth<700)setTimeout(closeFilters,120)};document.querySelector('#nx20CatYear').onchange=e=>{state.year=e.target.value;state.page=1;renderChips();load();if(innerWidth<700)setTimeout(closeFilters,120)};document.querySelector('[data-nx20-reset]').onclick=()=>{state.search=state.genre=state.format=state.year='';state.page=1;syncInputs();renderChips();load();if(innerWidth<700)closeFilters()};}

  function pages(info){const root=document.querySelector('#nx20CatPages');if(!root)return;const cur=Number(info.currentPage||state.page||1),last=Math.min(Number(info.lastPage||1),999);if(last<=1){root.innerHTML='';return}const set=new Set([1,last,cur-2,cur-1,cur,cur+1,cur+2].filter(x=>x>=1&&x<=last)),nums=[...set].sort((a,b)=>a-b);let prev=0,out='';for(const n of nums){if(prev&&n-prev>1)out+='<span>…</span>';out+=`<button type="button" class="${n===cur?'active':''}" data-nx20-page="${n}">${n}</button>`;prev=n}root.innerHTML=`<button type="button" class="nav" data-nx20-page="${Math.max(1,cur-1)}" ${cur===1?'disabled':''}>‹</button>${out}<button type="button" class="nav" data-nx20-page="${Math.min(last,cur+1)}" ${cur===last?'disabled':''}>›</button>`;root.querySelectorAll('[data-nx20-page]').forEach(b=>b.onclick=()=>{const p=Number(b.dataset.nx20Page);if(!p||p===cur)return;state.page=p;load();document.querySelector('.nx20-cat-body')?.scrollIntoView({behavior:'smooth',block:'start'})})}
  function bindCards(items){const byId=new Map(items.map(m=>[String(m.id),m]));document.querySelectorAll('[data-nx20-open]').forEach(el=>{const open=()=>{const m=byId.get(el.dataset.nx20Open);if(m)openAnime(m)};el.onclick=e=>{if(e.target.closest('a,button'))return;open()};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}});document.querySelectorAll('.nx20-cat-poster>img').forEach(img=>img.addEventListener('error',()=>{img.src=`${BASE}/assets/logo.png`;img.classList.add('fallback')},{once:true}));window.AniNexusMediaState?.sync?.()}
  async function load(){const grid=document.querySelector('#nx20CatGrid');if(!grid)return;state.controller?.abort();state.controller=new AbortController();const token=++state.token;grid.innerHTML=skeletons();const pagesEl=document.querySelector('#nx20CatPages');if(pagesEl)pagesEl.innerHTML='';const pageLabel=document.querySelector('#nx20CatPageLabel');if(pageLabel)pageLabel.textContent='Carregando…';try{const result=await fetchCatalog();if(token!==state.token||!document.querySelector('#nx20CatGrid'))return;const items=result.items||[],info=result.pageInfo||{},total=Number(info.total||items.length);const totalEl=document.querySelector('#nx21CatalogTotal');if(totalEl)totalEl.textContent=total.toLocaleString('pt-BR');if(pageLabel)pageLabel.textContent=`${total.toLocaleString('pt-BR')} títulos · Página ${info.currentPage||state.page} de ${Math.min(info.lastPage||1,999)}`;const titleEl=document.querySelector('#nx20CatTitle');if(titleEl)titleEl.textContent=modeLabel();grid.innerHTML=items.length?`<div class="nx20-cat-grid">${items.map(card).join('')}</div>`:`<div class="nx20-cat-empty"><img src="${BASE}/assets/logo.png" alt=""><h3>Nenhum anime encontrado</h3><p>Tente remover algum filtro ou pesquisar por outro título.</p><button type="button" data-nx20-reset-empty>Limpar filtros</button></div>`;grid.querySelector('[data-nx20-reset-empty]')?.addEventListener('click',()=>{state.search=state.genre=state.format=state.year='';state.page=1;syncInputs();renderChips();load()});pages(info);bindCards(items)}catch(err){if(err?.name==='AbortError'||token!==state.token)return;grid.innerHTML=`<div class="nx20-cat-error">${ICON.retry}<h3>Não foi possível carregar o catálogo</h3><p>Houve uma falha temporária ao consultar os títulos. Seus filtros foram preservados.</p><button type="button" data-nx20-retry>${ICON.retry} Tentar novamente</button></div>`;if(pageLabel)pageLabel.textContent='Falha ao carregar';grid.querySelector('[data-nx20-retry]').onclick=load}}

  function setupScroll(){state.lastY=Math.max(0,scrollY);const update=()=>{state.scrollRaf=0;if(route()!==TARGET)return;const y=Math.max(0,scrollY),hero=document.querySelector('#nx21CatalogHero'),dock=document.querySelector('#nx21CatalogDock'),topbar=document.querySelector('#topbar');if(!hero||!dock)return;const headerH=topbar?.offsetHeight||58,stuck=hero.getBoundingClientRect().bottom<=headerH+2;dock.classList.toggle('is-stuck',stuck);if(!stuck){document.body.classList.remove('nx21-cat-scroll-down','nx21-cat-scroll-up');dock.classList.remove('expanded');state.lastY=y;return}const delta=y-state.lastY;if(!state.filtersOpen){if(delta>10){document.body.classList.add('nx21-cat-scroll-down');document.body.classList.remove('nx21-cat-scroll-up');dock.classList.remove('expanded')}else if(delta<-10){document.body.classList.add('nx21-cat-scroll-up');document.body.classList.remove('nx21-cat-scroll-down');dock.classList.add('expanded')}}state.lastY=y};const onScroll=()=>{if(!state.scrollRaf)state.scrollRaf=requestAnimationFrame(update)};window.__NX_CAT_SCROLL__&&removeEventListener('scroll',window.__NX_CAT_SCROLL__);window.__NX_CAT_SCROLL__=onScroll;addEventListener('scroll',onScroll,{passive:true});update()}
  function cleanup(){state.controller?.abort();state.mounted=false;closeFilters();document.body.classList.remove('nx20-catalog-active','nx21-catalog-active','nx21-cat-scroll-down','nx21-cat-scroll-up');const top=document.querySelector('#topbar');if(top)top.style.transform='';if(window.__NX_CAT_SCROLL__){removeEventListener('scroll',window.__NX_CAT_SCROLL__);window.__NX_CAT_SCROLL__=null}}
  function mount(force=false){if(!onCatalog()&&!force)return;if(window.__NX_CATALOG_BOOT__){history.replaceState({},'',`${BASE}${TARGET}`);window.__NX_CATALOG_BOOT__=false}if(route()!==TARGET)return;if(state.mounted&&document.querySelector('.nx21-cat-hero'))return;state.mounted=true;renderShell()}

  document.addEventListener('click',e=>{if(route()===TARGET&&!e.target.closest('#nx21CatalogDock')&&state.filtersOpen)closeFilters();const a=e.target.closest('a[href]');if(!a)return;try{const u=new URL(a.href,location.href);let p=u.pathname;if(IS_PAGES)p=p.replace(/^\/AniNexus/,'')||'/';p=p.replace(/\/+$/,'')||'/';if(p!==TARGET)return;if(e.button&&e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();hardGo(TARGET)}catch{}},true);
  window.addEventListener('popstate',()=>setTimeout(()=>{route()===TARGET?mount(true):cleanup()},0));
  new MutationObserver(()=>{if(route()===TARGET&&!document.querySelector('.nx21-cat-hero'))mount(true)}).observe(app,{childList:true,subtree:false});
  mount();
})();
